Move Jira and SonarQube self-service from repo to docs
port-labs/port-docs pull request #1018
Opened 2024-03-25 18:07 UTC by lordsarcastic

# Description

Move Jira and SonarQube self-service from repo to docs.

## Added docs pages

- Open Jira issue with automatic label (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/open-jira-issue-with-automatic-label.md`)
- Add tags to SonarQube project (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/SonarQube/add-tags-to-sonarqube-project.md`)

2024-03-25 19:54 UTC, PeyGis requested changes
please go over my comments and apply them

2024-03-25 19:54 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/open-jira-issue-with-automatic-label.md
> +          project: <PROJECT-KEY> # change the name to your project key
This workflow is great but it appears that if a user wants to use this workflow for 20 projects, they will have to always go to their Github workflow file and replace the project key. This will be problematic. Instead of asking them to enter the project key, let's use the Jira Project entity selection field, so that they user will choose one of the already existing project entities they have in Port. Your task then is to grab the value and map it to this project variable in the action. Doing this will support multiple projects with the same workflow file.

2024-03-25 19:54 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/SonarQube/add-tags-to-sonarqube-project.md
> +          logMessage: Finished request to create ServiceNow incident
This should be changed to SonarQube instead of ServiceNow

2024-03-25 19:54 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/SonarQube/add-tags-to-sonarqube-project.md
> +      - name: Create a log message
Use a relevant step name instead of create a log message

2024-03-25 19:54 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/SonarQube/add-tags-to-sonarqube-project.md
> +      - name: Create a log message
Use a relevant step name instead of create a log message

2024-03-27 14:14 UTC, hadar-co approved these changes

2024-03-27 14:17 UTC, merged