Add docs for Port Execution Agent
port-labs/port-docs pull request #102
Opened 2022-11-27 15:12 UTC by talsabagport

# Description

Add docs for [Port Execution Agent](https://artifacthub.io/packages/helm/port-labs/port-agent)

## Added docs pages

Please also include the path for the added docs

- Port Execution Agent (`/platform-overview/self-service-actions/port-execution-agent`)

## Updated docs pages

Please also include the path for the updated docs

- Blueprint (`/platform-overview/port-components/blueprint`)
- Setting Self Service Actions in Port (`/platform-overview/self-service-actions/setting-self-service-actions-in-port`)

2022-11-29 16:44 UTC, EllaFurman requested changes

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/port-execution-agent.md
> +## Next Steps
```suggestion
# Port execution agent

Our execution agent provides you with a secure and convenient way to listen and act on invocations of Self-Service Actions and changes in the software catalog.

By using the execution agent, you don't need to expose a public endpoint for Port to contact.

The data flow when using the Port execution agent is as follows:

- A new Self-Service Action or change in the software catalog is invoked;
- Port sends the invocation event to your dedicated Kafka topic;
- The execution agent pulls the new invocation event from your Kafka topic, and sends it to the URL you specified.

![Port Agent Architecture](../../../../static/img/platform-overview/self-service-actions/portAgentArchitecture.png)

## Next steps
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/port-execution-agent.md
> +## Next Steps
Remove capital letters from "Self-Service Actions" if it isn't something regular in the docs.

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +This is a walkthrough of how to install the Port Execution Agent in your Kubernetes Cluster.
```suggestion
Let's dive in to a walkthrough on how to install the Port execution agent in your Kubernetes cluster.
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +The helm chart with full installation guide can be found [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```suggestion
You can observe the helm chart with the full installation [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +This is a walkthrough of how to install the Port Execution Agent in your Kubernetes Cluster.
```suggestion
Let's dive in to a walkthrough on how to install the Port execution agent in your Kubernetes cluster.
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +The helm chart with full installation guide can be found [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```suggestion
You can observe the helm chart with the full installation [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +- Connection credentials to Kafka, provided to you by Port.
```suggestion
:::note prerequisites

- The [Helm](https://helm.sh) must be installed to use the chart. Please refer to
  the Helm's [documentation](https://helm.sh/docs) for further details on the installation;
- The connection credentials to Kafka are provided to you by Port.
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +3. Follow one of the following guides:
```suggestion
3. Follow one of the guides below:
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +- [Changelog Listener](../../../tutorials/self-service-actions/webhook-actions/changelog-listener) - to create a Blueprint with `changelogDestination` to listen and act on changes in the Software Cat
```suggestion
- [Setting Self-Service Actions In Port](../setting-self-service-actions-in-port) - set up a Blueprint and Self-Service Actions.
- [Changelog Listener](../../../tutorials/self-service-actions/webhook-actions/changelog-listener) - create a Blueprint with `changelogDestination` to listen and act on changes in the software catalog.
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +- Or it can be a public service accessible from the public internet (**note** that in this scenario, the execution agent needs corresponding outbound network rules that will allow it to contact the p
```suggestion
- Or, it can be a public accessible service from the public internet (**note** in this scenario, the execution agent needs corresponding outbound network rules that will allow it to contact the public service).
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +**IMPORTANT**: To make use of the **Port Execution Agent**, you need to configure:
```suggestion
**IMPORTANT**: To make use of the **Port execution agent**, you need to configure:
```

2022-11-29 16:44 UTC, EllaFurman commented on docs/platform-overview/self-service-actions/port-execution-agent/quickstart.md
> +When a new invocation is detected, the agent will pull it from your Kafka topic and forward it to the internal API in your private network.
```suggestion
Well Done! **Port Agent** is now running in your environment and will trigger any webhook that you've configured (for self-service actions, or changes in the software catalog).

When a new invocation is detected, the agent will pull it from your Kafka topic and forward it to the internal API in your private network.
```

2022-11-30 08:44 UTC, talsabagport commented on docs/platform-overview/self-service-actions/port-execution-agent/port-execution-agent.md
> +## Next Steps
It is the way we do it in other places in the doc

2022-11-30 09:01 UTC, merged