PORT-6938 Add scheduled mode to Azure Ocean Installation guide
port-labs/port-docs pull request #1033
Opened 2024-03-28 17:50 UTC by phalbert

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Updated docs pages

Please also include the path for the updated docs

- [Azure Ocean Installation](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation?installation-methods=one-time&deploy=helm&cicd-method=azure#installation) (`/docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md`)

2024-04-02 16:08 UTC, hadar-co requested changes

2024-04-02 16:08 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +<TabItem value="ui" label="From the UI">
@phalbert Any special reason to add this "From the UI" tab? It's basically installing via Helm like we show in the "Always on" tab, only without all of the parameter descriptions. Also, we don't have such a tab for any other Ocean installation. It should be removed

2024-04-02 16:22 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +<TabItem value="ui" label="From the UI">
Alright @hadar-co. I am removing it. The consistency is necessary.

2024-04-10 12:06 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +<TabItem value="ui" label="From the UI">
@hadar-co , the option under "From the UI" tab uses terraform. Should I go ahead and add it under the Real & Always on tab under "terraform"

<img width="1505" alt="Screenshot 2024-04-10 at 13 05 57" src="https://github.com/port-labs/port-docs/assets/8656262/10082246-3554-4594-8402-5fc391d27ca5">

2024-04-24 14:17 UTC, yairsimantov20 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +    subscriptionId: xxxx-your-subscription-id-xxxxx
I think there is no longer a need for a subscription id as it can assume the ids by its permissions
ask @Tankilevitch

2024-05-01 13:37 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +scheduledResyncInterval: 120
@yairsimantov20, I noticed this setting appears in many Ocean integration docs. Would it be more appropriate to have a 60-minute default instead of 120? I'm happy to create a PR to make this change across the board.

2024-05-01 13:43 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +To install the integration using ArgoCD, follow these steps:
@yairsimantov20, Do elaborate please. Should it not be an option?

2024-05-22 08:17 UTC, Tankilevitch requested changes

2024-05-22 08:17 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +| `integration.secrets.subscriptionId`            | Your Azure Subscription ID            |   | ✅       |
it is not required any more

2024-05-22 08:17 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +| `integration.config.appHost`             | The host of the Port Ocean app. Used to set up the integration endpoint as the target for webhooks created in Jira                         | https://my-oc
it is not a jira integration

2024-05-22 08:17 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +          -e OCEAN__INTEGRATION__SECRET__AZURE_SUBSCRIPTION_ID=$OCEAN__SECRET__AZURE_SUBSCRIPTION_ID \
remove as well

2024-05-22 08:17 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +                                -e OCEAN__INTEGRATION__SECRET__AZURE_SUBSCRIPTION_ID=$OCEAN__SECRET__AZURE_SUBSCRIPTION_ID \
sane

2024-05-22 08:17 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
> +            subscriptionId: ${{ secrets.OCEAN__SECRET__AZURE_SUBSCRIPTION_ID }}
remove

2024-05-31 09:10 UTC, hadar-co commented
@Tankilevitch review and merge

2024-06-02 09:53 UTC, Tankilevitch approved these changes

2024-06-02 10:13 UTC, hadar-co approved these changes

2024-06-02 10:14 UTC, merged