PORT-7273 | DORA Metrics
port-labs/port-docs pull request #1035
Opened 2024-03-28 18:18 UTC by mk-armah

# Description
This docs provides a comprehensive guide for creating a GitHub action computes DORA Metrics for a service (repo)

## Inputs
| Name                 | Description                                                                                          | Required | Default            |
|----------------------|------------------------------------------------------------------------------------------------------|----------|--------------------|
| repository              | GitHub repository in owner/repo format eg. port-labs/self-service-actions                               | true     | -                  |
| timeframe              | Time frame in weeks to calculate metrics on                                                              | true    | -               |
| workflow              | The name of the workflows to process. Multiple workflows can be separated by a comma (,) .                                                              | true    | -               |

- Resource Path (`/create-self-service-experiences/setup-backend/github-workflow/examples/dora-metrics`)

2024-03-29 10:50 UTC, MPTG94 requested changes
Some initial comments

2024-03-29 10:50 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/dora-metrics.md
> +- `<Entity-ID>` - your target entity id in port
```suggestion
- `<Entity-ID>` - your target entity identifier in Port
```

2024-03-29 10:50 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/dora-metrics.md
> +```json showLineNumbers title="sample input json"
```suggestion
```json showLineNumbers
```

2024-03-29 10:50 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/dora-metrics.md
> +5. Create the following python scripts (`calculate_pr_metrics.py`, `deployment_frequency.py` and `lead_time_for_changes.py` ) in a folder named `dora` at the root of your GitHub repository:
```suggestion
5. Create the following Python scripts (`calculate_pr_metrics.py`, `deployment_frequency.py` and `lead_time_for_changes.py` ) in a folder named `dora` at the root of your GitHub repository:
```

2024-03-31 09:35 UTC, hadar-co approved these changes

2024-03-31 09:36 UTC, merged