Add merge=true flag to the Docs
port-labs/port-docs pull request #104
Opened 2022-11-27 16:34 UTC by talsabagport

# Description

Add merge=true flag to the Docs

## Updated docs pages

Please also include the path for the updated docs

- Entity Basics (`/tutorials/entity-basics.md`)

2022-11-27 16:47 UTC, danielsinai requested changes
🦢 looks great

2022-11-27 16:47 UTC, danielsinai commented on docs/tutorials/entity-basics.md
> +  Moreover, another flag called `merge` is available. Adding `merge=true` to the request allows you to update only specific properties, just like in PATCH request.
Looks great, can you just specify it must come with the upsert flag =true?

2022-11-27 16:54 UTC, talsabagport commented on docs/tutorials/entity-basics.md
> +  Moreover, another flag called `merge` is available. Adding `merge=true` to the request allows you to update only specific properties, just like in PATCH request.
done

2022-11-28 10:39 UTC, danielsinai approved these changes

2022-11-28 12:05 UTC, merged