Port 7533 Update wiz docs to show information on config params
port-labs/port-docs pull request #1071
Opened 2024-04-04 11:26 UTC by phalbert

# Description

- Fix variable declaration from ${VARIABLE_NAME}, to $(VARIABLE_NAME)
- Add guide on setting variable groups.
- Add comment on how to get Wiz credentials

## Updated docs pages

Please also include the path for the updated docs

- Blueprint (`/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md`)

2024-04-04 12:08 UTC, hadar-co requested changes

2024-04-04 12:08 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +:::info GETTING YOUR WIZ CREDENTIALS
@phalbert sending an email in order to get your client ID and secret seems strange. Here is a doc page of another product that explains how to acquire them:
https://docs.safe.security/docs/wizio#42-client-id-and-client-secret

Please change the instructions to these.

2024-04-04 12:52 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +:::info GETTING YOUR WIZ CREDENTIALS
Thanks a lot for this link. I have revised the instructions now.

2024-04-04 22:02 UTC, MPTG94 requested changes
Please make updates according to my comments

2024-04-04 22:02 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +<img src='/img/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wizApi.png' width='85%' border='1px' />
This image is wrong, take a better look at the docs @hadar-co linked, the image that should be here is different.

2024-04-04 22:02 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Log in to Wiz: Access your Wiz account.
This section is missing one of the images from the guide @hadar-co linked

2024-04-05 10:34 UTC, phalbert commented
@MPTG94 I have resolved these

2024-04-07 11:24 UTC, MPTG94 requested changes
Please apply my suggestions

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Log in to Wiz account.
```suggestion
    - Login to your Wiz account.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Click the User Profile icon (top right) and select "User Settings."
```suggestion
    - Click the **User Profile** icon available at the top right of the screen and click the **User Settings** option.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Click "Tenant" in the left menu.
```suggestion
    - Click the **Tenant** option from the left options menu.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Copy the API Endpoint URL: It will be displayed on the screen.
```suggestion
    - The system displays the **API Endpoint URL**.
    - Copy and save the **API URL** to use while configuring the Wiz intergration.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Log in to Wiz: Access your Wiz account.
```suggestion
You must create a service account in Wiz to generate the Client ID and Client Secret. Follow the below steps to get the Client ID and Client Secret:
    - Login to **Wiz with the Project Admin role**.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Open Settings: Click the Settings icon (top-right).
```suggestion
    - Click the **Settings** icon available at the top-right of the page.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +    - Go to Service Accounts: In the left menu, find and select "Service Accounts".
```suggestion
    - On the Settings page, Click **Service Accounts** from the left menu.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +        - Click "Add Service Account".
```suggestion
        - Click **Add Service Account**.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +        - Provide a descriptive "Service Account Name".
```suggestion
        - Provide a descriptive **Service Account Name**.
```

2024-04-07 11:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +        - Type: Select "Custom Integration (GraphQL API)".
```suggestion
        - Type: Select **Custom Integration (GraphQL API)**.
```

2024-04-09 17:33 UTC, phalbert commented
@MPTG94, thanks for catching these. They were avoidable. I will be keen.

2024-04-30 08:40 UTC, MPTG94 approved these changes
LGTM

2024-04-30 08:40 UTC, merged