Add k8s exporter configuration - resync
port-labs/port-docs pull request #108
Opened 2022-11-28 15:50 UTC by talsabagport

# Description

Add k8s exporter configuration page - including advanced configuration (re-sync).

## Added docs pages

Please also include the path for the added docs

- Quickstart (`exporters/k8s-exporter/configuration.md`)

2022-11-29 16:45 UTC, MPTG94 requested changes
Please see attached comments.

resyncinterval needs a better explanation IMO, it is not completely clear how it works with regards to other objects managed by the K8S exporter.

In addition, add language tagging and showLineNumbers for the code blocks in the exporter quickstart page too

2022-11-29 16:45 UTC, MPTG94 commented on docs/exporters/k8s-exporter/configuration.md
> +    helm install my-port-k8s-exporter port-labs/port-k8s-exporter \
Please wrap in code block, tag as bash and add showLineNumbers

2022-11-29 16:45 UTC, MPTG94 commented on docs/exporters/k8s-exporter/configuration.md
> +    helm install my-port-k8s-exporter port-labs/port-k8s-exporter \
Same comment as the previous code block

2022-11-29 16:45 UTC, MPTG94 commented on docs/exporters/k8s-exporter/configuration.md
> +| **`secret.secrets.portClientId`**     | Port Client ID.                                                                  |
Is there a reason to both code block and bold these parameters?

2022-11-29 16:45 UTC, MPTG94 commented on docs/exporters/k8s-exporter/configuration.md
> +| `resyncInterval` | The interval in minutes before sending a sync event for all known objects. | `0` (re-sync disabled) | Reconciliation every X minutes. For example, if your entity has a related ta
```suggestion
| `resyncInterval` | The interval in minutes before sending a sync event for all known objects. | `0` (re-sync disabled) | Reconciliation every X minutes. For example, if your Entity has a related target Entity that still does not exists, it will try again later. |
```

2022-11-30 09:59 UTC, MPTG94 approved these changes
Looks good, ask Ella to proof read

2022-11-30 09:59 UTC, MPTG94 commented on docs/exporters/k8s-exporter/configuration.md
> +| `resyncInterval` | The interval in minutes to send a repeated sync event for all known existing objects (regardless of new sync events). | `0` (re-sync disabled) | Reconciliation every X minutes. F
```suggestion
| `resyncInterval` | The interval in minutes to send a repeated sync event for all known existing objects (regardless of new cluster events). | `0` (re-sync disabled) | Re-sync every X minutes. For example, your Entity might have a Related target Entity that does not exist yet at the time of a sync event. The sync will fail, but later when the target Entity is available, the Entity creation will succeed (re-sync occurs continually every X minutes). |
```

2022-11-30 10:48 UTC, EllaFurman requested changes

2022-11-30 10:48 UTC, EllaFurman commented on docs/exporters/k8s-exporter/configuration.md
> +## How to configure the Kubernetes Exporter?
```suggestion
## How to configure the Kubernetes exporter?
```

2022-11-30 10:48 UTC, EllaFurman commented on docs/exporters/k8s-exporter/configuration.md
> +### Required Configuration
```suggestion
### Required configuration
```

2022-11-30 10:48 UTC, EllaFurman commented on docs/exporters/k8s-exporter/configuration.md
> +| `configMap.config`                | Port K8s Exporter `config.yaml`. Look at [Quickstart](./quickstart) for example. |
```suggestion
| `secret.secrets.portClientId`     | Port Client ID                                                              |
| `secret.secrets.portClientSecret` | Port Client Secret                                                              |
| `configMap.config`                | Port K8s Exporter `config.yaml`. Look at [Quickstart](./quickstart) for example |
```

2022-11-30 10:48 UTC, EllaFurman commented on docs/exporters/k8s-exporter/configuration.md
> +| `resyncInterval` | The interval in minutes to send a repeated sync event for all known existing objects (regardless of new cluster events). | `0` (re-sync disabled) | Re-sync every X minutes. For e
```suggestion
| `resyncInterval` | The interval in minutes to send a repeated sync event for all known existing objects (regardless of new cluster events). | `0` (re-sync disabled) | Re-sync every X minutes. For example, your Entity might have a related target Entity that does not exist yet at the time of a sync event. The sync will fail, but later when the target Entity is available, the Entity creation will succeed (re-sync occurs continually every X minutes). |
```

2022-11-30 13:31 UTC, merged