PORT-7002 | Restart Argocd Application
port-labs/port-docs pull request #1080
Opened 2024-04-05 17:18 UTC by mk-armah

# Description

Guide to create a self-service action in Port that executes a [GitHub workflow](/create-self-service-experiences/setup-backend/github-workflow/github-workflow.md) to restart an Argo CD application.

## Added docs pages
- Resource Path (`/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app`)

2024-04-17 10:18 UTC, PeyGis requested changes
LGTM. Just some minor comments

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +    - `ARGO_CD_PASSWORD` - Argo CD token [learn more](https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)
This is a bit confusing. The variable is ARGO_CD_PASSWORD but the description says ArgoCD token. Which one is correct?

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +1. Install the Ports GitHub app from [here](https://github.com/apps/getport-io/installations/new).
Port instead of Ports

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +  "identifier": "running_service",
The identifier should use camelCase, and must be consistent with what's in the ocean integration: argocdApplication

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +        uses: actions/checkout@v2
The actions/checkout has version 4, let's use it instead of @v2

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +          ARGO_CD_SERVER: ${{ inputs.argocd_server }}
I don't see where you're using the ARGO_CD_SERVER env variable in this step. Let's remove it or change the argocd login command to reference the ARGO_CD_SERVER instead of ${{ inputs.argocd_server }}

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +          logMessage: "Waiting for application to stabilize ... "
I don't see why we are separating these steps. You can easily merge them into one log message:

logMessage: "Successfully restarted Deployment ✅, Waiting for application to stabilize ..."

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +        "description": "The Argo CD Application Server. eg. my-argocd-server.com",
In the github workflow, you had stated that the server doesn't need to have the https prefix. But you forgot to have it here in the description. This may create confusion

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +      "application_name"
Why is application_name the only required input? I thought the argo server should be made required too since it doesn't have a default value

2024-04-17 10:18 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +4. Select the new status
I am not sure  I understand what you mean by select new status

2024-04-30 09:18 UTC, stavbernazport commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +      - name: Report Failure In Installing Argo CD CLI
Does reporting CLI installation success/failure really necessary?
We would like to keep these pipelines as simple and clear as possible
I think it's better to ditch them to reduce complexity and length of the pipeline

2024-05-09 08:49 UTC, mk-armah commented
This PR will be reopened at [PORT-7658-control-the-payload-docs](https://github.com/port-labs/port-docs/tree/PORT-7658-control-the-payload-docs) branch

2024-05-12 13:37 UTC, hadar-co approved these changes

2024-05-13 17:24 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +    - `ARGO_CD_PASSWORD` - [Argo CD PASSWORD](https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)
```suggestion
    - `ARGO_CD_PASSWORD` - [Argo CD Password](https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)
```

2024-05-14 11:29 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/restart-argocd-app.md
> +- [Rollback Argo CD Deployment](/create-self-service-experiences/setup-backend/github-workflow/examples/ArgoCD/rollback-argocd-deployment) using Port's self-service actions.
```suggestion
- [Rollback Argo CD Deployment](/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/rollback-argocd-deployment) using Port's self-service actions.

```

2024-05-14 11:47 UTC, merged