PORT-7728 | Add guide to the OpenCost integration showing how to bring cost information from AWS
port-labs/port-docs pull request #1125
Opened 2024-04-26 12:01 UTC by lordsarcastic

# Description
Added guide for CloudCost integration in OpenCost. Included guide to bring cost information for specific providers.

## Updated docs pages

Please also include the path for the updated docs

- OpenCost (`docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md`)

2024-04-26 13:34 UTC, PeyGis requested changes
some minor comments

2024-04-26 13:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- Map you cost allocations from different providers from OpenCost.
```suggestion
- Map you cost allocations from different cloud providers from OpenCost.
```

2024-04-26 13:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +    "description": "This blueprint represents an instance of OpenCost CloudCost data",
```suggestion
    "description": "This blueprint represents cloud cost allocations from your OpenCost instance",
```
This blueprint represents cloud cost allocations from your OpenCost instance

2024-04-26 13:36 UTC, PeyGis requested changes

2024-04-26 13:36 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- [`CloudCost](https://www.opencost.io/docs/integrations/api-examples#cloudcost-examples)
```suggestion
- [`Cloud Cost`](https://www.opencost.io/docs/integrations/api-examples#cloudcost-examples)
```

2024-04-28 08:19 UTC, talru1123 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- Map you cost allocations from different cloud providers from OpenCost.
Map your*

2024-04-30 10:38 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- Map you cost allocations from different cloud providers from OpenCost.
```suggestion
- Map your cost allocations from different cloud providers from OpenCost.
```

2024-04-30 10:39 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +  - **window** - Duration of time over which to query. Accepts: words like `today`, `week`, `month`, `yesterday`, `lastweek`, `lastmonth`; durations like `30m`, `12h`, `7d`; RFC3339 date pairs like `
```suggestion
  - **window** - Duration of time over which to query. Accepts words like: `today`, `week`, `month`, `yesterday`, `lastweek`, `lastmonth`; durations like `30m`, `12h`, `7d`; RFC3339 date pairs like `2021-01-02T15:04:05Z,2021-02-02T15:04:05Z`; Unix timestamps like `1578002645,1580681045`. If not specified, the default value is `"today"`
```

2024-04-30 10:40 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- **window** - Duration of time over which to query. Accepts: words like `today`, `week`, `month`, `yesterday`, `lastweek`, `lastmonth`; durations like `30m`, `12h`, `7d`; RFC3339 date pairs like `20
```suggestion
- **window** - Duration of time over which to query. Accepts words like: `today`, `week`, `month`, `yesterday`, `lastweek`, `lastmonth`; durations like `30m`, `12h`, `7d`; RFC3339 date pairs like `2021-01-02T15:04:05Z,2021-02-02T15:04:05Z`; Unix timestamps like `1578002645,1580681045`. If not specified, the default value is `"today"`
```

2024-04-30 10:48 UTC, stavbernazport approved these changes
LGTM

2024-04-30 10:49 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
> +- [`CloudCost](https://www.opencost.io/docs/integrations/api-examples#cloudcost-examples)
```suggestion
- [`Cloud Cost](https://www.opencost.io/docs/integrations/api-examples#cloudcost-examples)
```

2024-04-30 10:52 UTC, merged