Port-8073 | PORT-8128 | Updated action guide for creating pagerduty incident
port-labs/port-docs pull request #1209
Opened 2024-05-16 10:01 UTC by mk-armah

# Description

-  Changed action type from CREATE to DAY-2.
-  Updated port action to send payload context directly as inputs.
-  Updated GitHub action to utilize inputs from port context.

## Updated docs pages

Path for the updated docs

/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-incident

2024-05-19 10:17 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-incident.md
> +      "{{if (.inputs | has(\"extra_details\")) then \"extra_details\" else null end}}": "{{.inputs.\"extra_details\"}}",
```suggestion
      "extra_details": "{{.inputs.\"extra_details\"}}",
```

2024-05-19 10:17 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-incident.md
> +      "{{if (.inputs | has(\"extra_details\")) then \"extra_details\" else null end}}": "{{.inputs.\"extra_details\"}}",
This goes for the other inputs as well

2024-05-20 11:57 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-incident.md
> +      "{{if (.inputs | has(\"from\")) then \"from\" else null end}}": "{{.inputs.\"from\"}}",
```suggestion
      "from": "{{.inputs."from"}}",
```
and the other inputs too

2024-05-23 14:40 UTC, yairsimantov20 requested changes
go over @pazhersh comments

2024-05-23 14:58 UTC, pazhersh approved these changes

2024-05-23 15:05 UTC, merged