Port 8079 update GitHub actions for aws
port-labs/port-docs pull request #1212
Opened 2024-05-16 14:51 UTC by phalbert

# Description

Update the AWS GitHub guides with the v2 actions schema
<img width="1189" alt="Screenshot 2024-05-16 at 15 51 45" src="https://github.com/port-labs/port-docs/assets/8656262/e498ce88-3fb3-4839-bbb9-f6d93d1e51b9">

## Updated docs pages

Please also include the path for the updated docs

- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-s3-bucket.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-eks-cluster-and-deploy-app.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/deploy-cloudformation-template.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/manage-ec2-instances.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/push-image-to-ecr.md

2024-05-19 09:56 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/push-image-to-ecr.md
>      steps:
I see you've added new steps that weren't a part of the workflow before

Have you copied them from another workflow or are they completely new?

2024-05-20 13:12 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +      "context": {
Can you please rename it to `port_context`?

2024-05-20 13:12 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +      context:
don't forget to rename here too :)

2024-05-21 06:26 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance.md
> +      "context": {
```suggestion
      "port_context": {
```

2024-05-21 06:26 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance.md
> +      context:
```suggestion
      port_context:
```

2024-05-21 06:26 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/manage-ec2-instances.md
> +      "context": {
```suggestion
      "port_context": {
```

2024-05-21 06:26 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/push-image-to-ecr.md
> +      "context": {
```suggestion
      "port_context": {
```

2024-05-23 14:39 UTC, yairsimantov20 requested changes
go over @pazhersh comments

2024-05-23 15:00 UTC, pazhersh requested changes

2024-05-23 15:00 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance.md
> +          runId: ${{ fromJson(inputs.context).runId }}
don't forget to change here too, and in the other usages as well

2024-05-26 10:43 UTC, merged