Port 8076 update GitHub actions for k8s slack and more
port-labs/port-docs pull request #1213
Opened 2024-05-16 15:38 UTC by phalbert

# Description

Update Github actions for K8s, Slack and More

## Updated docs pages

Please also include the path for the updated docs

- docs/create-self-service-experiences/setup-backend/github-workflow/examples/kubernetes/manage-clusters.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/promote-to-production.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/broadcast-api-consumers-message.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/manage-pull-requests.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/nudge-pr-reviewers.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel.md

2024-05-19 10:09 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/nudge-pr-reviewers.md
> +        "entity": "{{.entity.identifier}}",
Im pretty sure you need to send the entire entity since you use sub properties from it
```suggestion
        "entity": "{{.entity}}",
```

2024-05-23 14:40 UTC, yairsimantov20 requested changes
go over @pazhersh comments

2024-05-23 15:01 UTC, pazhersh approved these changes

2024-05-24 14:35 UTC, phalbert commented
> go over @pazhersh comments

I have gone over them now, and updated the PR

2024-05-28 07:02 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel.md
> +>>>>>>> main
you missed some conflicts in this file

2024-05-28 11:37 UTC, merged