Ppdated Pagerduty Self Service GitHub Actions
port-labs/port-docs pull request #1215
Opened 2024-05-17 00:11 UTC by mk-armah

# Description
Improved existing pagerduty guides and fixed bug in obtaining the entity ids

## Updated docs pages
/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/

### BugFix  
 - correct entity identifer in port action to `.entity.identifier`

### Improvement
- Added `relations` field to all DAY-2 actions
- Improved actions to report updated runs back to port

2024-05-19 10:16 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/acknowledge-incident.md
>        "{{if (.inputs | has(\"from\")) then \"from\" else null end}}": "{{.inputs.\"from\"}}",
```suggestion
      "from": "{{.inputs.\"from\"}}",

```

2024-05-19 10:16 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/change-on-call-user.md
>        "{{if (.inputs | has(\"new_on_call_user\")) then \"new_on_call_user\" else null end}}": "{{.inputs.\"new_on_call_user\"}}",
all the inputs here too could go through this change:
```suggestion
      "new_on_call_user": "{{.inputs.\"new_on_call_user\"}}",

```

2024-05-19 10:16 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/change-on-call-user.md
>        "{{if (.inputs | has(\"new_on_call_user\")) then \"new_on_call_user\" else null end}}": "{{.inputs.\"new_on_call_user\"}}",
Thats relevant for the other files in this PR as well

2024-05-19 10:16 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-service.md
> +      - name: Extract User Emails
Did you copy these steps from somewhere or are they completely new?

2024-05-19 10:16 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident.md
> +      - name: Get PagerDuty Incident Details
here too, are the new steps in this pr copied from another example we have, or are they completely new here?

2024-05-20 10:14 UTC, mk-armah commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-service.md
> +      - name: Extract User Emails
i'm not sure i understand

2024-05-20 10:20 UTC, mk-armah commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident.md
> +      - name: Get PagerDuty Incident Details
Its new. I just extended the capabilities of the action to report back to port. it was not so initially

2024-05-23 14:39 UTC, yairsimantov20 requested changes
go over @pazhersh comments

2024-05-23 15:04 UTC, pazhersh approved these changes

2024-05-23 15:04 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/PagerDuty/create-pagerduty-service.md
> +      - name: Extract User Emails
allright, cool

2024-05-23 15:06 UTC, yairsimantov20 approved these changes

2024-05-28 08:20 UTC, merged