PORT-8073 | Update Self Service Action for Creating Slack Channel
port-labs/port-docs pull request #1219
Opened 2024-05-17 09:09 UTC by mk-armah

# Description

Replaced `port_payload` with similar feature that sends essential `port_context` via the action input. This to take advantage of the control the payload feature of Port actions.

## Updated docs pages
create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel

2024-05-19 10:20 UTC, pazhersh commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel.md
>        "{{if (.inputs | has(\"members\")) then \"members\" else null end}}": "{{.inputs.\"members\"}}",
you can clean the inputs
```suggestion
      "members": "{{.inputs.\"members\"}}",
```

2024-05-23 14:37 UTC, yairsimantov20 approved these changes
🌊

2024-05-23 14:38 UTC, yairsimantov20 requested changes
go over @pazhersh comment

2024-05-26 11:18 UTC, pazhersh approved these changes

2024-05-26 11:19 UTC, merged