PORT-7257 | Add the Upbound EKS as a service use case to our docs
port-labs/port-docs pull request #1221
Opened 2024-05-17 18:14 UTC by lordsarcastic

# Description

Added Upbound EKS as a service to the docs

## Added docs pages

- Quickstart (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md`)

2024-05-27 06:02 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +Remember to change `CHANGE_TO_YOUR_GITHUB_ORG_NAME` and `CHANGE_TO_YOUR_REPO_NAME` values in the action blueprint.  You need to replace these with your appropriate Github organization name and reposi
```suggestion
Remember to change `CHANGE_TO_YOUR_GITHUB_ORG_NAME` and `CHANGE_TO_YOUR_REPO_NAME` values in the action blueprint. You need to replace these with your appropriate Github organization name and repository name.
```

2024-05-27 06:02 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +      "{{if (.inputs | has(\"ref\")) then \"ref\" else null end}}": "{{.inputs.\"ref\"}}",
Update the inputs syntax here to just take the input fields, there's no need for the `{{if (.inputs.....}}` in the input key selection

2024-05-27 06:04 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +        "context": {
This input does not appear in the workflow, it is also called context instead of being called port_context

2024-05-27 06:04 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +{
Same comments as previous Port SSA

2024-05-27 06:04 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +    "workflowInputs": {
Same comments as previous Port SSA

2024-05-27 06:04 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +    "workflowInputs": {
Same comments as previous Port SSA

2024-05-27 06:04 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +    "workflowInputs": {
Same comments as previous Port SSA

2024-05-27 06:05 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +These entities will represent the different Upbound control planes which were created earlier.
```suggestion
These entities will represent the different Upbound control planes which you created in your Upbound organization.
```

2024-05-27 06:36 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +3. In the `identifier` field, insert the Upbound control plane `identifier` which we saved earlier and click create (do this step multiple times if there are more than 1 control planes).
```suggestion
3. In the `identifier` field, insert the Upbound control plane `identifier` which we saved earlier and click create (do this step multiple times if there is more than one control plane).
```

2024-05-27 06:40 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/upbound-port-capabilities.md
> +At this point, everything should be set up. Browse to your [Self-service](https://app.getport.io/self-serve) page to view the different actions you defined in Port, and try them out.
Add an explanation about the example flows that are available using these actions:

- Create an EKS cluster from Port (as a Port admin/platform engineer)
- Request an EKS cluster from Port (as a Port member/developer)
- Approve an EKS cluster request
- Deny an EKS cluster request
- Delete an EKS cluster

2024-06-28 10:03 UTC, hadar-co requested changes

2024-06-28 10:03 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Upbound/eks-as-a-service-action.md
> +# EKS as a service action (EKSaaS)
the file is in the wrong location, see my Slack message

2024-06-29 09:38 UTC, hadar-co approved these changes

2024-06-29 09:39 UTC, merged