PORT-7361 | Mini guide to connect Github repository with SonarQube project
port-labs/port-docs pull request #1238
Opened 2024-05-22 08:35 UTC by lordsarcastic

# Description
This mini guide is on the other direction of [connect SonarQube project to service](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-sonar-project-to-service) but does the connection on the GitHub side

## Added docs pages

Please also include the path for the added docs

- Connect GitHub repository with SonarQube project (`docs/build-your-software-catalog/sync-data-to-catalog/git/github/guides/connect-github-repository-with-sonarqube-project.md`)

2024-05-23 14:22 UTC, yairsimantov20 commented
i dont see it in the list of guides in here 
https://pr-1238.d2ngvl90zqbob8.amplifyapp.com/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis/

2024-05-23 14:24 UTC, yairsimantov20 requested changes
i dont see it in the list of guides in here
https://pr-1238.d2ngvl90zqbob8.amplifyapp.com/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis/

2024-06-09 13:52 UTC, yairsimantov20 approved these changes
🌊 Tech stuff looks good

2024-06-16 14:51 UTC, hadar-co requested changes

2024-06-16 14:51 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/guides/connect-github-repository-with-sonarqube-project.md
> +import PortTooltip from "/src/components/tooltip/tooltip.jsx"
@lordsarcastic The new "guides" folder has a lowercase "g" in the sidebar, it should be "Guides". To resolve this, please add a `_category_.json` file to the folder, see other folders for examples.

2024-06-20 14:37 UTC, hadar-co approved these changes

2024-06-20 14:37 UTC, merged