Port 2109 create a docs
port-labs/port-docs pull request #124
Opened 2022-12-15 12:20 UTC by dvirsegev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2022-12-16 16:47 UTC, MPTG94 requested changes
Please extend the example inside the deep dive page, we need to show an example with a larger request body that has more content so the user understand that not only the timer property that expired is sent to him in the action event

2022-12-19 12:02 UTC, EllaFurman requested changes

2022-12-19 12:02 UTC, EllaFurman commented on docs/software-catalog/blueprint/timer-properties.md
> +# Timer Properties
```suggestion
# Timer properties
```

2022-12-19 12:02 UTC, EllaFurman commented on docs/software-catalog/blueprint/timer-properties.md
> +Let's look at some examples of basic timer properties definitions to better understand how timer properties work:
```suggestion
Let's look at some examples of basic timer properties definitions to better understand how timer properties work.
```

2022-12-19 12:02 UTC, EllaFurman commented on docs/software-catalog/blueprint/timer-properties.md
> +In the following example, we create a timer property called locked, that will expire in 2 hours:
```suggestion
In the following example, we will create a timer property called locked, that will expire in 2 hours:
```

2022-12-20 07:55 UTC, MPTG94 approved these changes
LGTM

2022-12-20 08:02 UTC, merged