Update snyk default blueprints
port-labs/port-docs pull request #1261
Opened 2024-05-31 11:09 UTC by phalbert

# Description

Update Snyk default blueprints. Complements https://github.com/port-labs/ocean/pull/676
 
## Updated docs pages

Please also include the path for the updated docs

- Snyk Integration (`docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md`)

2024-06-17 17:44 UTC, Tankilevitch requested changes

2024-06-17 17:44 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
> +      "many": false
shouldn't it be `required: true` is there a case where project won't be part of an organization?

2024-06-25 22:17 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
> +      "many": false
It should be but since we have already merged https://github.com/port-labs/ocean/commit/57037de7a471d498a138c5e4e66c971d52d4dfcd, we'll open another PR to update both in ocean and docs

2024-06-26 06:29 UTC, Tankilevitch approved these changes

2024-06-26 09:36 UTC, merged