PORT-8401 | Jira Integration docs | Fix webhook docs + change priority to name
port-labs/port-docs pull request #1262
Opened 2024-05-31 11:50 UTC by lordsarcastic

# Description

Changed the priority field from an ID to name, changed webhooks Jira Issue blueprint to be consistent with integration blueprint

## Updated docs pages

- Jira (`docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md`)

2024-06-09 13:26 UTC, MPTG94 requested changes
Please take a look at my comment

2024-06-09 13:26 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/resources/jira/_example_jira_issue_configuration.mdx
> +        "url": "(.self | split(\"/\") | .[:3] | join(\"/\")) + \"/browse/\" + .key",
All of the changes here assume that the payload is received from the webhook in the same way that they are received in Ocean. But it is not the case, the webhook has a request body that also needs to be taken into account.

If you want to update the mapping here, please setup a Jira webhook and test the webhook configuration before making the update

2024-07-30 07:09 UTC, erikzaadi requested changes
Some small nits

2024-07-30 07:09 UTC, erikzaadi commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
> +  # highlight-next-line
Nice, didn't know about the highlight comments, very cool

2024-07-30 07:09 UTC, erikzaadi commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
> +  - kind: sprint # `state` is only available with the "spring" kind
Typo?
```suggestion
  - kind: sprint # `state` is only available with the "sprint" kind
```

2024-07-30 07:09 UTC, erikzaadi commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
>        "48x48": "https://secure.gravatar.com/avatar/9df2ac1caa70b0a67ff0561f7d0363e5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIC-1.png"
![](https://secure.gravatar.com/avatar/9df2ac1caa70b0a67ff0561f7d0363e5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIC-1.png) 
This on purpose?

2024-08-06 02:09 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
>        "48x48": "https://secure.gravatar.com/avatar/9df2ac1caa70b0a67ff0561f7d0363e5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIC-1.png"
Yes, the email field is a part of the response. Also didn't want to expose sensitive information, so "shadow" takes the brunt...

2024-08-09 14:40 UTC, erikzaadi approved these changes

2024-09-02 15:02 UTC, hadar-co approved these changes

2025-01-03 17:33 UTC, closed without merging