Add New Self-Service Guide for Atlassian Statuspage Incident Management
port-labs/port-docs pull request #1289
Opened 2024-06-07 18:16 UTC by phalbert

# Description

A self-service guide to  [create and manage incidents](https://developer.statuspage.io/#operation/postPagesPageIdIncidents) on Atlassian Statuspage directly within the Port platform

## Added docs pages

- Create and Update a [Statuspage](https://www.atlassian.com/software/statuspage) Incident (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md`)

2024-06-09 15:56 UTC, MPTG94 requested changes
Address my comments and then ping me for another review

2024-06-09 15:56 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/blueprints/_statuspage_component_blueprint.mdx
Since we don't currently have a way to ingest components, let's remove this blueprint for now (it is ok to keep the file but not include it in the guide).

Let's also remove references to components in other blueprints and also in the self-service actions

2024-06-09 15:56 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +
Let's also add here a step which creates a new incident entity in Port, that we can trigger the update status self-service action on

2024-06-09 15:56 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +
Let's also add here a step which updates the status of the incident entity in Port and also any other details or inputs that were provided as part of the action. To make sure that the incident in Port reflects the status in Statuspage correctly

2024-06-10 12:33 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +
alright

2024-06-10 12:34 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +
alright

2024-06-10 13:50 UTC, phalbert commented
Closed this in favour of https://github.com/port-labs/port-docs/pull/1293 because of conflicts after merging changes from main that change the location of github actions

2024-06-10 13:50 UTC, closed without merging