PORT-8575 Add guide for managing statuspage incidents
port-labs/port-docs pull request #1293
Opened 2024-06-10 13:03 UTC by phalbert

# Description

A self-service guide to  [create and manage incidents](https://developer.statuspage.io/#operation/postPagesPageIdIncidents) on Atlassian Statuspage directly within the Port platform

## Added docs pages

- Create and Update a [Statuspage](https://www.atlassian.com/software/statuspage) Incident (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md`)

2024-06-16 09:35 UTC, MPTG94 requested changes
Please apply fixes according to my comments

2024-06-16 09:35 UTC, MPTG94 commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/blueprints/_statuspage_blueprint.mdx
Make sure the statuspage, statuspage component and statuspage incident blueprints are synchronized with what is provided by the statuspage Ocean integration

2024-06-16 09:35 UTC, MPTG94 commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/blueprints/_statuspage_component_blueprint.mdx
Make sure the statuspage, statuspage component and statuspage incident blueprints are synchronized with what is provided by the statuspage Ocean integration

2024-06-16 09:35 UTC, MPTG94 commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/blueprints/_statuspage_incident_blueprint.mdx
Make sure the statuspage, statuspage component and statuspage incident blueprints are synchronized with what is provided by the statuspage Ocean integration

2024-06-16 09:35 UTC, MPTG94 commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
add the `baseUrl` parameter in all places where you use the `uses: port-labs/port-github-action@v1`. Please also add the regional template block under the code blocks so that users know of the option to select a different region, see [here](https://docs.getport.io/guides-and-tutorials/setup-slack-reminders#setup-the-actions-backend) for an example

2024-06-16 09:35 UTC, MPTG94 commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
add the `baseUrl` parameter in all places where you use the `uses: port-labs/port-github-action@v1`. Please also add the regional template block under the code blocks so that users know of the option to select a different region, see [here](https://docs.getport.io/guides-and-tutorials/setup-slack-reminders#setup-the-actions-backend) for an example

2024-06-26 11:10 UTC, hadar-co requested changes

2024-06-26 11:10 UTC, hadar-co commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +1. Create the file `.github/workflows/create-statuspage-incident.yml` in the `.github/workflows` folder of your repository.
```suggestion
1. Create the file `create-statuspage-incident.yml` in the `.github/workflows` folder of your repository.
```

2024-06-26 11:10 UTC, hadar-co commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +2. Create the file `.github/workflows/update-statuspage-incident.yml` in the `.github/workflows` folder of your repository.
```suggestion
2. Create the file `update-statuspage-incident.yml` in the `.github/workflows` folder of your repository.
```

2024-06-26 11:10 UTC, hadar-co commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +:::tip Customize Your Workflow:
change this to be item number 3. Customize Your Workflow (instead of an admonition).
There are too many admonitions here in a row, it is confusing.

2024-06-26 11:10 UTC, hadar-co commented on docs/actions-and-automations/setup-backend/github-workflow/examples/Statuspage/manage-statuspage-incident.md
> +:::tip prerequisites
change the prerequisites to be a header (###) instead of an admonition.

2024-06-26 12:09 UTC, merged