Update sso docs
port-labs/port-docs pull request #1294
Opened 2024-06-10 13:30 UTC by OmriGez

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-06-12 16:42 UTC, MPTG94 requested changes
Apply changes based on my comments

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
Please also update the SAML folder to saml

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +2. Share with us the following information about your SSO application: X509 certificate (`.pem` or `.crt` file) and Signin URL (as defined in the application).
Did you end up testing with a `.crt` certificate to verify that it also works?

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +3. Port will provide you with a metadata XML file that you can upload in the SSO application to complete the connection.
```suggestion
3. Port will provide you with a metadata XML file that you can upload in the identity provider interface, to the SSO application to complete the connection.
```

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +    * User attribute mappings:
Change these `*` to `-`

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +    * User attribute mappings:
across the whole doc

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +    * User attribute mappings:
Add here in brackets what is the source and what is the target. For example - `given_name` is the target field the mapping will send to, `firstname` is the source field in the IdP that the value will be coming from

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +If your login provider does not support metadata files, extract the following data from the XML and manually add to your application:
This is not true, if they do not support XML upload, we will directly send them the correct values for the fields (or all they will have to do is input the `{CONNECTION_NAME}` parameter based on what we give them)

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +* SP EntityID = The EntityDescriptor field in the XML, looks like : `urn:auth0:port-prod:...` where the `...` is the connection name as provided to you by Port.
```suggestion
* SP EntityID = The EntityDescriptor field in the XML, looks like : `urn:auth0:port-prod:{CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/SAML.md
> +* callback URL = The AssertionConsumerService binding field in the XML, looks like : `https://auth.getport.io/login/callback?connection=...` where the `...` is the connection name as provided to you
```suggestion
* callback URL = The AssertionConsumerService binding field in the XML, looks like : `https://auth.getport.io/login/callback?connection={CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/google-workspace.md
>  ---
Update the `sidebar_position` field

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/jumpcloud.md
>  1. In the Admin Portal, go to User Authentication -> SSO.
Update the `sidebar_position` field

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/azure-ad.md
> +Send the PEM certificate file along with the application ID (Which can be found in the properties tab of the application) to Port.
Should this be step number 6? or was there something else that should have been there?

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/azure-ad.md
> +3. Select `Groups assigned to the application` and in the source attribute selectr `Cloud-only group display names`.
```suggestion
3. Select `Groups assigned to the application` and in the source attribute select `Cloud-only group display names`.
```

2024-06-12 16:42 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/SAML/azure-ad.md
> +4. Assign the relevant groups you want to expose to the application.
```suggestion
4. Assign the relevant groups you want to expose to the application, these will be ingested into Port as teams you can use to manage user permissions and RBAC in your Port account.
```

2024-06-24 08:43 UTC, OmriGez commented on docs/sso-rbac/sso-providers/SAML/azure-ad.md
> +Send the PEM certificate file along with the application ID (Which can be found in the properties tab of the application) to Port.
typo, fixed

2024-07-03 12:00 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +        - given_name : firstname
```suggestion
        - `given_name`: `firstname`
```

2024-07-03 12:00 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +        - family_name : lastname
```suggestion
        - `family_name`: `lastname`
```

2024-07-03 12:00 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +        - email_verified : true
```suggestion
        - `email_verified`: `true`
```

2024-07-03 12:01 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +* callback URL = The AssertionConsumerService binding field in the XML, looks like : `https://auth.getport.io/login/callback?connection={CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connect
```suggestion
* callback URL = The AssertionConsumerService binding field in the XML, looks like: `https://auth.getport.io/login/callback?connection={CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```

2024-07-03 12:03 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/jumpcloud.md
>  description: Integrate JumpCloud with Port
```suggestion
description: Integrate JumpCloud with Port using SAML
```

2024-07-03 12:03 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/google-workspace.md
>  description: Integrate Google Workspace with Port
```suggestion
description: Integrate Google Workspace with Port using SAML
```

2024-07-03 12:04 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +description: Integrate Azure AD with Port using SAML application
```suggestion
description: Integrate Azure AD with Port using SAML
```

2024-07-03 12:16 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +    - User attribute mappings:
```suggestion
    - User attribute mappings - `target attribute name (Port)`: `source attribute name (SSO app)`:
```

2024-07-03 12:24 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +3. Click on `Create your own application` and select "Integrate any other application you don't find in the gallery (Non-gallery)".
```suggestion
3. Click on `Create your own application` and select `Integrate any other application you don't find in the gallery (Non-gallery)`.
```

2024-07-03 12:24 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +4. In the getting started section, select the "Set up Single Sign On" button, and choose the SAML method.
```suggestion
4. In the getting started section, select the `Set up Single Sign On` button, and choose the SAML method.
```

2024-07-03 12:25 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +Send the PEM certificate file along with the application ID (Which can be found in the properties tab of the application) to Port.
```suggestion
Send the **PEM certificate file** along with the **application ID** (Which can be found in the properties tab of the application) to Port.
```

2024-07-03 12:26 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +At the top of the SAML configuration page, you can find a `upload metadata file` button. Press that one and upload the file provided to you by Port to complete the connection configuration.
```suggestion
At the top of the SAML configuration page, click on the `upload metadata file` button and upload the file provided to you by Port to complete the connection configuration.
```

2024-07-03 12:33 UTC, MPTG94 approved these changes
Final changes

2024-07-03 12:33 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +* IdP EntityID = `https://auth.getport.io`
```suggestion
- IdP EntityID: `https://auth.getport.io`
```

2024-07-03 12:33 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +* SP EntityID = The EntityDescriptor field in the XML, looks like : `urn:auth0:port-prod:{CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```suggestion
- SP EntityID: The EntityDescriptor field in the XML, looks like : `urn:auth0:port-prod:{CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```

2024-07-03 12:33 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/saml.md
> +* callback URL = The AssertionConsumerService binding field in the XML, looks like: `https://auth.getport.io/login/callback?connection={CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connecti
```suggestion
- callback URL: The AssertionConsumerService binding field in the XML, looks like: `https://auth.getport.io/login/callback?connection={CONNECTION_NAME}` where the `{CONNECTION_NAME}` is the connection name as provided to you by Port.
```

2024-07-03 13:44 UTC, MPTG94 approved these changes
Small update

2024-07-03 13:44 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/saml/azure-ad.md
> +title: "Azure-AD"
```suggestion
title: "Azure Active Directory (SAML)"
```

2024-07-03 13:47 UTC, merged