added some additional JSON schema features to the docs
port-labs/port-docs pull request #130
Opened 2022-12-19 13:06 UTC by amitb777

# Description

added some additional JSON schema features to the docs

## Updated docs pages

- Blueprint (`/software-catalog/blueprint`)

2022-12-20 09:41 UTC, MPTG94 requested changes
Please apply fixes according to comments

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +### Regular Expressions
There is already a dedicated explanation about regex in the [docs](https://docs.getport.io/software-catalog/blueprint/#string-regular-expression-patterns). Please combine the new explanation with the old one, under the new **additional keywords** header

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +
Add a small explanation that the rule above allows x to be 0<=x<100

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +List validation is useful for arrays of arbitrary length where each item matches the same schema. For this kind of array, set the items keyword to a single schema that will be used to validate all of
There is already a section called [Special property types](https://docs.getport.io/software-catalog/blueprint/#special-property-types) which explains [object arrays](https://docs.getport.io/software-catalog/blueprint/#objects-array), [url arrays](https://docs.getport.io/software-catalog/blueprint/#urls-array) and [enums](https://docs.getport.io/software-catalog/blueprint/#enum), let's take those explanation and put them here, and delete the special property types header

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +List validation is useful for arrays of arbitrary length where each item matches the same schema. For this kind of array, set the items keyword to a single schema that will be used to validate all of
There is already a section called [Special property types](https://docs.getport.io/software-catalog/blueprint/#special-property-types) which explains [object arrays](https://docs.getport.io/software-catalog/blueprint/#objects-array), [url arrays](https://docs.getport.io/software-catalog/blueprint/#urls-array) and [enums](https://docs.getport.io/software-catalog/blueprint/#enum), let's take those explanation and put them here, and delete the special property types header

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +The properties (key-value pairs) on an object are defined using the `properties` keyword. The value of `properties` is an object, where each key is the name of a property and each value is a schema u
```suggestion
It is possible to define the format and validation rules of key-value pairs inside an `object` property by using the `properties` key inside the `object` type definition.

The properties (key-value pairs) on an object are defined using the `properties` keyword. The value of `properties` is an object, where each key is the name of a property and each value is a schema used to validate that property. Any property that doesn’t match any of the property names in the `properties` keyword is ignored by this keyword.
```

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +When using the `properties` keyword, you can also make use of the `additionalProperties` keyword to control the handling of extra stuff, that is, properties whose names are not listed in the properti
```suggestion
When using the `properties` keyword, you can also make use of the `additionalProperties` keyword to control the handling of extra properties that were not explicitly defined. That is, properties whose names are not listed in the `properties` keyword of the `object` or match any of the regular expressions in the `patternProperties` keyword.

By default, any additional properties are allowed (`"additionalProperties": true`), by setting `additionalProperties` to `false`, only keys explicitly specified can be saved, and any other fields will be rejected (in the example below, only `config_file_path` and `min_required_cpu` will be allowed). 
```

2022-12-20 09:41 UTC, MPTG94 commented on docs/software-catalog/blueprint/blueprint.md
> +When using the `properties` keyword, you can also make use of the `additionalProperties` keyword to control the handling of extra stuff, that is, properties whose names are not listed in the properti
can you add an example where you use patternProperties here? It is written but not explained, so people will probably not know how to use it

2022-12-21 08:21 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +### Regular Expressions
done

2022-12-21 08:26 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +
done

2022-12-21 08:38 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +List validation is useful for arrays of arbitrary length where each item matches the same schema. For this kind of array, set the items keyword to a single schema that will be used to validate all of
done

2022-12-21 08:39 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +List validation is useful for arrays of arbitrary length where each item matches the same schema. For this kind of array, set the items keyword to a single schema that will be used to validate all of
done

2022-12-21 08:46 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +The properties (key-value pairs) on an object are defined using the `properties` keyword. The value of `properties` is an object, where each key is the name of a property and each value is a schema u
done

2022-12-21 08:53 UTC, amitb777 commented on docs/software-catalog/blueprint/blueprint.md
> +When using the `properties` keyword, you can also make use of the `additionalProperties` keyword to control the handling of extra stuff, that is, properties whose names are not listed in the properti
I removed the part with the patternProperties, it's pretty advanced and I don't think anyone is going to use it...

2022-12-21 10:28 UTC, MPTG94 approved these changes
LGTM, please apply the requested fixes and merge

2022-12-21 12:28 UTC, merged

2022-12-21 12:40 UTC, EllaFurman commented on docs/software-catalog/blueprint/blueprint.md
> +### Regular Expressions
Expressions should be with a lower case "e"

2022-12-21 12:40 UTC, EllaFurman commented on docs/software-catalog/blueprint/blueprint.md
> +It is possible to define the format and validation rules of key-value pairs inside an `object` property by using the `properties` keyword inside the `object` type definition.
it is = You can define...