PORT 8756 aws integration add use get resource api to docs
port-labs/port-docs pull request #1328
Opened 2024-06-19 11:38 UTC by shalev007

# Description

- **Add `useGetResourceAPI` option to the AWS Lambda function mapping in the `mapping_extra_resources.md`.**
- **feat: add helm installation**
- **feat: add installation warnings**

## Updated docs pages

- AWS Installation (/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation)
- Mapping extra resources (/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources)

2024-06-19 12:22 UTC, hadar-co requested changes

2024-06-19 12:22 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +## install using terraform
The first word in headers should be capitalized (see other headers as well)

2024-06-19 12:22 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +- By default the integration uses the [`CloudControl:ListResources`](https://docs.aws.amazon.com/cli/latest/reference/cloudcontrol/list-resources.html) API to get the resources. The integration can a
```suggestion
- By default the integration uses the [`CloudControl:ListResources`](https://docs.aws.amazon.com/cli/latest/reference/cloudcontrol/list-resources.html) API to get the resources. The integration can also enrich each resource by running [`CloudControl:GetResource`](https://docs.aws.amazon.com/cli/latest/reference/cloudcontrol/get-resource.html) on each resource, you can use this by enabling `useGetResourceAPI` option.  

```

2024-06-19 13:48 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +:::tip Get an example of the AWS resource properties
```suggestion
:::tip AWS resource properties example
```

2024-06-19 13:48 UTC, hadar-co approved these changes

2024-06-19 13:57 UTC, Tankilevitch requested changes

2024-06-19 13:57 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
should be under the tab of the real time events / terraform

2024-06-20 15:43 UTC, Tankilevitch requested changes

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +
Write about the PORT_CLIENT_ID and secret, and aws key id and secret and where to get it

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +--set integration.config.liveEventsApiKey="$YOUR_CUSTOM_API_KEY" \
remove

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +```
show full installation method

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +```
remove `\`

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +--set integration.config.awsSecretAccessKey="$AWS_SECRET_ACCESS_KEY" \
remove `\`

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +
missing information about how to create the user and get the access key and secret
and what roles to assign to it

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +
missing installation example for on-premise

2024-06-20 15:43 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +
also lets don't show the live key events parameter in the docker example

2024-06-20 15:44 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
> +
and lets describe what properties needs to be filled by the user in each of the installation methods

2024-06-20 15:44 UTC, Tankilevitch approved these changes

2024-06-20 16:19 UTC, merged