[PORT-8823] Added creating service account guide
port-labs/port-docs pull request #1339
Opened 2024-06-24 09:26 UTC by matan84

# Description

Added a guide that helps users create their own service account to the GCP integration

## Added docs pages

Please also include the path for the added docs

- Creating an Integration-Deditcated Service Account (`build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/creating-a-dedicated-service-account`)

2024-06-24 14:07 UTC, Tankilevitch requested changes

2024-06-24 14:07 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
<img width="1179" alt="Screenshot 2024-06-24 at 17 01 10" src="https://github.com/port-labs/port-docs/assets/59158507/85a7177c-8700-4fd8-b3f3-d8118cfa1d1e">


there is seem to be something wrong on the right side with repeating keys

2024-06-24 14:07 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
Also I feel like the default example of the screenshots is a bit overwhelming and I would prefer it to be somewhat collapsable and maybe as a reference of each installation instead of the first thing they see, wdyt?
<img width="959" alt="Screenshot 2024-06-24 at 17 03 13" src="https://github.com/port-labs/port-docs/assets/59158507/ee7d8a99-1d26-40c4-b65c-2b4ff51cff8a">

2024-06-24 14:07 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
> +}
same here lets default to polling

2024-06-24 14:07 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
> +
see that we started using image references in a bit of a different way - 
e.g.
`<img src='/img/scorecards/custom-scorecards-example.png' width='50%' border='1px' />
<br/><br/>`

you can adjust the width to align all screenshots to the same size, as well as adding a border :)

2024-06-24 14:08 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
> +<Tabs groupId="installation-platforms" queryString="installation-platforms">
lets have `helm` as the default one

2024-06-24 14:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
> +Choose one of the following installation methods:
I might add a few words on what we suggest to start with and what is the benefits of each :)

2024-06-24 14:11 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
> +
Oh really cool
Will check how this looks before moving all pictures to a specified place

2024-06-24 14:56 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
As for the right side menu, this happens also with aws, and i think itll happen for every document using the tab switcher and headings
As for pictures, check how they look now, if this is too overloaded ill change it

2024-06-25 06:21 UTC, Tankilevitch approved these changes

2024-06-25 06:23 UTC, merged