PORT-6978 | DORA Metrics Mini Guides
port-labs/port-docs pull request #1350
Opened 2024-06-28 08:10 UTC by mk-armah

# Description

Added a new guide (`/connect-dora-metrics-to-service`)

Updated DORA Metrics guide with team metrics
- Presents and update github blueprint. New properties include Response Time and Average Response Time and Time Frame.
- Computes response rate and response time for github teams
- Upserts metrics alongside port github blueprint properties

![image](https://github.com/port-labs/port-docs/assets/85971733/659ac82f-e260-41fb-b9b5-c5f1d815722a)

## Added docs pages

Please also include the path for the added docs

- Connect DORA Metrics to Service (`/`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- DORA Metrics (`/`)
- ...

2024-07-02 09:57 UTC, MPTG94 requested changes
Take a look at my comments

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +    - `GH_PAT_CLASSIC` - [GitHub Personal Access Token (Classic)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#personal-access-t
The learn more here does not link anywhere

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +          python dora/calculate_pr_metrics.py  --owner "${{ needs.setup.outputs.owner }}" --repo "${{ matrix.repository }}" --token "${{ secrets.GH_PAT_CLASSIC }}" --time-frame "${{ needs.setup.outpu
I don't see `calculate_pr_metrics.py` anywhere else in the doc, please verify the file names

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +You can choose to run any of the metric jobs (`compute-team-metrics` or `compute-repo-metrics`) optionally. This is controlled by setting or unsetting the corresponding Port blueprint parameters in y
This is unclear, after reading this tip, I still do not know how to correctly control what is computed, I think the table below needs to be expanded to explain it better. Or you can provide an additional example `dora-config.json` which shows some other formats

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +:::tip
```suggestion
:::tip Controlling configurations
```

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +```json showLineNumbers title="github team blueprint" {29,30,31,32,33,34,35,36,37,38,39,40,41}
Please use `// highlight-start` and `// highlight-end` as we do in other code blocks in the docs, and don't use the {1,2,3}

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/connect-dorametrics-to-service.md
> +- Install port [GitHub integration](/build-your-software-catalog/sync-data-to-catalog/git/github/installation)
```suggestion
- Install Port's [GitHub integration](/build-your-software-catalog/sync-data-to-catalog/git/github/installation) 

```

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/connect-dorametrics-to-service.md
> +        relations:
Add a highlight here to show that this is what changed

2024-07-02 09:57 UTC, MPTG94 commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/connect-dorametrics-to-service.md
> +Now, if our `DORA Metrics` identifier is equal to the repository id, the `metrics` will automatically be linked to it &nbsp;🎉
```suggestion
Now, if our `DORA Metrics` identifier is equal to the repository id, the `metrics` will automatically be linked to it 🎉

```

2024-07-10 05:02 UTC, mk-armah commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics/dora-metrics.md
> +          python dora/calculate_pr_metrics.py  --owner "${{ needs.setup.outputs.owner }}" --repo "${{ matrix.repository }}" --token "${{ secrets.GH_PAT_CLASSIC }}" --time-frame "${{ needs.setup.outpu
Line 397 -590

2024-10-07 17:27 UTC, closed without merging