Atlassian Statuspage Ocean Integration Docs
port-labs/port-docs pull request #1360
Opened 2024-07-02 08:47 UTC by phalbert

# Description

This PR adds comprehensive documentation for integrating Atlassian Statuspage with Ocean

## Added docs pages

Please also include the path for the added docs

- Statuspage (`/docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md`)
- Docker Parameters (`/docs/build-your-software-catalog/sync-data-to-catalog/incident-management/_statuspage_docker_parameters.mdx`)

2024-07-02 11:03 UTC, lordsarcastic requested changes
A few changes

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary> Incident Update response data</summary>
```suggestion
<summary><b>Incident Update response data (Click to expand)</b></summary>
```

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary> Page entity in Port</summary>
```suggestion
<summary><b>Page entity in Port (Click to expand)</b></summary>
```

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary>Component Group entity in Port</summary>
```suggestion
<summary><b>Component Group entity in Port(Click to expand)</b></summary>
```

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary> Component entity in Port</summary>
```suggestion
<summary><b>Component entity in Port (Click to expand)</b></summary>
```

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary> Incident entity in Port</summary>
```suggestion
<summary><b>Incident entity in Port (Click to respond)</b></summary>
```

2024-07-02 11:03 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +<summary> Incident Update entity in Port</summary>
```suggestion
<summary><b>Incident Update entity in Port (Click to expand)</b></summary>
```

2024-07-02 16:46 UTC, lordsarcastic approved these changes

2024-07-02 18:21 UTC, hadar-co requested changes

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +Our [Atlassian Statuspage](https://www.atlassian.com/software/statuspage) integration allows you to import `page`, `component_group`, `component`, `incident`, and `incident_update` resources from you
```suggestion
Port's [Atlassian Statuspage](https://www.atlassian.com/software/statuspage) integration allows you to import `page`, `component_group`, `component`, `incident`, and `incident_update` resources from your Statuspage instance into Port, according to your mapping and definitions.
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +
Refrain from using "our" in cases like these, when talking about something of Port's use "Port's".

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +1. Go to the DevPortal Builder page.
should be:
Go to the [Builder page](link to builder) of your portal.

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +2. Select the Data Sources tab at the left sidebar.
```suggestion
2. Select the `Data Sources` tab in the left sidebar.
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +3. Click on `+ Data Source` at the top right corner.
```suggestion
3. Click on `+ Data Source` in the top right corner.
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +4. Select Statuspage under the Incident Management category.
```suggestion
4. Select `Statuspage` under the `Incident Management` category.
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +5. Modify the [configuration](#configuration-structure) according to your needs.
```suggestion
5. Modify the [configuration](#configuration-structure) according to your data.
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +To ingest Statuspage objects using the [integration configuration](#configuration-structure), you can follow the steps below:
```suggestion
To ingest Statuspage objects using the [integration configuration](#configuration-structure), follow the steps below:
```

2024-07-02 18:21 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +7. Click `Next` and you can view the integration configuration and update it as necessary.
```suggestion
7. Click `Next`, you can view the integration configuration and update it as necessary.
```

2024-07-03 10:08 UTC, hadar-co approved these changes

2024-07-03 10:08 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
> +3. Click on `+ Data Source` button in the top right corner.
```suggestion
3. Click on the `+ Data Source` button in the top right corner.
```

2024-07-03 10:14 UTC, merged