[Snyk] - Connect Snyk image to target
port-labs/port-docs pull request #1363
Opened 2024-07-03 07:38 UTC by PeyGis

# Description

Deleted the previous guide that fills catalog images with snyk data to a new model that connects images to snyk target

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-07-03 09:39 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/guides/connect-images-to-snyk-target.md
> +Snyk API provides information about scanned images stored in container registries. This guide aims to assist users in populating their software catalog using data obtained from the Snyk API as well a
Snyk API provides information about scanned images stored in container registries. This guide demonstrates how to enrich your Port software catalog by importing image data from Snyk and establishing relationships between these images and their corresponding Snyk targets.

2024-07-04 10:41 UTC, hadar-co requested changes

2024-07-04 10:41 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/guides/connect-images-to-snyk-target.md
> +Snyk API provides information about scanned images stored in container registries. This guide demonstrates how to enrich your Port software catalog by importing image data from Snyk and establishing
```suggestion
Snyk's API provides information about scanned images stored in container registries. This guide demonstrates how to enrich your Port software catalog by importing image data from Snyk and establishing relationships between these images and their corresponding Snyk targets.
```

2024-07-04 10:41 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/guides/connect-images-to-snyk-target.md
> +# Connect images with Snyk target
```suggestion
# Connect images to Snyk targets
```

2024-07-04 10:41 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/guides/connect-service-to-target.md
> +<img src='/img/guides/githubServiceCreateRelation.png' width='60%' border="1px" />
the images here are very big, make them a bit smaller

2024-07-04 11:02 UTC, hadar-co approved these changes

2024-07-04 11:02 UTC, merged