Relation delete docs
port-labs/port-docs pull request #138
Opened 2022-12-26 18:00 UTC by yairsimantov20

# Description

Docs about how to remove the relation

## Added docs pages

- Quickstart (`/software-catalog/entity/tutorial#remove-relations`)

2022-12-27 11:00 UTC, MPTG94 requested changes
Fix comments and then ask for another review

2022-12-27 18:53 UTC, yairsimantov20 commented on docs/software-catalog/entity/tutorial.md
> +    "environment": null
Yeah
It will remove all relations

2022-12-27 18:59 UTC, yairsimantov20 commented on docs/software-catalog/entity/tutorial.md
> +#### PUT request
Added

2022-12-28 13:16 UTC, MPTG94 approved these changes
Fix the comments and ask Ella for a proof read in the #port-docs channel

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +If you set a relation that has a many: true setting to null, it will remove all the relations for that entity.
```suggestion
If a Blueprint has a Relation of type `"many": true`, by setting the specific Relation key to `null` on the Entity, the mapped related Entities will be removed.
```

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a relation from a `many` relation, for example: `environment`, send a PUT request with the following body:
```suggestion
To remove a mapped related Entity from a `"many": true` relation, for example: `environment`, send a POST request with the following body:
```

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +Make an **HTTP POST** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}?upsert=true`.
```suggestion
Make an **HTTP POST** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}?upsert=true`, for example:
```

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a specific relation, for example: `environment`, send a PUT request with the following body:
```suggestion
To remove a mapped related Entity from a `"many": false` relation, for example: `environment`, send a POST request with the following body:
```

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a relation from a `many` relation, for example: `environment`, send a PUT request with the following body:
Flip between these 2 examples such that many true is second

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a relation from a `many` relation, for example: `environment`, send a PUT request with the following body:
Update the text in these following examples to better match the updates to POST upsert

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a specific relation, for example: `environment`, send a PUT request with the following body:
Update the text in these following examples to better match the updates to POST upsert

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a relation from a `many` relation, for example: `environment`, send a PATCH request with the following body:
Update the text in these following examples to better match the updates to POST upsert

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +To remove a specific relation, for example: `environment`, send a PATCH request with the following body:
Update the text in these following examples to better match the updates to POST upsert

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +Make an **HTTP PUT** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}`.
```suggestion
Make an **HTTP PUT** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}`, for example:
```

2022-12-28 13:16 UTC, MPTG94 commented on docs/software-catalog/entity/tutorial.md
> +Make an **HTTP PATCH** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}`.
```suggestion
Make an **HTTP PATCH** request to the URL `https://api.getport.io/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}`, for example:
```

2022-12-29 16:00 UTC, EllaFurman requested changes

2022-12-29 16:00 UTC, EllaFurman commented on docs/software-catalog/entity/tutorial.md
> +To remove a mapped related Entity from a `"many": false` relation, for example: `environment`, send a PATCH request with the following body:
```suggestion
To remove a mapped related Entity from a `"many": false` relation (for example: `environment`), send a PATCH request with the following body:
```

2022-12-29 16:16 UTC, EllaFurman approved these changes

2022-12-29 16:16 UTC, merged