added a generic oidc sso page
port-labs/port-docs pull request #1393
Opened 2024-07-12 09:20 UTC by priyaraghu0412

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-07-15 11:18 UTC, MPTG94 requested changes
Please look at my comments

2024-07-15 11:18 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +
You don't need a blank line between bullets, it makes the page much more spaced than it needs to be, so please remove these blank linkes

2024-07-15 11:18 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +
Need to also add here a guidance step on cases where the email verified field needs to be provided (it doesn't happen in OIDC Okta, but if you look at the OIDC OneLogin docs, you will see it is explained there)

2024-07-16 10:25 UTC, priyaraghu0412 commented
@MPTG94 I addressed all the comments. Please review.

2024-07-16 11:52 UTC, MPTG94 requested changes
Take a look at my additional comments

2024-07-16 11:52 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +
Add an additional line break here (you can see how using a `<br>` block in other doc pages)

2024-07-16 11:52 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +	 - `email_verified`: This custom field must be transmitted to Port during user login, specifically required for certain Identity Providers such as Onelogin.
What I meant is add an additional numbered bullet (such as 3,4,5,6) that will explain that the `email_verified` field from the identity provider might be required in some cases, and that in those cases you will need to make sure that field is sent with the value `true` by your identity provider as part of the connection.

And you should also link to the example in the OneLogin docs, because that is an actual example showing that

2024-07-17 06:10 UTC, priyaraghu0412 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +
@MPTG94 Done. I had to add 2 <br></br> to get the correct line spacing.

2024-07-17 06:11 UTC, priyaraghu0412 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +	 - `email_verified`: This custom field must be transmitted to Port during user login, specifically required for certain Identity Providers such as Onelogin.
@MPTG94 I added the extra step. Please review.

2024-07-17 06:52 UTC, MPTG94 requested changes
One final change

2024-07-17 06:52 UTC, MPTG94 commented on docs/sso-rbac/sso-providers/oidc/oidc.md
> +5. Add a custom property `email_verified` and configure the OpenID Claims in your identity provider to ensure that Port receives the value `true` for this attribute as part of the connection process.
```suggestion
5. Add a custom property `email_verified` and configure the OpenID Claims in your identity provider to ensure that Port receives the value `true` for this attribute as part of the connection process. This step may be required specifically for certain identity providers such as [OneLogin](/sso-rbac/sso-providers/oidc/onelogin.md#step-4-add-email_verified-custom-property-to-all-users).
```

2024-07-17 07:13 UTC, MPTG94 approved these changes
LGTM

2024-07-17 07:27 UTC, merged