Create guide explaining how to connect OpenCost with AWS and Argo CD K8 resource
port-labs/port-docs pull request #1397
Opened 2024-07-12 18:28 UTC by lordsarcastic

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-07-15 15:40 UTC, phalbert reviewed
There are also some conflicts in the files

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/_category_.json
> +}
new line missing

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +# Connect Opencost `cloudcost` with AWS Resource
Connect OpenCost Cloud Costs to AWS Resources in Port

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +This guide aims to cover how to connect an Opencost Resource Allocations resource with an ArgoCD K8 resource to draw cost analysis.
This guide demonstrates how to link OpenCost cloud cost data with your AWS resources within Port, enabling you to gain insights into the cost breakdown of your infrastructure and applications.

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +
Add a use cases admonition to give a quick idea of how useful this would be

:::tip Use Case Examples:

Cost Attribution: Determine which AWS resources (EC2 instances, RDS databases, etc.) contribute the most to your overall cloud costs.
Budget Management: Track the costs of individual resources or groups of resources against your budget allocations.
Anomaly Detection: Identify unusual spikes in resource costs and investigate potential causes.
Optimization Opportunities: Pinpoint resources that are underutilized or overprovisioned, potentially leading to cost savings
:::

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +:::tip Prerequisites
if the usecases admonition is added, then this should be a section rather than an admonition i.e

## Prerequisites

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +- Click the + Blueprint button at the top right corner.
Click the `+ Blueprint` button at the top right corner

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +- Click the Edit JSON button.
Click the `Edit JSON` button.

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +- Navigate to your Port organization's data model page on the builder.
Add a link to the data model page

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/_category_.json
> +}
new line missing

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +This guide aims to cover how to connect an Opencost Cloudcost resource with an AWS resource to draw cost analysis.
This guide will show you how to connect a Kubecost cloudcost resource with an AWS resource in Port to analyze your cloud cost allocation.

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +:::tip Prerequisites
I would change Prerequisites to a section and add a usecases admonition

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +# Connect Kubecost `cloudcost` with AWS Resource
Is it Kubecost or Opencost?

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +- Navigate to your Port organization's data model page on the builder.
Add the link to the data model page

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +- Click the + Blueprint button at the top right corner.
Click the `+ Blueprint` button at the top right corner.

2024-07-15 15:40 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost/guides/connect-opencost-resource-with-aws-resource.md
> +- Click the Edit JSON button.
Click the `Edit JSON` button.

2024-07-30 07:32 UTC, matan84 requested changes
Requested some changes. Please also add in the end of the guide a final view of the builder + specfic entity page view after you have created the blueprints + mappings

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +Cost Attribution: Determine which Kubernetes resource contribute the most to your overall cloud costs.
The tip is redundant here, you can just add _Use case examples_ as a heading

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +- Ensure you have [Port's Opencost integration installed and configured in your environment](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost).
Duplicate

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +- Two (2) new blueprints created by the Opencost integration, "Opencost Resource Allocations" and `Opencost Cloudcost`
IMO You shouldn't specify directly the names of the blueprints, because that changes frequently, You can just say that some bluprints are auto-generated as part of the integration's onboarding

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +If the blueprints aren't created:
Redundant part IMO, you can remove this

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +1. Head back to the [Builder](https://app.getport.io/settings/data-model), choose the `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip>, and click on `New relation`:
When did I create the Pull request blueprint through this guide?

2024-07-30 07:32 UTC, matan84 commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/guides/connect-opencost-resource-with-argocd-k8s-resources.md
> +Now that the <PortTooltip id="blueprint">blueprints</PortTooltip> are related, we need to assign the relevant ArgoCD K8 resource to each of our Opencost Resource Allocation. This can be done by addin
```suggestion
Now that the <PortTooltip id="blueprint">blueprints</PortTooltip> are related, we need to assign the relevant ArgoCD Kubernetes resource to each of our Opencost Resource Allocation. This can be done by adding some mapping logic. Go to your [data sources page](https://app.getport.io/settings/data-sources), and click on your ArgoCD integration
```

2024-08-11 12:33 UTC, matan84 approved these changes
LGTM

2025-05-07 08:00 UTC, closed without merging