Gitlab ci integration guide
port-labs/port-docs pull request #1422
Opened 2024-07-24 10:45 UTC by kodjomiles

# Description

This PR includes the implementation of a self-service action to trigger incidents in PagerDuty using GitLab CI. The work involved extensive research on PagerDuty integration and implementing the documentation guide.

### Added docs pages
Please also include the path for the added docs:

- Trigger PagerDuty Incident (`/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab`)

## Updated docs pages

Please also include the path for the updated docs:

- PagerDuty Integration Guide (`/docs/integrations/pagerduty`)

2024-07-24 11:13 UTC, mk-armah commented
change the path from ~~github-workflow~~ to gitlab-ci

2024-07-24 11:29 UTC, PeyGis requested changes
Please go over my comments

2024-07-24 11:29 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab.md
> +2. In your GitLab repository, [go to **Settings > CI/CD**](https://docs.gitlab.com/ee/ci/variables/#define-a-cicd-variable-in-the-ui) define a CI/CD variable in the UI and add the following secrets:
```suggestion
2. In your GitLab repository, [go to **Settings > CI/CD**](https://docs.gitlab.com/ee/ci/variables/#define-a-cicd-variable-in-the-ui) and add the following secrets:
```

2024-07-24 11:29 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab.md
> +4. In Case you decided not to install the PagerDuty integration, you will need to create a blueprint for PagerDuty incidents in Port.
```suggestion
4. In case you decided not to install the PagerDuty integration, you will need to create a blueprint for PagerDuty incidents in Port.
```

2024-07-24 11:29 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab.md
> +Create a directory structure `scripts/` and a `trigger_pagerduty_incident.sh` script to handle the API calls:
Move the script inside the Gitlab CI pipeline itself. We don't want the user to create files as this could be challenging. We want everything to be encapsulated into a single workflow/pipeline

2024-07-24 11:29 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab.md
> +1. Navigate tp [GitLab CI/CD Settings > **CI/CD** ](https://docs.gitlab.com/ee/ci/variables/) `Variables`.
```suggestion
1. Navigate t0 [GitLab CI/CD Settings > **CI/CD** ](https://docs.gitlab.com/ee/ci/variables/) `Variables`.
```

2024-07-24 11:29 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/PagerDuty/trigger-pagerduty-incident-gitlab.md
> +
Why don't you add this configure environment variables to the prerequisite section when you mentioned how to add CI variables/secrets?

2024-07-26 10:23 UTC, kodjomiles reviewed
Please go over my changes

2024-07-30 07:12 UTC, matan84 requested changes
The guide itself looks very clean
Please add screenshots

2024-07-30 09:10 UTC, kodjomiles commented
got it

On Tue, Jul 30, 2024 at 7:12 AM Matan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The guide itself looks very clean
> Please add screenshots
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/port-labs/port-docs/pull/1422#pullrequestreview-2206837042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU43J4X34FAHHMXPDUUIEPTZO44HFAVCNFSM6AAAAABLMG3EWKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBWHAZTOMBUGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-13 17:07 UTC, PeyGis requested changes
some few more comments

2024-08-14 04:58 UTC, kodjomiles commented on docs/actions-and-automations/setup-backend/gitlab-pipeline/examples/PagerDuty/trigger-pagerduty-incident.md
> +   <img src='/img/self-service-actions/setup-backend/gitlab-pipeline/addingBlueprint.png' width='85%' border="1px" />
the image or the whole point ?

2024-08-14 05:24 UTC, kodjomiles commented
I have moved the pr from my forked repo to upstream

2024-08-14 05:24 UTC, closed without merging