[PORT-8794] Create 10-20 examples of the most common aws resources
port-labs/port-docs pull request #1423
Opened 2024-07-24 14:15 UTC by oiadebayo

# Description

This pull request adds mappings for 16 new AWS resources into Port's AWS integration. The following resources have been integrated:

- Amazon EC2 (Elastic Compute Cloud)
- Amazon RDS (Relational Database Services)
- Amazon S3 (Simple Storage Service)
- AWS ECS Cluster
- AWS Lambda
- Amazon VPC (Virtual Private Cloud)
- Amazon Kinesis
- Amazon SNS (Simple Notification Service)
- Amazon Cognito
- Amazon Lightsail
- Amazon IAM (Identity and Access Management)
- DynamoDB
- Amazon SQS (Simple Queue Service)
- Amazon ElastiCache
- AWS CloudFormation
- AWS Amplify
- Web Application Firewall (WAF)
- Amazon Lex
- AWS QuickSight
- Amazon CloudFront
- AWS Elastic Beanstalk
- AWS Auto Scaling

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-07-24 16:54 UTC, phalbert requested changes
Are you positive all these resources need the `useGetResourceAPI` since [it makes the resync slower](https://pr-1423.d2ngvl90zqbob8.amplifyapp.com/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources#usegetresourceapi-property)?

2024-07-24 16:56 UTC, phalbert reviewed
Add the link to the page being updated in the description

2024-07-26 11:46 UTC, phalbert requested changes
Great work so far! The titles are too many. I would say that we should make the page less noisy by having titles for the groups only e.g.

### Compute Resources 

...blueprints...
...integration config...

### Developer Tools

...blueprints...
...integration config...

### Applications

...blueprints...
...integration config...

2024-07-26 11:46 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +### Application Integration Integration Configuration Example
I think this was duplicated: `Integration Integration`

2024-07-26 11:50 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Shouldn't this statement have the word _not_?

As you've probably looked at the [Examples](./examples.md) page, you've noticed that the AWS Integration supports some AWS resources, but most of them are **not** documented in the Examples page.

2024-07-26 12:03 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
This section can be made better

## Is the AWS Resource Supported by the Integration?

The AWS Integration relies on [AWS's Cloud Control API](https://aws.amazon.com/cloudcontrolapi/). This means:

1. **Check the AWS docs**: Is the type of resource you want to ingest listed [here](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html)?
      - **If Yes**: Great! It's supported.
      - **If Not**: Please contact us or contribute by [adding support](https://ocean.getport.io/develop-an-integration/) to the [integration](https://github.com/port-labs/ocean/tree/main/integrations/aws) yourself.

2024-07-26 12:21 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +### Application Integration Integration Configuration Example
This has been fixed and the titles reduced too

2024-07-26 16:48 UTC, noaiz requested changes

2024-07-26 16:48 UTC, noaiz commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Yes and Not shouldn't be capitalized (they're words in the middle of a sentence), and maybe I would even write "If so" instead of "if yes".

2024-07-26 16:48 UTC, noaiz commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
>  After you've found the resource in the [AWS CloudControlAPI Docs](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html), you can map it to Port by following these ste
```suggestion
After you've found the resource in the [AWS Cloud Control API Docs](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html), you can map it to Port by following these steps:
```

2024-07-26 16:48 UTC, noaiz commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
- [ ] Please edit all smaller headings under this heading to have only the first word capitalized, as per [our convention](https://github.com/port-labs/port-docs/blob/main/CONTRIBUTING.md#:~:text=Subtitles%20(H2%2D4)%20%2D%20capital%20letters%20only%20for%20the%20first%20word%20of%20the%20subtitle.%20The%20rest%20of%20the%20sentence%20will%20be%20in%20lowercase%20letters.%20For%20example%3A%20%22Our%20building%2Dspace%22.).

2024-07-26 16:48 UTC, noaiz commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +## Integration Configuration Basics and the Use of `useGetResourceAPI`
This should be in Sentence case ([docs convention](https://github.com/port-labs/port-docs/blob/main/CONTRIBUTING.md#:~:text=Subtitles%20(H2%2D4)%20%2D%20capital%20letters%20only%20for%20the%20first%20word%20of%20the%20subtitle.%20The%20rest%20of%20the%20sentence%20will%20be%20in%20lowercase%20letters.%20For%20example%3A%20%22Our%20building%2Dspace%22.)).
```suggestion
## Integration configuration basics and the use of `useGetResourceAPI`
```

2024-07-26 17:11 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Done, thank you for the insight

2024-07-26 17:13 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Corrected, thank you

2024-07-26 17:13 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +## Integration Configuration Basics and the Use of `useGetResourceAPI`
This has also been corrected

2024-09-08 11:32 UTC, shalev007 commented
Hey is the Blueprint a new page? because I can't see it on https://pr-1423.d2ngvl90zqbob8.amplifyapp.com/platform-
overview/port-components/blueprint

2024-09-09 09:51 UTC, shalev007 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/compute_resources/_port_app_config.mdx
> +                '#/application/overview?applicationName=' + .Properties.ApplicationName
I think this is a mistake
```suggestion
                '/application/overview?applicationName=' + .Properties.ApplicationName
```

2024-09-09 10:06 UTC, shalev007 commented
Overall looks good to me, I trust that you tested all of these resources, if not please do
👍

2024-09-09 10:06 UTC, shalev007 approved these changes

2024-09-17 16:57 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
The wording here still needs a small fix and adding a link to the API

_The AWS Integration is **relying** on AWS's Cloud Control API. That means:_

should be:
_The AWS Integration relies on [AWS's Cloud Control API](https://aws.amazon.com/cloudcontrolapi/). This means:_

2024-09-17 17:02 UTC, phalbert commented
@oiadebayo  I think this would also benefit from the new integration spec by removing the configuration section and just linking to it like in the Jira docs; where they have JQL support, we put `useGetResourceAPI` API
<img width="1355" alt="Screenshot 2024-09-17 at 18 01 13" src="https://github.com/user-attachments/assets/85b8f4e6-639b-492a-975f-99b4a86fd547">

2024-09-27 12:15 UTC, phalbert approved these changes
LGTM

2024-10-11 17:14 UTC, noaiz commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
> +### Developer tools  blueprint and configuration example
```suggestion
### Developer tools blueprint and configuration example
```

2024-10-11 17:15 UTC, noaiz approved these changes
Made [a small suggestion](https://github.com/port-labs/port-docs/pull/1423/files#r1797232282) for redundant space, otherwise looks good.

2024-10-11 17:32 UTC, merged