PORT-8538 Add general security page to Port's docs
port-labs/port-docs pull request #1424
Opened 2024-07-24 16:46 UTC by MPTG94

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-07-25 06:41 UTC, MatanHeledPort commented on docs/security/security.md
> +Security and compliance are always our top priority at Port. We're building a product that's meant to be the daily hub for all of your developers, when fully integrated in an organization, Port becom
```suggestion
Security and compliance are always our top priority at Port. We're building a product that's meant to be the daily hub for all of your developers. When fully integrated in an organization, Port becomes a main junction for the developers' daily routines, as well as a centerpiece for analytics, metrics, self-service and automation flows. This can only be achieved if we have your trust and confidence that we will treat your data with respect and security in mind.
```

2024-07-25 07:29 UTC, MatanHeledPort requested changes
Check out my recommendations

2024-07-25 07:29 UTC, MatanHeledPort commented on docs/security/security.md
> +All data in Port servers is encrypted at rest, data at rest is encrypted using AES-256bit encryption. AWS stores and manages data cryptography keys in its redundant and globally distributed Key Manag
```suggestion
All data in Port servers is encrypted at rest using AES-256bit encryption. AWS stores and manages data cryptography keys in its redundant and globally distributed Key Management Service ([AWS KMS](https://aws.amazon.com/kms/)). So, if an intruder were ever able to access any of the physical storage devices, the Port data contained there would still be impossible to decrypt without the keys, rendering the information a useless jumble of random characters.
```

2024-07-25 07:29 UTC, MatanHeledPort commented on docs/security/security.md
> +All data in Port servers is encrypted at rest, data at rest is encrypted using AES-256bit encryption. AWS stores and manages data cryptography keys in its redundant and globally distributed Key Manag
`rendering the information a useless jumble of random characters.` Is this necessary?  :D

2024-07-25 07:29 UTC, MatanHeledPort commented on docs/security/security.md
> +Port will never make an outbound request to your infrastructure or environment in order to pull information, data is always sent to Port using push methods.
```suggestion
Port will never make an outbound request to your infrastructure or environment in order to pull information.
```

2024-07-25 07:29 UTC, MatanHeledPort commented on docs/security/security.md
> +Aside from those, Port also supports other backends such as webhooks which make it possible for Port to directly make a request to your environment and trigger your backend, should you choose to use
I would add a short sentence regarding our custom headers which can be validated by the customer

2024-07-25 12:17 UTC, jonathan-gruber-1 commented
looks great 
- let's start with compliance first? 
- Business Continuity and Disaster Recovery >> usually the expectation is to explain that we have a Business Continuity and Disaster Recovery Program in place, could we add this?
- Business continuity & Disaster recovery could also be added here: https://pr-1424.d2ngvl90zqbob8.amplifyapp.com/security/#security-policies

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Organizations that are more security concerned, limited by compliance requirements or internal policy you have the option to listen to action triggers by listening to messages coming in from a Kafka
```suggestion
Organizations that are more security concerned, limited by compliance requirements or internal policy - you have the option to listen to action triggers by listening to messages coming in from a Kafka topic provided to you by Port, or you can use Port's agent, which is hosted on your premise and listens to the topic on your behalf in order to forward it to the correct destination internally. These two solutions make it possible to receive action triggers without opening any inbound network connectivity to your infrastructure.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Port provides native applications for GitHub and Bitbucket which seamlessly integrate with the Git providers to ingest information and keep an up to date catalog available in Port. These integrations
```suggestion
Port provides native applications for GitHub and Bitbucket which seamlessly integrate with the Git providers to ingest information and keep an up-to-date catalog available in Port. These integrations use OAuth 2.0 for authentication and permissions to your Git provider.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +As part of the installation Port's Git provider apps, the apps gain a limited set of permissions ([GitHub](/docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md#permissions), [B
```suggestion
As part of the installation of Port's Git provider apps, the apps gain a limited set of permissions ([GitHub](/docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md#permissions), [Bitbucket](/docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket.md#permissions)). In addition, it is possible to selectively authorize access to a limited set of repositories.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +By default the Git integrations will not ingest any source code, and will only search for `README.md` files specifically. It is possible to configure the apps to not ingest any source code files at a
```suggestion
By default the Git integrations will not ingest any source code, and will only search for `README.md` files specifically. It is possible to configure the apps to not ingest any source code files at all, or to ingest additional files that are relevant to your use case.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Port provides a variety of open source integration for different use cases, such as the K8s exporter and Port agent. These integrations are completely open source and you have the option to view the
```suggestion
Port provides a variety of open source integration for different use cases, such as the K8s exporter and Port agent. These integrations are completely open source and you have the option to view the source code on GitHub. In addition, these integrations are fully customizable and are deployed on your premise, so they do not require opening inbound network connectivity to your infrastructure or providing any secrets or credentials to Port.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +For some third party services, a "Hosted by Port" integration option is available. In this deployment type, the integration is hosted and managed on Port's infrastructure, removing the need to person
```suggestion
For some third-party services, a "Hosted by Port" integration option is available. In this deployment type, the integration is hosted and managed on Port's infrastructure, removing the need to personally host, manage and maintain the integration on your premise.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +While this deployment method does require providing an access token to the relevant third party service in order for the integration to work, it still provides the same level of security and customiz
```suggestion
While this deployment method does require providing an access token to the relevant third-party service in order for the integration to work, it still provides the same level of security and customizability that all Ocean integrations provide.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +When an integration is hosted by Port, it is deployed on Port's infrastructure and makes calls to the third party service, receives the results, processes the data according to the integration config
```suggestion
When an integration is hosted by Port, it is deployed on Port's infrastructure and makes calls to the third-party service, receives the results, processes the data according to the integration configuration, and then sends the processed results to Port. While this does mean data is processed outside of your premise, there is still complete separation between the integration and Port itself, meaning an additional layer of protection that prevents completely unprocessed data from making its way to your Port account.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Sentry’s organization list also displays who has MFA enabled so users can vet their own organization’s security.
```suggestion
Port’s organization list also displays who has MFA enabled so users can vet their own organization’s security.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Port integrates with all major [SSO providers](/docs/sso-rbac/sso-rbac.md), allowing you to seamlessly import users, and teams, and also exposing Port to your organization in a managed manner.
```suggestion
Port integrates with all major [SSO providers](/docs/sso-rbac/sso-rbac.md), allowing you to seamlessly import users and teams, and also exposing Port to your organization in a managed manner.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Port practices continuous delivery, which means all code changes are committed, tested, shipped, and iterated on in a rapid sequence. A continuous delivery methodology, complemented by pull request,
```suggestion
Port practices continuous delivery, which means all code changes are committed, tested, shipped, and iterated on in a rapid sequence. A continuous delivery methodology, complemented by pull request, continuous integration (CI), and automated error tracking, significantly decreases the likelihood of a security issue and improves the response time and the effective eradication of bugs and vulnerabilities. Release notes and details for Port releases can be found in the [changelog](https://roadmap.getport.io/changelog).
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Any and all secrets shared with Port are encrypted both at rest and in transit, once they are saved into the system, their value cannot be retrieved directly, it will only be used and referenced as s
```suggestion
Any and all secrets shared with Port are encrypted both at rest and in transit, Once they are saved into the system, their value cannot be retrieved directly, it will only be used and referenced as specified by the user. A customer's secrets are completely isolated from another's at both the data storage layer and the access permissions layer.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +Port notifies customers of any data breaches as soon as possible via email and the primary contact channel, followed by multiple periodic updates throughout each day addressing progress and impact. P
```suggestion
Port will notify customers of any data breaches as soon as possible via email and the primary contact channel, followed by multiple periodic updates throughout each day addressing progress and impact. Port Enterprise plans include a dedicated customer success manager who holds responsibility for customer communication, as well as regular check-ins and escalations.
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +You can find Port's privacy policy [here](https://www.getport.io/legal/privacy-policy)
```suggestion
You can find Port's privacy policy [here](https://www.getport.io/legal/privacy-policy).
```

2024-07-25 12:31 UTC, noaiz commented on docs/security/security.md
> +You can find Port's DPA [here](https://www.getport.io/legal/dpa)
```suggestion
You can find Port's DPA [here](https://www.getport.io/legal/dpa).
```

2024-07-29 14:04 UTC, hadar-co commented on docs/security/security.md
> +Port is an internal developer portal platform and as such we place the utmost importance on data security, privacy and compliance, so that you can trust that your compliance, privacy and security nee
```suggestion
Port is an internal developer portal platform and as such we place the utmost importance on data security, privacy and compliance, so that you can trust that your security needs are met.
```

2024-07-29 14:04 UTC, hadar-co commented on docs/security/security.md
> +The goal of this document is to provide you with transparency as to security policies and practices at Port.
```suggestion
The goal of this document is to provide you with transparency as to Port's security policies and practices. 
```

2024-07-29 14:09 UTC, hadar-co commented on docs/security/security.md
> +This document will outline the different measures, protocols, processes and methods we take to ensure that your data stays secure and highly available.
```suggestion
This document will outline the different measures, protocols, processes and methods we use to ensure that your data stays secure and highly available.
```

2024-07-29 14:38 UTC, hadar-co approved these changes

2024-07-29 14:44 UTC, merged