Add bigquery resources to gcp
port-labs/port-docs pull request #1441
Opened 2024-07-30 20:34 UTC by PeyGis

# Description

Added blueprint and mapping resources for GCP BigQuery

## Added docs pages

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/bigquery_resources/_dataset_blueprint.mdx
docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/bigquery_resources/_model_blueprint.mdx
docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/bigquery_resources/_port_app_config.mdx
 docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/bigquery_resources/_table_blueprint.mdx

## Updated docs pages

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md

2024-08-04 12:26 UTC, Tankilevitch requested changes

2024-08-04 12:26 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +<ModelBlueprint/>
lets separate between compute and bigquery which is more of a `data management` section

2024-08-15 16:15 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +<BigQueryConfig/>
this should be separate, mapping per section, so the user won't get lost

2024-09-25 08:09 UTC, hadar-co approved these changes

2024-09-25 08:29 UTC, merged