PORT-9395 | Update sonarqube guide to use search relation
port-labs/port-docs pull request #1442
Opened 2024-07-31 05:16 UTC by kodjomiles

# Description

This PR updates the SonarQube analysis to use the new search relation feature.
## Added docs pages

## Updated docs pages

Please also include the path for the updated docs
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis

2024-07-31 08:57 UTC, PeyGis requested changes
Please go over my comments and let me know when you're done

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +There are two ways to establish the relationship between `pull-request` kind and the `sonarqube-analysis` kind:
```suggestion
There are two ways to establish the relationship between a GitHub `pull-request` entity and a SonarQube `analysis` entity:
```

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +<img src='/img/guides/pullReqSonarQubeRelationship.png' width='70%' border='1px' />
It is not clear what you're trying to convey with this image. Maybe we don't need it?
![image](https://github.com/user-attachments/assets/c4acf4cf-f6e0-414b-ae90-90697ce7dc74)

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +      <img src='/img/githubExporter.png' width='100%' border='1px' />
This image is not rendering properly
<img width="892" alt="Screenshot 2024-07-31 at 8 44 01 AM" src="https://github.com/user-attachments/assets/6a9ce710-52bf-4a3e-ba1c-ddbc0947ca5c">

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +1. **Option 1** - using the `title` and `branch` **property** to perform a search query[ rule](/search-and-query/#rules) to map relations based on the **property** of the related entity:
Instead of organizing this as a list, I want it to be a sub header
### Matching common pull request title and branch


### Matching pull request commit sha

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +1. **Option 1** - using the `title` and `branch` **property** to perform a search query[ rule](/search-and-query/#rules) to map relations based on the **property** of the related entity:
Also, there is not much information on the why. You are talking about the how. Users need to understand why we are using the title and branch.

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +     ```
instead of just showing a truncated config mapping, provide the full mapping for the pull-request kind including the search rules. Then ask them to update their pull-request kind with this new one

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +2. **Option 2** - modify the `sonarQube Analysis` <PortTooltip id="blueprint">blueprints</PortTooltip> to add a `commitSha` **property**:
Use the sub header I mentioned above instead of a list. and add a line text explaining what and why we are using the commit sha

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
>  ```
Provide the full config mapping

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +           - property: '"$branch"'
$branch will not work. just use '"branch"' since it is not a meta property. [See examples of meta properties](https://docs.getport.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/meta-properties). These are the only one you can use the $ to access them

2024-07-31 08:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +           - property: '"$commitSha"'
```suggestion
           - property: '"commitSha"'
```

2024-07-31 12:23 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +There are two ways to establish the relationship between `pull-request` kind and the `sonarqube-analysis` kind:
done

2024-08-06 13:07 UTC, hadar-co requested changes

2024-08-06 13:07 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +- Go to the `SonarQube` <PortTooltip id="blueprint">blueprints</PortTooltip>.
```suggestion
- Go to the `SonarQube` <PortTooltip id="blueprint">blueprint</PortTooltip>.
```

2024-08-06 13:07 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +- Hover over it, click on the `...` button on the right, and select `Edit`.
We need to be clearer in the instructions here. If we want to instruct the user to edit the JSON, there is no need to click edit, and then edit JSON. The guide should instruct to click on the `...` and click edit JSON. This will save the user unnecessary steps.
Also, it's unclear from the instructions if the user needs to add the mapping or replace the existing mapping. Please clarify.

2024-08-06 13:07 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +to map relationships between `githubPullRequest` entities and `sonarAnalysis` entities based on specific **properties** rather than direct identifiers.
```suggestion
to map relationships between `githubPullRequest` entities and `sonarAnalysis` entities based on specific **properties** rather than direct identifiers.  
```

2024-08-06 13:07 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +By using **properties** like `title`, `branch`, and `commitSha`, we are able to establish a between the two entities.
```suggestion
By using **properties** like `title`, `branch`, and `commitSha`, we are able to establish a between the two entities.  
```

2024-08-06 16:46 UTC, jadenmyles commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +# Relation Mapping
got it !

2024-08-06 17:26 UTC, kodjomiles commented
requesting PR be closed since PR has been moved to the main repository.

2024-08-06 17:26 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +- Hover over it, click on the `...` button on the right, and select `Edit`.
Done

2024-08-06 17:28 UTC, closed without merging