PORT-9458 | Create automation that sends a Slack message for prs more than 3 days
port-labs/port-docs pull request #1447
Opened 2024-08-01 17:55 UTC by kodjomiles

# Description

- Added a new example for sending Slack notifications when a PR is open for more than 3 days. Webhook Guide.
- Added the complete automation definition JSON for the Slack notification.

## Updated docs pages

Please also include the path for the updated docs
https://docs.getport.io/actions-and-automations/define-automations/examples

2024-08-13 16:37 UTC, PeyGis requested changes
some changes needed. but overall looks good

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +- Port installed on GitHub.
```suggestion
- Install Port's GitHub app by clicking [here](https://github.com/apps/getport-io/installations/new).
- Configure a [Slack app](https://api.slack.com/apps) that can post a message to a Slack channel. The app should have a `chat:write` bot scope under OAuth & Permissions.
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +
I'll prefer you add a one sentence overview section describing the purpose of this automation, before the prerequisite

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +2. **Check if `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> exists:**
```suggestion
2. **Create the `Pull Request` blueprint (if it doesn't exist):**
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +    - If the `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> does not exist, create it with the schema provided below.
```suggestion
Go to your [Builder](https://app.getport.io/settings/data-model) page and create the `Pull Request` blueprint using the schema provided below
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +3. **Add `openDuration` **property** to `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> (if it already exists):**
```suggestion
3. **Add an `openDuration` property to the `Pull Request` blueprint (if it already exists):**
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +    - Navigate to the `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> in your Port Builder.
```suggestion
    - Navigate to the `Pull Request` blueprint in your Port Builder.
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +    - Go to [Slack API: Applications](https://api.slack.com/apps).
```suggestion
    - Go to [Slack API](https://api.slack.com/apps).
```

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +
I don't think we should spent much time showing users how to generate a Slack webhook URL. Let's just give them a [reference link from Slack](https://api.slack.com/messaging/webhooks) on how to create one

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
>  ## Update a service's default values upon creation
Please check this section on the AWS Amplifiy [link](https://pr-1447.d2ngvl90zqbob8.amplifyapp.com/actions-and-automations/define-automations/examples#automation-definition-3). It seem to have broken

2024-08-13 16:37 UTC, PeyGis commented on docs/actions-and-automations/define-automations/examples.md
> +<br></br>
I don't think this section will be needed sine we want to keep it short

2024-08-14 04:13 UTC, kodjomiles commented on docs/actions-and-automations/define-automations/examples.md
> +<br></br>
okay

2024-08-14 04:14 UTC, kodjomiles commented on docs/actions-and-automations/define-automations/examples.md
> +
okay

2024-08-20 12:22 UTC, PeyGis requested changes
left some comments

2024-08-20 12:22 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +- Configure a [Slack app](https://api.slack.com/apps) that can post a message to a Slack channel. The app should have a `chat:write` bot scope under OAuth & Permissions.
should be Configured

2024-08-20 12:22 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +## Integrate GitHub Resources with Port
```suggestion
## Integrate GitHub resources with Port
```

2024-08-20 12:22 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +:::info Note
Replace Note with Role Requirement or something that captures this sentence

2024-08-20 12:22 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +    - If the `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> does not exist, create it with the schema provided below.
remove the blueprint tooltip from this block

2024-08-20 12:41 UTC, PeyGis requested changes
left some more comments

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +### Add the `openDuration` and `nudgeSent` Properties to the `Pull Request` Blueprint
```suggestion
### Add the `openDuration` and `nudgeSent` properties to the `Pull Request` blueprint
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +1. Navigate to the `Pull Request` <PortTooltip id="blueprint">blueprint</PortTooltip> in your Port Builder.
remove all instances of the tooltip

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +### Add the Mirror Properties to the `Pull Request` Blueprint
```suggestion
### Add the mirror properties to the `Pull Request` blueprint

```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +### Update/Create the `Service` Blueprint
```suggestion
### Update/Create the `Service` blueprint
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +    <summary>Relation mapping (click to expand)</summary>
```suggestion
    <summary>Configuration mapping (click to expand)</summary>
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +
There is no content under this header? I will prefer if we add something like "In the following section, we will define the automation that will xyz" or something better

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +         "channel": "{{ .event.diff.after.properties.serviceSlackChannel }}",
why do we need the channel in the body? And what are we using it for?

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +### 1. Automation to Send Slack Notification
```suggestion
### 1. Automation to send Slack notification
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +### 2. Automation to Mark Nudge as Sent
```suggestion
### 2. Automation to manage sent notifications
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +- **`nudgeSent`**: This property is a boolean flag that helps prevent multiple notifications for the same PR. Once a notification is sent, this property is set to `true`, ensuring that no further not
maybe we can instead use `isNotificationSent`?

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +## Slack Message Example
```suggestion
## Example Slack message
```

2024-08-20 12:41 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +<img src='/img/guides/overduePrSlackNotification.png' border='1px' />
Can you take another screenshot with more real-life example of this feature? let's update the title

2024-08-20 13:01 UTC, PeyGis requested changes

2024-08-20 15:28 UTC, kodjomiles commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +         "channel": "{{ .event.diff.after.properties.serviceSlackChannel }}",
double checking. sends the notification to the specified slack channel name, in case the webhook isn't a direct one for the slack group

2024-08-21 12:09 UTC, PeyGis approved these changes
LGTM

2024-08-21 12:09 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +<summary>Click to view the automation definition for sending Slack notifications</summary>
```suggestion
<summary>Automation for sending Slack notifications (click to expand)</summary>
```

2024-08-21 12:09 UTC, PeyGis commented on docs/guides-and-tutorials/automated-slack-alert-for-old-prs.md
> +  <summary>Click to view the automation definition for marking notification as sent</summary>
```suggestion
  <summary>Automation for marking notification as sent (click to expand)</summary>
```

2024-08-21 14:41 UTC, hadar-co approved these changes

2024-08-21 14:54 UTC, merged