PORT-8929 | Update the lock and unlock service guide to use upsert entity and automations
port-labs/port-docs pull request #1451
Opened 2024-08-05 03:07 UTC by kodjomiles

# Description

- Updated the lock and unlock service guide to use create/update entity action and entity update automation trigger
- Removed github workflow implementation to simplify lock and unlock service
- Replaced old images with new implementation images

## Updated docs pages
- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- https://docs.getport.io/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port

2024-08-13 16:51 UTC, PeyGis requested changes

2024-08-13 16:51 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> -2. Configure a [Slack app](https://api.slack.com/apps) that can post a message to a Slack channel. The app should have a `chat:write` bot scope under **OAuth & Permissions**.
we still need this prerequisite

2024-08-13 16:51 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> +   When the `update entity` backend is triggered,
rename to `UPDATE_ENTITY` since it is a type of trigger

2024-08-14 03:43 UTC, kodjomiles commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> -2. Configure a [Slack app](https://api.slack.com/apps) that can post a message to a Slack channel. The app should have a `chat:write` bot scope under **OAuth & Permissions**.
we are not using a bot anymore. it's just the webhook so we don't need that

2024-08-14 03:43 UTC, kodjomiles commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> +       - Copy the generated webhook URL.
okay got it

2024-08-20 12:56 UTC, PeyGis requested changes

2024-08-28 13:10 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> +  <summary>Click to expand: Port Action - Unlock Service</summary>
```suggestion
  <summary></b>Port Action - Unlock Service (click to expand)</b></summary>
```

2024-08-28 13:13 UTC, PeyGis commented on docs/actions-and-automations/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md
> +## Test the actions in [self-service](https://app.getport.io/self-serve)
```suggestion
## Test the lock and unlock actions
```

2024-09-03 10:43 UTC, closed without merging

2024-09-03 10:43 UTC, kodjomiles commented
Moved content to a new branch