Enrich services gitops wf fix
port-labs/port-docs pull request #1459
Opened 2024-08-05 19:07 UTC by priyaraghu0412

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-08-06 06:53 UTC, MPTG94 requested changes
The a look at my comments

2024-08-06 06:53 UTC, MPTG94 commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +          sed -i 's/{{ domain_identifier }}/${{ fromJson(inputs.domain).identifier }}/' ./targetRepo/port.yml
This change is unclear to me, I see that in the control the payload section of the action in the doc, you are asked to configure the following:
![image](https://github.com/user-attachments/assets/db002fd5-7bbb-4acc-8251-c623d691ddb9)

So from what I understand the `{{ $inputs.domain }}` should already contain specifically the domain's identifier

2024-08-06 06:53 UTC, MPTG94 commented on docs/api-reference/create-an-entity.api.mdx
> +        param={{"schema":{"type":"boolean","default":false},"in":"query","name":"merge","required":false,"description":"If `upsert` is `true` and `merge` is also `true`, this call will update the ent
Changes to the API reference need to be made in the [apispec.yaml](https://github.com/port-labs/port-docs/blob/main/static/apispec.yaml) file.

Please remove the changes from this file (it will get overwritten by a new build of the docs) and make those in the spec file.

2024-08-09 12:17 UTC, hadar-co commented on docs/api-reference/create-an-entity.api.mdx
> +        param={{"schema":{"type":"boolean","default":false},"in":"query","name":"merge","required":false,"description":"If `upsert` is `true` and `merge` is also `true`, this call will update the ent
@priyaraghu0412 @MPTG94 I have made the change in the API spec, you can remove this from the PR :)

2024-08-09 17:31 UTC, priyaraghu0412 commented on docs/api-reference/create-an-entity.api.mdx
> +        param={{"schema":{"type":"boolean","default":false},"in":"query","name":"merge","required":false,"description":"If `upsert` is `true` and `merge` is also `true`, this call will update the ent
@hadar-co Thank you!

2024-08-09 17:32 UTC, closed without merging