PORT-9395 | Update sonarqube guide to use search relation
port-labs/port-docs pull request #1464
Opened 2024-08-06 17:23 UTC by kodjomiles

# Description

This PR updates the SonarQube analysis to use the new search relation feature.

## Updated docs pages
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis

2024-08-06 17:24 UTC, kodjomiles commented
requesting close as this  PR has been moved to the main repository.

2024-08-07 07:25 UTC, hadar-co requested changes

2024-08-07 07:25 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +  - kind: pull-request
fix indentation of this code snippet

2024-08-07 08:37 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +  - kind: pull-request
Done

2024-08-07 08:37 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +  - kind: pull-request
thank you it was an oversight

2024-08-07 09:41 UTC, PeyGis requested changes
left some comments

2024-08-07 09:41 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +to establish the relationship between a GitHub `pull-request` entity and a SonarQube `analysis` entity:
```suggestion
We will explore two ways to establish the relationship between a GitHub `pull-request` entity and a SonarQube `analysis` entity:
```

2024-08-07 09:41 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +The first way is to use the `title` and `branch` properties:
```suggestion
The first approach is to establish a match using the title and branch properties
```

2024-08-07 09:41 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +  ensuring accurate mapping even if there are pull requests with similar titles on different branches.
```suggestion
  The `branch` property gives information about the source and destination of the the code changes. Combining the title with the branch offers a robust mapping, ensuring that entities are correctly matched in situations where there are similar pull request titles but on different branches.
```

2024-08-07 09:41 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/guides/connect-github-pr-with-sonar-analysis.md
> +The second way is to use the `commitSha` property:
```suggestion
The second option is to use the `commitSha` property that is common to both the pull request and SonarQube analysis:
```

2024-08-13 13:37 UTC, hadar-co approved these changes

2024-08-13 13:50 UTC, PeyGis approved these changes
LGTM

2024-08-13 13:54 UTC, merged