PORT-9720-bug-|-docs-fix-github-user-blueprint-example
port-labs/port-docs pull request #1468
Opened 2024-08-09 09:19 UTC by kodjomiles

…n update

# Description
(docs: Added GitHub user, team, and repository mapping with documentation update)
## Added docs pages

## Updated docs pages
- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples#map-repositories-and-teams

2024-08-09 11:31 UTC, hadar-co requested changes

2024-08-09 11:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
> +:::note
give the admonition a title, like this:
:::note title-here
content here
:::

Titles make it more likely that users will not miss a note/warning/tip

2024-08-09 11:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
> +:::tip
title (see the last comment above)

2024-08-09 12:03 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
> +:::note
So just to be clear I'm to change this to title ?

2024-08-09 12:03 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
> +:::tip
From notes to title ?

2024-08-09 14:18 UTC, PeyGis requested changes
looks good. just some formatting comments

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
> +<RepositoryUserBlueprint/>
the user blueprint should come before the team since the team requires the user

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +            defaultBranch: ".default_branch"
```suggestion
            defaultBranch: .default_branch
```

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +            url: ".html_url"
```suggestion
            url: .html_url
```

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +            readme: "file://README.md"
```suggestion
            readme: file://README.md
```

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +            notification_setting: ".notification_setting"
remove the string quote from the jq

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +            user: ".email"
remove the "" from the .email

2024-08-09 14:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-teams/_github_exporter_example_repository_with_teams_and_users_port_app_config.mdx
> +          title: ".email"
same here, remove the quote

2024-08-09 16:28 UTC, PeyGis approved these changes
LGTM

2024-08-10 09:04 UTC, hadar-co approved these changes

2024-08-10 09:04 UTC, merged