PORT-9272 | Change guides to parse files using the file kind
port-labs/port-docs pull request #1470
Opened 2024-08-09 18:01 UTC by lordsarcastic

# Description
Changed packages parser to use the GitHub file kind instead of webhooks

## Updated docs pages

- Packages (`docs/build-your-software-catalog/custom-integration/webhook/examples/packages`)

2024-08-15 19:09 UTC, PeyGis requested changes
looks good overall. just some few comments

2024-08-15 19:09 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/packages/trivy.md
> +            data_source: .item.DataSource
The mapping is not formatted well so it throws error when you copy and paste it in Port. I have modified it so replace it using

```
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/results.json'
    port:
      itemsToParse: '[.file.content[] | select(.Vulnerabilities != null) as $input | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, FixedVersion, Title, Description, Severity, References, PrimaryURL, DataSource, Target: $input.Target}]'
      entity:
        mappings:
          identifier: .item.VulnerabilityID
          title: .item.Title
          blueprint: '"trivyVulnerability"'
          properties:
            version: .item.InstalledVersion
            package_name: .item.PkgName
            primaryUrl: .item.PrimaryURL
            description: .item.Description
            target: .item.Target
            severity: .item.Severity
            data_source: .item.DataSource
```

2024-08-16 17:24 UTC, PeyGis requested changes
check my comment on the indentation for the trivy config mapping

2024-08-16 17:24 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/packages/trivy.md
> +      query: 'true'
this still doesn't work. the kind and selector must be on the same indentation level

2024-08-21 08:39 UTC, PeyGis approved these changes
LGTM

2024-08-25 08:06 UTC, hadar-co requested changes

2024-08-25 08:06 UTC, hadar-co commented on docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/connect-github-codeowners-with-service-team-and-user.md
> +resources:
this snippet is empty

2024-08-29 11:43 UTC, hadar-co approved these changes

2024-08-29 12:31 UTC, merged