PORT-7464-move-webhook-integration-examples-to-integrate-with-any-tool
port-labs/port-docs pull request #1482
Opened 2024-08-12 18:53 UTC by kodjomiles

# Description

moved dynatrace to intergrate port with any tool

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace

![image](https://github.com/user-attachments/assets/bf9f2175-047a-46bf-8482-4bfbdc708a3a)

2024-08-13 09:05 UTC, PeyGis requested changes
LGTM

2024-08-13 09:05 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md
> +
This example for ingesting entities should come after the webhook installation method (after mapping result)

2024-08-20 13:14 UTC, PeyGis requested changes
LGTM

2024-08-20 13:14 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md
> +Here’s how you can revise the flow:
this is out of context so remove it

2024-09-24 20:35 UTC, PeyGis approved these changes
previous comments have been addressed so this looks good to me

2024-09-25 11:18 UTC, hadar-co requested changes

2024-09-25 11:18 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md
> +We can create a webhook integration between [Datadog](https://www.datadoghq.com/) and Port, which will ingest alerts and monitor entities into Port and map them to your microservice entities.
@kodjomiles For consistency, the opening paragraph of this section is the same for all integrations, for example:
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/project-management/jira/#alternative-installation-via-webhook

Please keep this paragraph in all integrations in this PR

2024-09-25 13:28 UTC, hadar-co approved these changes

2024-09-25 13:29 UTC, merged