Add "supported resources" section to all Ocean integration docs that still do not have it
port-labs/port-docs pull request #1504
Opened 2024-08-16 18:29 UTC by lordsarcastic

# Description

Some integration docs do not have "supported resources" section. This PR adds it to these integrations

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-08-21 08:49 UTC, PeyGis requested changes

2024-08-21 08:49 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
> +- `build` - `\<your-jenkins-host\>/api/json)
Jenkins build and job are using the same API?

2024-08-22 09:27 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
> +- `build` - `\<your-jenkins-host\>/api/json)
Yes, they are

2024-08-22 09:27 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
> +- `build` - `\<your-jenkins-host\>/api/json)
Builds are found under jobs

2024-08-28 10:50 UTC, PeyGis requested changes

2024-08-28 10:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
> +- `user` - (`\<your-jenkins-host\>/people/api/json`)
```suggestion
- `job` - (`<your-jenkins-host>/api/json`)
- `build` - (`<your-jenkins-host>/api/json`)
- `user` - (`<your-jenkins-host>/people/api/json`)
```

2024-08-28 10:51 UTC, PeyGis approved these changes
LGTM

2024-09-02 14:58 UTC, hadar-co approved these changes

2024-09-02 15:06 UTC, merged