Add cloud resources for Dynatrace integration
port-labs/port-docs pull request #1521
Opened 2024-08-22 22:04 UTC by lordsarcastic

# Description
Added a guide to ingest cloud resources from Dynatrace integration

## Added docs pages

Please also include the path for the added docs

- Ingest cloud resources using Dynatrace (`docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md`)

2024-08-23 08:16 UTC, PeyGis requested changes
Looks great. just some minor comments

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +- Watch for object changes (create/update/delete) in real-time, and automatically apply the changes to your entities in Port.
The watch for object changes is only applied to webhooks so since this is only a guide, I don't think we need it

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +- You have entities from cloud providers configured on Dynatrace. See Dynatrace documentation for this.
`See Dynatrace documentation for this.`

Can you add the link to the documentation?

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +- `cloud:gcp:pubsub_snapshot`
This is great. I will prefer we remove some and replace the aws and azure types. For now it looks like they are all gcp types. so 5 of gcp, 5 of aws and 5 of azure

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +        - cloud:gcp:pubsub_snapshot
Then you can apply the changes you made above here with mixed entity types for all the 3 cloud providers

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +<img src='/img/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/dynatraceCloudResourcesResults.png' border='1px' />
Let's change this image so that the entity identifier doesn't report CUSTOM_DEVICE etc. Let's use the displayName as the identifier, which is more human readable.

2024-08-23 08:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +
As a tip, you can also mention that they can get other entity types by making a request to this Dynatrace enpoint

https://<environment-id>.live.dynatrace.com/api/v2/entityTypes

2024-08-23 09:42 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +<img src='/img/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/dynatraceCloudResourcesResults.png' border='1px' />
The display name sometimes contains spaces which isn't allowed by Port

2024-08-23 09:48 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/ingest-cloud-resources-using-dynatrace.md
> +<img src='/img/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/guides/dynatraceCloudResourcesResults.png' border='1px' />
sure, let's use this mapping then

.displayName | gsub(" "; "-")

2024-08-23 09:49 UTC, PeyGis approved these changes
LGTM

2024-08-25 06:57 UTC, hadar-co approved these changes

2024-08-25 07:04 UTC, merged