Added docs to the page permissions routes
port-labs/port-docs pull request #153
Opened 2023-01-03 13:44 UTC by matanl490

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-01-04 12:00 UTC, EllaFurman requested changes

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +## What is a Page?
```suggestion
## What is a page?
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +All table operations are available on the top bar of the table:
Hasn't this been written already in line 70?

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +Filtering a table is done using the following menu:
```suggestion
YOu can filter a table by using the following menu:
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +You can filter according to one or many fields while setting the relation between each field filter: `And/Or`.
```suggestion
To filter, you can define any filtering operator with a suitable value.

You can filter one or more values while setting the relation between each field filter with a: `And/Or`.
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +Sorting the table is done on the following menu:
```suggestion
You can sort the table on the following menu:
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +Hiding table columns is done on the following menu:
```suggestion
You can hide table columns on the following menu:
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +Grouping by Entities is done on the following menu:
```suggestion
You can group by Entities on the following menu:
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +Group by is recommended when you want to create custom views for users, such as Microservices by Owners.
```suggestion
Group by is recommended when you want to create custom views for users, such as "microservices by owners".
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/page.md
> +We provide a free text search option on tables. Searching on a table is available on the left side of the top bar:
```suggestion
We provide a free text search option on tables. To search on a table, click the left side of the top bar:
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/tutorial.md
> +- Currently only Read permission can be modified.
```suggestion
- Currently only read permission can be modified.
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/tutorial.md
> +- Any user can get the permissions of a specific page.
```suggestion
- Any user can get permissions for a specific page.
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/tutorial.md
> +Only Page Permissions of Software Catalog Pages can be requested.
```suggestion
Only page permissions of software catalog pages can be requested.
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/tutorial.md
> +- Only users with the admin role can update the permissions of a specific page;
```suggestion
- Only admin users can update permissions of a specific page;
```

2023-01-04 12:00 UTC, EllaFurman commented on docs/software-catalog/page/tutorial.md
> +When updating the permissions of a page, be sure to include the list of roles and users that need permissions in every request. Any role or user that does not appear in the request body will lose per
```suggestion
When updating page permissions, be sure to include a list of roles and users that need permissions in every request. Any role or user that does not appear in the request body will lose permissions to the page (this is also how you deny permissions from a user)
```

2023-01-05 08:18 UTC, MPTG94 commented on docs/software-catalog/page/page.md
> +All table operations are available on the top bar of the table:
Line 70 refers to page operations, this line refers to table operations

2023-01-05 08:34 UTC, merged