Added Docs for Octopus Deploy Integration
port-labs/port-docs pull request #1530
Opened 2024-08-27 19:16 UTC by oiadebayo

# Description

Created a CI/CD category and moved Jenkins docs into the folder
Added a docs page for the new Octopus Deploy integration

## Added docs pages

Please also include the path for the added docs

- Octopus Deploy (`/docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md`)

2024-08-28 10:36 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
> +
I prefer the API Key generation guide comes after the installation. See the Dynatrace and ArgoCD docs for an example

2024-08-28 10:38 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
> +	--set port.clientSecret="744pUpiZImxIrjYrYWPojqOuU9UquYU5XZvMcRys3ty4Tp2tEYAnqE8FZrV6Lekk"  \
Replace the exposed client id and secret with a placeholder <YOUR_PORT_CLIENT_ID>

2024-08-28 15:33 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
> +
Done

2024-08-28 15:33 UTC, oiadebayo commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
> +	--set port.clientSecret="744pUpiZImxIrjYrYWPojqOuU9UquYU5XZvMcRys3ty4Tp2tEYAnqE8FZrV6Lekk"  \
Done

2024-08-30 16:34 UTC, PeyGis approved these changes
LGTM

2024-09-03 14:54 UTC, hadar-co requested changes

2024-09-03 14:54 UTC, hadar-co commented on docs/integrations-index.md
> +## CI/CD
please remove this title and add Jenkins in the same level as the other headers.
This is because there are other sections there that are related to CI/CD and its confusing that they are not also under that header

2024-09-03 16:32 UTC, oiadebayo commented on docs/integrations-index.md
> +## CI/CD
Done

2024-09-04 10:23 UTC, hadar-co approved these changes

2024-09-04 10:29 UTC, merged