Port 9873 Add jenkins pipeline stages to jenkins integration
port-labs/port-docs pull request #1531
Opened 2024-08-28 11:24 UTC by phalbert

# Description

Updated docs for [adding the `stage` kind](https://github.com/port-labs/ocean/pull/960) in the Jenkins integration

## Updated docs pages

Please also include the path for the updated docs

- Jenkins (`docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md`)

2024-08-28 11:48 UTC, PeyGis requested changes

2024-08-28 11:48 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
> +Our Jenkins integration allows you to import `jobs`, `builds`, `stages`, and `users` from your Jenkins environment into Port, according to your mapping and definitions.
```suggestion
Port's Jenkins integration allows you to import `jobs`, `builds`, `stages`, and `users` from your Jenkins environment into Port, according to your mapping and definitions.

```

2024-09-25 11:34 UTC, hadar-co approved these changes
LGTM, has someone tested to see that the new snippets work as expected?

2024-09-25 12:04 UTC, PeyGis requested changes
some comment

2024-09-25 12:04 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
> +    jobUrl: http://localhost:8080/job/limbopay/job/Limbo%20Core/job/main
can we make it clear that the jobUrl is only an example so user's don't copy and paste this in their data sources mapping? And that they should replace it with their own jobUrl from one of their job

2024-09-25 12:04 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
> +    jobUrl: http://localhost:8080/job/Phalbert/job/airframe-react
same as above

2024-09-25 12:04 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
> +    jobUrl: http://localhost:8080/job/Phalbert/job/autoshop_api
same as above

2024-09-25 14:33 UTC, closed without merging