PORT-9832 Update Multi-account minimum permission to install the Ocean AWS Exporter
port-labs/port-docs pull request #1535
Opened 2024-08-30 10:56 UTC by oiadebayo

# Description

This PR updates the documentation for configuring the Ocean AWS exporter to use the minimum necessary permissions for multi-account setups. The changes address client concerns regarding elevated permissions by adjusting the configurations for the Integration Account, Member Accounts, and Root Account to adhere to a security-focused, minimal permissions model. These updates ensure that the exporter operates effectively while minimizing potential security risks.

## Added docs pages

Please also include the path for the added docs

- No new docs pages were added in this update.

## Updated docs pages

Please also include the path for the updated docs

- Multi Account Installation (`docs\build-your-software-catalog\sync-data-to-catalog\cloud-providers\aws\installations\multi_account.md`)

2024-08-30 16:17 UTC, PeyGis requested changes
LGTM. Just some few comments

2024-08-30 16:17 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
> +in this example it's S3 bucket permissions
```suggestion
If you need to read from the `integration account`, you'll need to add CloudControl (cloudformation) and the resources permissions. In this example, we refer to the S3 bucket permissions
```

2024-08-30 16:17 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
> +In each non-root account (target member account), The Role `accountReadRoleName` must exist with necessary permissions to access S3 resources, list regions, and interact with CloudFormation resources
```suggestion
In each non-root account (target member account), The Role `accountReadRoleName` must exist with the necessary permissions to access S3 resources, list regions, interact with CloudFormation resources, and include `accountReadRoleName` from the `integration account` in its trust policy. See [reference](#member-account)
```

2024-08-30 16:17 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
> +First, we will create a role with necessary permissions (If you're running the terraform installation, this will be done for you). We'll call this role `ReadOnlyPermissionsOceanRole`, with `I can rea
```suggestion
First, we will create a role with necessary permissions (if you're running the terraform installation, this will be done for you). We'll call this role `ReadOnlyPermissionsOceanRole`, with `I can read resources in this account` policy.
```

2024-08-30 16:21 UTC, PeyGis approved these changes

2024-09-22 06:59 UTC, hadar-co approved these changes

2024-09-22 07:04 UTC, merged