package dependency ingesting
port-labs/port-docs pull request #1538
Opened 2024-09-02 05:06 UTC by kodjomiles

# Description
Added the documentation for ingesting dependencies from packages into service using the file kind

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- /build-your-software-catalog/sync-data-to-catalog/git/github/guides/get-dependencies-from-package-json-and-relate-them-with-service

2024-09-02 11:41 UTC, gurshafriri commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +resources:
```suggestion
# (resources:)
```

I think it will be clearer this way that only the kind itself should be added @hadar-co what do you think?

2024-09-02 11:41 UTC, gurshafriri commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +resources:
```suggestion
# (resources:)
```

same here

2024-09-02 12:16 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +resources:
okay

2024-09-02 12:16 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +resources:
okay

2024-09-03 08:52 UTC, PeyGis requested changes
left some changes

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +4. **Add ths JSON schema**:
typo on the "this"

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +      "semver_requirement": {
what is semver? do you mean server?

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +        "title": "Semver requirement"
server?

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +      "semver_requirement"
server?

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +            semver_requirement: .item.value
semver again?

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +3. Head back to the [data sources page](https://app.getport.io/settings/data-sources) Add the mapping below:
```suggestion
3. Head back to the [data sources page](https://app.getport.io/settings/data-sources) and add the mapping below:
```

2024-09-03 08:52 UTC, PeyGis commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +- [Mini guide to connecting services](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/guides/)
this link doesn't work. throws 404. please fix it or remove it

2024-09-03 09:25 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +      "semver_requirement": {
semantic version

2024-09-03 09:26 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +4. **Add ths JSON schema**:
okay

2024-09-03 09:27 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +        "title": "Semver requirement"
No please semantic version

2024-09-03 09:28 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +- [Mini guide to connecting services](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/guides/)
okay

2024-09-03 09:29 UTC, kodjomiles commented on docs/guides/all/ingest-dependencies-from-package-json-to-service.md
> +            semver_requirement: .item.value
Semantic version, the guide was written based on a demo. All this was replicated from the demo

2024-09-03 10:47 UTC, PeyGis approved these changes
LGTM

2024-09-03 11:02 UTC, hadar-co approved these changes

2024-09-03 11:37 UTC, merged