Added main page for export templates
port-labs/port-docs pull request #154
Opened 2023-01-04 12:46 UTC by MatanHeledPort

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-01-09 14:42 UTC, MPTG94 approved these changes
LGTM ask Aviv and Ella for a proof read after applying fixes

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/export-templates.md
> +Then, in order to map `applications`, your `config.yaml` will contain:
```suggestion
Then, in order to map ArgoCD `applications`, add the matching resource kind to your `config.yaml`:
```

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/export-templates.md
> +We created some pre-built Port K8s exporter templates covering different applications.
```suggestion
We created several pre-built Port K8s exporter templates covering different applications.
```

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/export-templates.md
> +Each template will include:
Right now this line and the previous one appear in the same line, if you want to separate them, you will need to add another blank link between therm

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +An ArgoCD Application is an Argo CRD which is responsible for managing different k8s objects, while a ArgoCD project clusters Applications.
```suggestion
An ArgoCD Application is an Argo CRD which is responsible for managing different k8s objects, while an ArgoCD project is an Argo CRD which clusters Applications.
```

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +This template covers ArgoCD Applications with relations to Deployments and Services, like ArgoCD's [Getting Started](https://argo-cd.readthedocs.io/en/stable/getting_started/) application `guestbook-
```suggestion
This template covers ArgoCD Applications with Relations to Deployments and Services, like ArgoCD's [Getting Started](https://argo-cd.readthedocs.io/en/stable/getting_started/) application `guestbook-ui`.
```

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +Blueprints created in this template define Relations to Blueprints which are referenced in the [Full Kubernetes Exporter](../../../complete-use-cases/full-kubernetes-exporter.md) docs.
```suggestion
Blueprints created in this template define Relations to Blueprints which are referenced in the [Full Kubernetes Exporter](../../../complete-use-cases/full-kubernetes-exporter.md) docs.

Specifically the Blueprints in this example are related to the [service](https://github.com/port-labs/k8s-exporter-example/blob/main/terraform/Service.tf) and [deployment](https://github.com/port-labs/k8s-exporter-example/blob/main/terraform/Deployment.tf) Blueprints.
```

2023-01-09 14:42 UTC, MPTG94 commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +The files to this Exporter Template can be found **[here](https://github.com/port-labs/port-k8s-exporter-use-cases/tree/main/argocd)**
Please make the repo link bold in the K8s exporter complete use case doc

2023-01-10 10:43 UTC, EllaFurman requested changes

2023-01-10 10:43 UTC, EllaFurman commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +An ArgoCD Application is an Argo CRD which is responsible for managing different k8s objects, while an ArgoCD project is an Argo CRD which clusters Applications.
```suggestion
An ArgoCD application is an Argo CRD which is responsible for managing different k8s objects, while an ArgoCD project is an Argo CRD which clusters applications.
```

2023-01-10 10:43 UTC, EllaFurman commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +The files to this Exporter Template can be found **[here](https://github.com/port-labs/port-k8s-exporter-use-cases/tree/main/argocd)**
```suggestion
You can find the files to this exporter template **[here](https://github.com/port-labs/port-k8s-exporter-use-cases/tree/main/argocd)**
```

2023-01-10 10:43 UTC, EllaFurman commented on docs/exporters/k8s-exporter/export-templates/export-templates.md
> +For example, to figure out how to map your ArgoCD resources, you can run:
```suggestion
For example, in order to figure out how to map your ArgoCD resources, you can run:
```

2023-01-10 10:43 UTC, EllaFurman commented on docs/exporters/k8s-exporter/export-templates/argocd-template.md
> +This template covers ArgoCD Applications with Relations to Deployments and Services, like ArgoCD's [Getting Started](https://argo-cd.readthedocs.io/en/stable/getting_started/) application `guestbook-
```suggestion
This template covers ArgoCD applications with Relations to deployments and services, like ArgoCD's [Getting Started](https://argo-cd.readthedocs.io/en/stable/getting_started/) application `guestbook-ui`.
```

2023-01-10 12:17 UTC, merged