PORT-10112 DORA Metrics guide and implement the necessary demo environment adjustments.
port-labs/port-docs pull request #1551
Opened 2024-09-05 09:35 UTC by kodjomiles

# Description

a comprehensive DORA Metrics guide and implement the necessary demo environment adjustments.
## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- /guides/all/setup-dora-metrics

2024-09-05 13:26 UTC, Matanga1-2 requested changes
Added suggestions and change requests, let's discuss more online

2024-09-05 13:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +#### PR Merge
Let's add that this is the recommended way

2024-09-05 13:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +2. **Use Lead Time Calculation**:
The lead time for PR should already be part of the guide you mentioned for Github. If not, let's include it in the default mapping and the guide.

2024-09-05 13:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +3. **Deployment Creation**:
Maybe a better approach is to update the Github mapping?

e.g. for a kind of pull-request, create a new deployment entity with search criteria based on the branch?

2024-09-05 13:55 UTC, kodjomiles commented on src/components/guides-section/consts.js
> +        tags: ["SDLC","GitHub"],
Okay

2024-09-05 14:14 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +### Metrics Calculation
I am following the order of the notion guide, maybe the heading is misleading
![image](https://github.com/user-attachments/assets/e1997d9f-4f17-4665-8aa3-10579296511e)
maybe you can clarify

2024-09-05 15:13 UTC, Matanga1-2 requested changes

2024-09-05 15:31 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Metrics Calculation
@kodjomiles we discussed, metrics can move to another section

2024-09-05 15:51 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +3. **Deployment Creation**:
@Matanga1-2 does this mean the automation be removed 🙂 ?

2024-09-05 16:00 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +3. **Deployment Creation**:
@kodjomiles yes 
The automation can be removed, and instead we can show an addition to Github mapping that generates the deployment entity

2024-09-06 14:46 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +  "relations": {
I thought that would be done at the organizational blueprint level, we will add the service relation to the organizational blueprint there, or you want us to add the organizational blueprint here

2024-09-08 07:19 UTC, Matanga1-2 requested changes

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +- **Add the configuration below** to the [data sources page](https://app.getport.io/settings/data-sources) in your Port portal, and select your GitHub integration:
@kodjomiles worth explaining that this can be similarly implement for other runs/workflows in other tools

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +In Jenkins, each time a build is triggered or completed,
@kodjomiles do you think it's feasible to add examples for all the supported CI/CD tools?
Maybe a "details" section for each type?

Jenkins
Octopus
CircleCI
Azure PIpelines
Codefresh
Gitlab Pipelines

Also depends on your estimate

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +
@kodjomiles maybe worth adding one final example of "Custom API" explaining that you can always interact directly with Port API from your internal tools, and share ean example API call snippet to create a new deployment?

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +      query: ".repository.name == 'monorepo' && (.service == 'service-A' || .service == 'service-B')"
@kodjomiles can you please explain this line and how it assist with monorepo?

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +Incidents are key to calculating important DevOps metrics, including **Change Failure Rate (CFR)** and **Mean Time to Recovery (MTTR)**. Effective incident tracking provides insights into how frequen
```suggestion
Incidents are vital for DORA metrics, including **Change Failure Rate (CFR)** and **Mean Time to Recovery (MTTR)**. Effective incident tracking provides insights into how frequently deployments result in failures and how quickly these failures are resolved.
```

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +2. **Create a Mirror Property**: Set up mirror properties to reflect key incident data (e.g., **recoveryTime**, **resolvedAt**) on the related service. This makes it easier to track MTTR at the servi
@kodjomiles maybe this can be improved and shorten a bit?
For example
"Add the below addition to your Incident blueprint to relate Incident and Service

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +  "mirrorProperties": {
@kodjomiles why do we need mirror properties? are these mirrored from Incident into a Service?
Given a service has multiple incidents, what is the value of having it mirrored? 
Maybe it should be aggregated to the service level instead?

2024-09-08 07:19 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
@kodjomiles is it possible to just give the bottom line?

For example, "We will now add the metrics to the service level"
<< service blueprint updates>>

"We will add the metrics to a new Organization level blueprint
<<organization blueprint>>
"We will manually create a new Organization entity and connect service/teams to it (maybe automation/SS action. should discuss"

That's it, your portal is not tracking DORA metrics. All we are left to do is visualize it in a Dashboard

2024-09-08 07:21 UTC, Matanga1-2 requested changes

2024-09-08 07:21 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
Also it should probably be ##? it's a new section, not under incidents

2024-09-09 09:38 UTC, kodjomiles commented on src/components/guides-section/consts.js
> +        title: "Setup Dora Metrics",
Tracking sounds better

2024-09-09 09:53 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
it's a calculation property. taking that from the pr level would have to be mirrored in the deployment blueprint yes ?
Should we go for that instead ?

2024-09-09 10:39 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +- Access a GitHub repository (e.g., `port-dora-metrics`) with workflows or pipelines for tracking deployments. Follow the [GitHub integration guide](https://docs.getport.io/build-your-software-catalo
I think we can remove it since it's not required for the basic/recommended approach.
You could write it below in the section that actually requires this

2024-09-09 10:40 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
Yeah a mirror property make sense, or alternatively map something like

leadTime: leadTime

2024-09-09 11:11 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +- Access a GitHub repository (e.g., `port-dora-metrics`) with workflows or pipelines for tracking deployments. Follow the [GitHub integration guide](https://docs.getport.io/build-your-software-catalo
okay

2024-09-09 11:30 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +- Access a GitHub repository (e.g., `port-dora-metrics`) with workflows or pipelines for tracking deployments. Follow the [GitHub integration guide](https://docs.getport.io/build-your-software-catalo
can we do something like this 

- Complete the [Port onboarding process](https://docs.getport.io/quickstart).
- Access a GitHub repository (e.g., port-dora-metrics) to sync your pull requests or deployments. You can follow the [GitHub integration guide](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/git/github) to ensure your deployments are tracked in Port.
- Optional for advanced strategies: If you're using workflows or pipelines, ensure they are configured for deployment tracking by following the relevant setup guides, such as CI/CD or GitHub Actions.

2024-09-09 11:31 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +- Access a GitHub repository (e.g., `port-dora-metrics`) with workflows or pipelines for tracking deployments. Follow the [GitHub integration guide](https://docs.getport.io/build-your-software-catalo
make it an optional prerequisite ?

2024-09-09 11:34 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +      query: ".repository.name == 'monorepo' && (.service == 'service-A' || .service == 'service-B')"
### Purpose of this Query for Monorepos:

- **`.repository.name == 'monorepo'`**: This condition ensures that the mapping applies only to repositories named **'monorepo'**, which is typical in monorepos where multiple services live in a single repository.
  
- **`(.service == 'service-A' || .service == 'service-B')`**: This additional condition filters the specific services within the monorepo. For example, if the monorepo contains multiple services (e.g., **service-A** and **service-B**), this query isolates and maps those specific services only, ensuring that they are treated as separate entities in Port.

### How it Assists with Monorepos:
In a **monorepo** setup, you have multiple services housed within a single repository. Each service might have its own deployment pipeline, ownership, and lifecycle. This query allows Port to treat each service as a separate entity while still being sourced from the same monorepo. 

By mapping specific services using this query, we ensure that Port can differentiate between the services and track their specific metadata, deployments, and incidents separately. This is crucial for environments that require granular tracking and management of microservices or different features within a single repository.

2024-09-09 12:02 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +2. **Create a Mirror Property**: Set up mirror properties to reflect key incident data (e.g., **recoveryTime**, **resolvedAt**) on the related service. This makes it easier to track MTTR at the servi
Straight to the point yeah okay

2024-09-09 14:47 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +  "mirrorProperties": {
if it's syncing across multiple incidents then aggregating is better

2024-09-09 14:50 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
when can we discuss this

2024-09-09 14:51 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
thought we were putting it under incidents

2024-09-09 15:05 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
we can't map leadTime to a leadTime from PR because that property doesn't exist.. it's a calculated property, making it a mirror would make sense.

2024-09-09 15:09 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
and the lead time on the pr blueprint is in days not in minutes, should I still go ahead

2024-09-09 15:23 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
"mirrorProperties": {
"leadTimeDays": {
"title": "Lead Time (Days)",
"mirror": ".relations.pullRequest.properties.lead_time_days",
"type": "number",
"description": "Mirrored lead time from Pull Request Blueprint in days."
}
},
"calculationProperties": {
"leadTimeMinutes": {
"title": "Lead Time (Minutes)",
"type": "number",
"calculation": ".properties.leadTimeDays * 1440",
"description": "Lead time in minutes, calculated from leadTimeDays."
}
}

and if that's the case we have to do a calculation to probably bring it to minutes

2024-09-09 15:38 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
@kodjomiles good questions
Lets finalize it later when we conclude the doc
For now just mirror a lead in days property.

2024-09-09 15:40 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          leadTime: |
okay

2024-09-09 15:41 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
@kodjomiles the overall structure can be

Deployment 
Incidents
Metrics
Dashboards

Agree?

2024-09-09 15:44 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
agree

2024-09-09 16:41 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +In Jenkins, each time a build is triggered or completed,
This would make it very long

2024-09-11 07:15 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Metric Calculations
Discussed

2024-09-16 09:36 UTC, Matanga1-2 requested changes

2024-09-16 09:36 UTC, Matanga1-2 commented on static/img/guides/doraMetricsDBVisualization.png
@kodjomiles  Showing the lead time in seconds looks weird. Can we update the Demo env please to show it in Minutes?

2024-09-16 09:36 UTC, Matanga1-2 commented on src/components/guides-section/consts.js
> +        tags: ["Engineering metrics","GitHub"],
@kodjomiles also add the port pillars as tags
We have in this guide Dashboards

2024-09-16 09:36 UTC, Matanga1-2 commented on src/components/guides-section/consts.js
> +        title: "Tracking Dora Metrics",
```suggestion
        title: "Tracking DORA Metrics",
```

2024-09-16 09:36 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +This aggregation setup will calculate the **average MTTR** by considering incidents that have been resolved,
@kodjomiles to clarify, MTTR is "mean time to recovery"
So average is redundant 
```suggestion
This aggregation setup will calculate the **MTTR** by considering incidents that have been resolved,
```

2024-09-16 09:36 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +Let's visualize the DORA metrics using **Port's Dashboard** feature. You can create custom dashboards to track these metrics and monitor your team's performance over time.
```suggestion
By leveraging Port's Dashboards, you can create custom dashboards to track the metrics and monitor your team's performance over time.
```

2024-09-16 09:36 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +5. Click **Save**.
@kodjomiles maybe we can add for at least one metric a screenshot of how it looks like before "save"?

2024-09-16 09:36 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +Congrats 🎉 You've successfully setup dora metrics in Port 🔥
```suggestion
Congrats 🎉 You've successfully setup DORA metrics in Port 🔥
```

2024-09-16 10:29 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Instead of mirroring properties like `recoveryTime` and `resolvedAt` at the service level, **aggregate** them to calculate the average **MTTR** across multiple incidents.
I have resolved this already, I think the comment was made on an old review

2024-09-16 10:30 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +To achieve this, we will aggregate data at the **Organization** level.
this too

2024-09-16 10:31 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Define the **Organization** blueprint and add these relationships to connect it with Deployments,
This isn't present aas well, I don't have anything like this anymore.
I think the review was done on old code

2024-09-16 10:32 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +
I am confused here

2024-09-16 10:34 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +By defining the **Organization** blueprint, adding the necessary relationships, and using these calculation blocks, you can successfully calculate the four main DORA metrics: **Deployment Frequency**
We are no more dealing with organization, but I can still add that it takes 15 minutes to show up as part of the limitations which is already stated in the aggregation docs page.

2024-09-16 10:35 UTC, kodjomiles commented on static/img/guides/doraMetricsDBVisualization.png
okay

2024-09-16 12:46 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +5. Click **Save**.
OKAY

2024-09-16 19:01 UTC, kodjomiles commented on static/img/guides/doraMetricsDBVisualization.png
We have to leave it for now for the complexities that comes with changing that value

2024-09-20 06:02 UTC, Matanga1-2 commented
@kodjomiles should this PR be closed?

2024-09-20 12:25 UTC, closed without merging