PORT-10112 Comprehensive DORA Metrics guide
port-labs/port-docs pull request #1594
Opened 2024-09-18 10:33 UTC by kodjomiles

# Description

a comprehensive DORA Metrics guide for tracking services on port

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- /guides/all/setup-dora-metrics

2024-09-18 12:26 UTC, Matanga1-2 requested changes

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
Incident or Service? I think Service, no?

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
Actually why is it even required here? don't we cover it in the metrics part?

@kodjomiles

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +
@kodjomiles add here that the timeframes are monthly but you can easily switch to weekly etc.

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          "value": "Success"
@kodjomiles why aren't we showing here timerframe?
e.g. monthly in our example

Aggregate per month

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +    "calculationSpec": {
@kodjomiles why not monthly?

2024-09-18 12:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +5. Select the `Hour` time interval and preferred time range
Why not monthly? 
@kodjomiles

2024-09-18 12:44 UTC, hadar-co requested changes

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +# DORA metrics
```suggestion
# Track DORA metrics
```

2024-09-18 12:44 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        title: "Tracking DORA Metrics",
```suggestion
        title: "Track DORA Metrics",
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +understand and implement [DevOps Research and Assessment (DORA) metrics](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance) within your organiza
```suggestion
implement and track [DevOps Research and Assessment (DORA) metrics](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance) within your organization in Port.  
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +This guide will cover the four key metrics: Deployment Frequency, Lead Time, Change Failure Rate, and Mean Time to Recovery.
```suggestion
This guide will cover the four key metrics: **deployment frequency**, **lead time**, **change failure rate**, and **mean time to recovery**.
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +:::info Prerequisites
Please list the prerequisites under a header (## Prerequisites) and not in an admonition.

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +:::tip Adding JSON Schema Using Port's UI
this tip doesn't make much sense here, it is out of context. Let's add this information where it's needed, for example in the "Data model setup" section it can be added as a last step (click "Edit JSON").

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +Ensure that your **PagerDuty incident blueprint** is configured properly. You can follow the detailed steps in the [PagerDuty Incident Blueprint](https://docs.getport.io/build-your-software-catalog/s
Unclear what these steps are, needs elaborating. Also, the link takes to the head of the page, perhaps you can link directly to the incident header?

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
Make sure that things like this are explained at least once. Users will probably not know how to add an aggregation property to a blueprint.

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +1. Go to **Catalog** in the navigation bar
```suggestion
1. Go to your [software catalog](https://app.getport.io/organization/catalog).
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +2. Click **new**
```suggestion
2. Click on the `+ New` button in the left sidebar.
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +### Dashboard Setup
make sure to be specific with links and instructions, and put button names in `quotes like this` (See my suggestions on points 1 and 2)

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +By following these steps, you can create a custom dashboard to visualize the DORA metrics.
```suggestion
```

2024-09-18 12:44 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +Congrats 🎉 You've successfully setup DORA metrics in Port 🔥
```suggestion
Congrats 🎉 You have successfully set up DORA metrics tracking in your portal 🔥
```

2024-09-18 23:10 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Ensure that your **PagerDuty incident blueprint** is configured properly. You can follow the detailed steps in the [PagerDuty Incident Blueprint](https://docs.getport.io/build-your-software-catalog/s
I agree.

2024-09-18 23:31 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
we do but we use this when we want to mirror from the pagerduty service blueprint the mttr aggregated property on the service bp

2024-09-18 23:32 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
Yeah, I agree.. it was like that initially but we talked about making it very minimalistic. let me add a link that would guide them to how aggregation works

2024-09-18 23:33 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
but since it's not referenced anywhere I might as well remove it

2024-09-18 23:34 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +Add the following **aggregation properties** to the **Incident blueprint**
we don't need that section anymore

2024-09-18 23:34 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +
okay sure thing

2024-09-18 23:43 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +    "title": "Lead Time for Change",
got it

2024-09-19 00:28 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "value": "Success"
we are getting the total value for all deployments so I thought that should  not be  based on a timeframe

2024-09-19 05:06 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          "value": "Success"
I think we should follow the guideline of monthly metrics
What you did shows the rate lifetime. Instead we want to measure the rate on a monthly basis. WDYT?

2024-09-19 05:08 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "value": "Success"
Yeah sounds good

2024-09-19 06:06 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
There's currently a bug with this approach, discussed in https://getport.slack.com/archives/C07ALEX911V/p1726725961241489?thread_ts=1726507073.753509&cid=C07ALEX911V
If the bug is fixed, no need to change. Otherwise, we should separate the "create blueprint" and "Add mirror property"

2024-09-19 06:08 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +      "path": "pullRequest.leadTimeHours"
In the Github documentation the name of the field is `lead_time_days`
We should be consistent.
Also, I suggest adding here a note to make sure you followed the Github examples and that you defined this field. IF you havene't, LINK to where you can do it

2024-09-19 06:13 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +    }
According to the Github guide, I need to create a calculation property on the lead time. I followed the example here
https://pr-1594.d2ngvl90zqbob8.amplifyapp.com/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples#map-repositories-and-pull-requests

But then I can't create an aggregation property of it. I think we discussed it.
What should be the approach here? the Github guide should be updated as well on how to create the required fields

2024-09-19 06:18 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +```yaml showLineNumbers
I did this step, and tested the mapping. I got this
![CleanShot 2024-09-19 at 09 15 39](https://github.com/user-attachments/assets/5c0d084c-d361-4183-bf09-2a1f44049c94)

It looks like it takes "Open" PR and considers it a successful deployment (without "Created at"). Not sure it's expected

2024-09-19 06:23 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +  "properties": {
@kodjomiles it a bit weird to copy paste it as I have additional properties. Maybe there's a better way?

2024-09-19 06:23 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +  "relations": {
@kodjomiles Same here, is there a better approach to make it copy-paste? not a must

2024-09-19 06:24 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +```yaml showLineNumbers
@kodjomiles it took me a few seconds to understand where to paste it, and even then since yaml is sensitive it didn't work well.
Can you try to improve it, or at least show a screenshot to clarify where to put it?

2024-09-19 06:24 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +       value: .summary
```suggestion
       value: .service.summary
```

2024-09-19 06:25 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<summary><b>Complete service blueprint</b></summary>
@kodjomiles I think we discussed that we should put here only the additional properties we want to add, and not all the blueprint. No?

2024-09-19 06:36 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +{
@kodjomiles to simplify copy-paste maybe we can remove in all these examples of metrics the surrounding curly brace?

I clicked on copy, pasted it under aggregation properties - and then had to manually delete the surrounding braces

2024-09-19 10:44 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
this links seems to be broken

2024-09-19 10:49 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +<summary><b>Complete service blueprint</b></summary>
no please, we defined the additional properties and provided the complete setup once we were done to give the client a high overview

2024-09-19 10:52 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +      "path": "pullRequest.leadTimeHours"
well now if they follow the link, it's a calculation property that can not be mirrored, that's why it's left out for now, I changed it to hours because that's what I saw in the notion docs, Let me change to days then. consistency across is great

2024-09-19 10:53 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
@kodjomiles I think you are not in this channel, but currently you can't copy paste the code you added. I confirmed the bug is fixed.

2024-09-19 10:54 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +    }
Yes please, the GitHub guide needs to be updated now to configure lead time as a property and not as a calculation property with the necessary mapping config added. I had that mapping in the code earlier but you suggested we remove it and update the GitHub docs instead

2024-09-19 10:56 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<summary><b>Complete service blueprint</b></summary>
@kodjomiles I'm just concerned it will override other stuff the customer added.
Maybe we can remove it completely and just let him go through each metric? what do you think?

2024-09-19 11:06 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +      "path": "pullRequest.leadTimeHours"
@Matanga1-2 should I change this to days ??

2024-09-19 11:10 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +```yaml showLineNumbers
@Matanga1-2 I am certain that we need to add an additional filter to the query. since this is being tracked when the pr is merged then we need to add that the status should be merged too, so that we can have the deployment being created at mergedAt

2024-09-19 11:58 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +<summary><b>Complete service blueprint</b></summary>
okay

2024-09-19 12:24 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
but you can add them separately ?

2024-09-19 12:25 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
How come it worked for me ?

2024-09-19 12:29 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +    "leadTimeHours": {
Separately it works. 
Try this:
Copy the blueprint from the doc
Change the relation name to one that doesn't exists (eg, pullRequest2)
Change the mirror property to that relation as well

See if you see an error

2024-09-20 06:25 UTC, Matanga1-2 requested changes

2024-09-20 06:25 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +     "property": "leadTimeDays",
```suggestion
     "property": "leadTimeHours",
```

Right? you changed the original prop name in the blueprint

2024-09-20 06:25 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +
@kodjomiles consider adding a note here explaining that at this point you can already go to each service and see the aggregation data. HOWEVER, it will be based on new data only (and you can link to the AGGREGATION PROP page to more information on how it works)

2024-09-20 06:25 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +To sync incidents from **PagerDuty**, follow the steps in the [PagerDuty guide](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty). The guide prov
@kodjomiles I believe the correct way to link to docs is without the base domain
```suggestion
To sync incidents from **PagerDuty**, follow the steps in the [PagerDuty guide](/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty). The guide provides detailed steps for setting up integrations to track incidents related to deployments.
```

2024-09-20 06:25 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +                 url: .self
@kodjomiles Aren't we missing with the definition of how to populate recoveryTime field?

2024-09-20 10:35 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +     "property": "leadTimeDays",
yeah

2024-09-20 10:57 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +                 url: .self
You are right, resolvedAt and recoveryTime, thought we had covered it earlier

2024-09-21 20:01 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="df" label="Deployment Frequency">
@kodjomiles I'm not sure it's entirely clear WHERE to add the aggregation/calcluation properties. You wrote above "service" but it wasn't `service`, rather just the text.

Consider explaining here how to actually reach the data model, that you need to select the service, update the JSON, and add it within the aggregation/calculation..
I think adding a screenshot here could help

2024-09-21 20:02 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
@kodjomiles I didn't recognize this property. In my env I don't have it. Why do we need it?
The way I see it each incident should be counted

2024-09-21 20:08 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<summary><b>Setup Change Lead Time Widget</b></summary>
@kodjomiles there are few discrepencies here:

1. When I set it up, I see a different popup
![CleanShot 2024-09-21 at 23 06 28@2x](https://github.com/user-attachments/assets/94e4cb76-6cc4-4f18-a138-b2a2cb1b6c21)
2. I can't select entity, if we aim to show the dashboard per entity you should specify how to filter only a specific entity.
3. The title is "monthly", while in section 7 you with (e.g., days) and the screenshot you write "hour". Make sure the timeframe is clear and be opinionated (instead of e.g., we should write what you expect the user to do)

2024-09-21 20:11 UTC, Matanga1-2 requested changes
We are getting there! left few last comments

2024-09-24 13:22 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
true

2024-09-24 13:26 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
CFR is calculated based on the percentage of failed deployments that lead to incidents or issues that were eventually resolved.
counting only resolved incidents provides clarity on how many deployment-related incidents have been addressed, which is key to understanding recovery efforts and not just the raw number of incidents. right ?? and the unresolved incidents would indicate that the failures are still in progress, which wouldn’t accurately reflect the **recovery** or **success rate** of deployments.

2024-09-24 13:28 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
If I include **unresolved incidents**, doesn't that mean that the CFR might inflate because ongoing incidents don’t reflect the true end state (resolved or unresolved) of the failure.
Resolved incidents show how many incidents were fully dealt with and would be directly related to the overall health of the system, which is what CFR aims to measure, correct me if I am wrong

2024-09-24 13:50 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="df" label="Deployment Frequency">
I have added a tip on how to get there. Look at it and let me know if I should still add a screenshot

2024-09-24 19:02 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="df" label="Deployment Frequency">
@kodjomiles I don't see the tip, can you point me in the right direction?

2024-09-24 19:03 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
@kodjomiles you're not wrong but when calculating CFR you should count as you mentioned all failed deployments. If an incident is not resolved, you can still consider it a failed deployment (it's still an incident, just an ongoing one).
So the way I see it in this guide each incident is considered a failed deployment

2024-09-25 09:29 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="df" label="Deployment Frequency">
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/64d372ff-68c7-41ba-8225-53b70fbbf417">
right here

2024-09-25 09:31 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="df" label="Deployment Frequency">
Missed it, perfect

2024-09-25 09:32 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +          "property": "incidentType",
okay let me modify it then

2024-09-25 11:00 UTC, Matanga1-2 approved these changes

2024-09-25 12:40 UTC, hadar-co requested changes

2024-09-25 12:40 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +DORA Metrics are a set of key performance indicators
```suggestion

DORA Metrics are a set of key performance indicators
```

2024-09-25 12:40 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +- Access a GitHub repository (e.g., port-dora-metrics) to sync your pull requests or deployments. You can follow the [GitHub integration guide](/build-your-software-catalog/sync-data-to-catalog/git/g
If a user completes the onboarding using GitHub, they will already have a repo that is synced with Port.

Instead of this line, let's split it to 2 lines:
The first should be something like "While this guide demonstrates an implementation using GitHub, other Git providers can be used as well."
And the second should be something like "Access to a GitHub repository that is connected to Port via the onboarding process."

2024-09-25 12:40 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +Port does not offer a built-in solution specifically tailored for monorepos.
```suggestion
```

2024-09-25 12:40 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +However, by using **custom integrations**, you can track services or components within a monorepo effectively.
```suggestion
By using **custom integrations**, you can effectively track services or components within a monorepo.
```

2024-09-25 12:40 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +2. Click on the `+ New` button in the left sidebar
Add a period at the end of each item in a list

2024-09-25 13:04 UTC, hadar-co approved these changes

2024-09-27 10:12 UTC, PeyGis requested changes
left some comment on the mapping for the github releases

2024-09-27 10:12 UTC, PeyGis commented on docs/guides/all/setup-dora-metrics.md
> +
Why is the gitlab releases and tags using the same mapping as the Deployment via Workflow Runs?

2024-09-27 10:12 UTC, PeyGis commented on docs/guides/all/setup-dora-metrics.md
> +
https://pr-1619.d2ngvl90zqbob8.amplifyapp.com/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples#map-repositories-repository-releases-and-tags

2024-09-27 11:31 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +
It's supposed to be for the release tags not the workflow, it's a mistake let me replace it

2024-09-27 13:16 UTC, PeyGis approved these changes
looks good

2024-09-27 13:18 UTC, merged