Add cloud resources for Datadog integration
port-labs/port-docs pull request #1604
Opened 2024-09-20 17:54 UTC by lordsarcastic

# Description
Added a guide on how to ingest cloud resources using Datadog integration

## Added docs pages
- Ingest cloud resources using Datadog (`docs/guides/all/ingest-cloud-resources-using-datadog.md`)

2024-09-25 09:45 UTC, PeyGis requested changes
Looks great. Please change the image. Try to show the important properties such as platform, cpu core, source etc

2024-09-25 09:45 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-datadog.md
> +<summary><b>Datadog Cloud Resource Blueprint (Click to expand</b></summary>
```suggestion
<summary><b>Datadog Cloud Resource Blueprint (Click to expand)</b></summary>
```

2024-09-25 15:05 UTC, PeyGis approved these changes
LGTM

2024-09-27 11:12 UTC, PeyGis requested changes
Let's make the guide appear on the all guides page and make it searchable by tags or title

To make it appear, you need to modify this file
src/components/guides-section/consts.js
and include an entry such as
    {
        title: "Sync Service Entities to Incident IO",
        description: "Create a GitHub action that syncs service entities to Incident IO catalog",
        tags: ["Incident management","GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/sync-service-entities-to-incident-io",
    }

2024-09-27 11:56 UTC, PeyGis approved these changes
nice work

2024-09-29 08:16 UTC, hadar-co commented on docs/guides/all/ingest-cloud-resources-using-datadog.md
> +We will be making use of the `hosts` kind in Port's Datadog integration which provides information on hosts existing on the cloud providers we have configured. So far, we are only interested in hosts
```suggestion
We will be making use of the `hosts` kind in Port's Datadog integration which provides information on hosts existing on the cloud providers we have configured. For this example, we are only interested in hosts with `gcp`, `aws`, and `azure` in the `sources` property.
```

2024-09-29 08:16 UTC, hadar-co commented on docs/guides/all/ingest-cloud-resources-using-datadog.md
> +4. Next, click on resync and watch your cloud resources from Datadog being ingested:
```suggestion
4. Finally, click `resync`. Your cloud resources from Datadog should now be ingested:
```

2024-09-29 08:28 UTC, merged