Sync port services to incident io
port-labs/port-docs pull request #1617
Opened 2024-09-26 19:29 UTC by PeyGis

# Description

A guide to sync services in Port to incident IO

## Added docs pages

`docs/guides/all/sync-service-entities-to-incident-io.md`

## Updated docs pages

docs/integrations-index.md
src/components/guides-section/consts.js

2024-09-29 08:46 UTC, Matanga1-2 requested changes

2024-09-29 10:21 UTC, hadar-co requested changes

2024-09-29 10:21 UTC, hadar-co commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +:::info Prerequisites
no need for an admonition here, the "Prerequisites" header is enough.

2024-09-29 10:21 UTC, hadar-co commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +## See Results
```suggestion
## Results
```

2024-09-29 10:21 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        logos: ["GitHub"],
no need to add another logo, if we added one for every tech product the filter list would be way too long..
@PeyGis I resolved the merge conflict and made a small change in consts.js

2024-09-30 14:53 UTC, PeyGis commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +      - name: Get Port Access Token
Yes, when using Port's github-app, you don't need to get the access token since that's encapsulated when making calls to Port's API. But besides that, we don't have support for it yet

2024-09-30 16:51 UTC, hadar-co approved these changes

2024-09-30 16:51 UTC, hadar-co commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +This guide helps you set up a GitHub workflow that periodically syncs service entities from Port into incident.io's catalog, ensuring better visibility and context for your services during incident m
```suggestion
This guide demonstrates how to set up a GitHub workflow that periodically syncs service entities from Port into incident.io's catalog, ensuring better visibility and context for your services during incident management.
```

2024-09-30 16:57 UTC, hadar-co approved these changes

2024-09-30 16:57 UTC, hadar-co commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +- Port properties such as aggregated and mirror properties cannot be directly synced to incident.io
```suggestion
- Port property types such as aggregation and mirror properties cannot be directly synced to incident.io.
```

2024-09-30 16:57 UTC, hadar-co commented on docs/guides/all/sync-service-entities-to-incident-io.md
> +- Incident IO can currently ingest up to **50,000 catalog items**, so keep this limit in mind when scaling your service catalog.
```suggestion
- incident.io can currently ingest up to **50,000 catalog items**, so keep this limit in mind when scaling your service catalog.
```

2024-09-30 17:22 UTC, hadar-co approved these changes

2024-09-30 17:30 UTC, Matanga1-2 approved these changes

2024-09-30 17:51 UTC, merged