PORT-10619 Restructure Gitlab Integration Docs
port-labs/port-docs pull request #1619
Opened 2024-09-27 04:50 UTC by kodjomiles

# Description

Changed the gitlab integration guide to use new integration guide structure 

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Gitlab Into (/build-your-software-catalog/sync-data-to-catalog/git/gitlab)
- Gitlab Installation (/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation)

2024-09-27 11:03 UTC, PeyGis approved these changes
LGTM

2024-09-29 10:31 UTC, hadar-co requested changes

2024-09-29 10:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
> -### Ingest files from your repositories
This is an important capability, it should not be removed. Please move it under the capabilities section with its own sub-header.

2024-09-29 10:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
>  :::note Prerequisites
Change to a header instead of an admonition.

2024-09-30 11:44 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
> -### Ingest files from your repositories
Just to confirm is it just the Ingest files from repo I should add or the other bit's that follows it are all to be added to capabilities, from where I see it, the data seems to be mapping configurations which has already been covered..
Is there something I am missing here ?

2024-10-05 16:03 UTC, hadar-co approved these changes

2024-10-05 16:08 UTC, merged