PORT-10620 Restructure Pagerduty Integration Docs
port-labs/port-docs pull request #1620
Opened 2024-09-27 14:08 UTC by kodjomiles

# Description

Restructure the Pagerduty integration guide to follow new integration docs structure. 

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- PagerDuty Integration Docs Page(`/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty`)

2024-09-27 16:14 UTC, PeyGis requested changes
looks great. One of the section that needs to be removed is the let's test it section. see below.
from the new integration template
```
# Examples

<!-- Make sure to add examples of supported blueprints and mappings -->
<!--If there are 5 or more examples, create a new page for the examples and link to it here. -->

To view and test the integration's mapping against examples of the third-party API responses, use the jq playground in your [data sources page](https://app.getport.io/settings/data-sources). Find the integration in the list of data sources and click on it to open the playground.
```


<img width="1298" alt="Screenshot 2024-09-27 at 4 13 24 PM" src="https://github.com/user-attachments/assets/426df665-69b2-42fe-8b6e-fa26fac36912">

2024-09-27 16:14 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
> +<Prerequisites />
I think the prerequisites should come under the installation section

2024-09-30 10:14 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
> +<Prerequisites />
done

2024-10-08 15:18 UTC, PeyGis approved these changes
LGTM

2024-10-10 11:22 UTC, hadar-co requested changes

2024-10-10 11:22 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
> +:::info Ingest data into Port
we can remove this admonition, like in other integrations

2024-10-10 12:04 UTC, hadar-co approved these changes

2024-10-10 12:04 UTC, merged