Orca - webhook example with script
port-labs/port-docs pull request #1625
Opened 2024-10-01 04:14 UTC by lordsarcastic

# Description
Implemented a webhook example with Python script to ingest Orca alerts into Port

## Added docs pages

Please also include the path for the added docs

- Orca Security (`docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md`)

2024-10-01 12:49 UTC, Matanga1-2 requested changes
Added minor comments on text

2024-10-01 12:49 UTC, Matanga1-2 commented on src/components/guides-section/consts.js
> +        title: "Ingest historical and realtime vulnerability alerts in Orca Security",
Maybe "Ingest vulnerability alerts from Orca Security"?

2024-10-01 12:49 UTC, Matanga1-2 commented on src/components/guides-section/consts.js
> +        description: "Ingest both historical and realtime alerts on vulnerabilites in Orca Security.",
Maybe "Ingest vulnerability alerts from Orca Security using a custom webhook integration"?

2024-10-01 12:49 UTC, Matanga1-2 commented on src/components/guides-section/consts.js
> +        tags: ["AppSec"],
Also webhook?

2024-10-01 12:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +description: Ingest both historical and realtime alerts on vulnerabilites in Orca Security.
Match to the title below based on the other comment

2024-10-01 12:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +# Ingest historical and realtime vulnerability alerts in Orca Security
Match to the suggested title

2024-10-01 12:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +  "mirrorProperties": {},
Making sure the existing data in Orca doesn't contain the service where the alert found?

2024-10-01 12:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +- `OCTA_SECURITY_API_TOKEN` - Get that by following the steps below
OCTA? not ORCA?

2024-10-01 12:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +- `OCTA_SECURITY_API_URL` - The host URL of your Orca Security dashboard. See the below table for which URL to use depending on your region:
OCTA? not ORCA?

2024-10-01 13:01 UTC, PeyGis requested changes
left some few comments as well

2024-10-01 13:01 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +<img src='/img/guides/createOrcaSecurityVulnerabilityAlertWebhook.png' border='1px' />
Can we also change the icon to show the more interesting props such as status, source etc

2024-10-01 13:01 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +        "description": "Current status of the vulnerability on assets"
can this also be an enum?

2024-10-08 10:17 UTC, lordsarcastic commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      },
I'm not entirely certain of all the possible values so...

2024-10-08 10:17 UTC, lordsarcastic commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +        "description": "Current status of the vulnerability on assets"
Same as above

2024-10-08 10:22 UTC, lordsarcastic commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +  "mirrorProperties": {},
There isn't any explicit information on the service the alert is attached to. It is up to the user to know how to generate the service name from the information provided by Orca.

2024-10-08 13:41 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      },
<img width="321" alt="Screenshot 2024-10-08 at 1 40 42 PM" src="https://github.com/user-attachments/assets/97e06580-bb70-4e52-9bc3-e2b8d606cba0">

These are the severities I see in Orca, which is consistent with all the CVE standards. Please update it to be an enum

2024-10-08 13:52 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      },
<img width="435" alt="Screenshot 2024-10-08 at 1 48 48 PM" src="https://github.com/user-attachments/assets/2cd95096-97f7-42b9-b87b-89b95f71782d">
Also for alerts, these are the severities

2024-10-08 13:52 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      },
<img width="435" alt="Screenshot 2024-10-08 at 1 48 48 PM" src="https://github.com/user-attachments/assets/2cd95096-97f7-42b9-b87b-89b95f71782d">
Also for alerts, these are the severities

2024-10-08 14:09 UTC, PeyGis commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      },
@lordsarcastic actually these enum: low,medium,critical,high and informational are supposed to be under risk level instead of severity

2024-10-09 05:47 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +  "mirrorProperties": {},
@lordsarcastic in the original mapping I added to the task we had this mapping to service & repo
![CleanShot 2024-10-09 at 08 47 24@2x](https://github.com/user-attachments/assets/92a1fa83-1e60-4815-a749-f813a50a9d7e)

Why can't we use it?

2024-10-09 05:49 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +<summary><b> Orca Security Alert webhook blueprint (Click to expand)</b></summary>
"webhook"?
Why not just "Orca Security Alert blueprint"?

2024-10-09 05:51 UTC, Matanga1-2 requested changes

2024-10-09 05:51 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +      "relations": {}
Same as above the original mapping I shared extracted the service & repo as relation

2024-10-09 13:29 UTC, lordsarcastic commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +<summary><b> Orca Security Alert webhook blueprint (Click to expand)</b></summary>
This is the blueprint for the webhook configuration

2024-10-09 13:30 UTC, Matanga1-2 commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +<summary><b> Orca Security Alert webhook blueprint (Click to expand)</b></summary>
Got it wasn't sure

2024-10-09 20:28 UTC, Matanga1-2 approved these changes

2024-10-10 10:15 UTC, PeyGis approved these changes
lgtm

2024-10-10 10:41 UTC, hadar-co requested changes

2024-10-10 10:41 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        logos: ["AppSec", "Webhook"],
```suggestion
        logos: ["Webhook"],
```

2024-10-10 10:41 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        link: "/build-your-software-catalog/custom-integration/webhook/examples/orca-security"
all guides should reside under /guides/all/

2024-10-10 10:41 UTC, hadar-co commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +This guide shows you how to ingest both historical and realtime alerts in Orca Security. To do this, you will use Port's webhook feature (for realtime alerts) and/or a Python script (for historical d
```suggestion
This guide demonstrates how to ingest both historical and realtime alerts from Orca Security into Port.  
To do this, we will use Port's webhook feature (for realtime alerts) and/or a Python script (for historical data).
```

2024-10-10 10:41 UTC, hadar-co commented on docs/build-your-software-catalog/custom-integration/webhook/examples/orca-security.md
> +6. Click on "Save"
```suggestion
6. Click on "Save".
```

2024-10-10 10:48 UTC, lordsarcastic commented on src/components/guides-section/consts.js
> +        link: "/build-your-software-catalog/custom-integration/webhook/examples/orca-security"
I wanted it to show up in both the guides and the webhook examples section. WDYT?

2024-10-10 10:49 UTC, lordsarcastic commented on src/components/guides-section/consts.js
> +        link: "/build-your-software-catalog/custom-integration/webhook/examples/orca-security"
I wanted it to show up in both the guides and the webhook examples section. WDYT?

2024-10-10 11:01 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        link: "/build-your-software-catalog/custom-integration/webhook/examples/orca-security"
I see:)
The guides itself should still reside under /guides/all , you can add a link to it in the webhook examples section

2024-10-10 11:04 UTC, lordsarcastic commented on src/components/guides-section/consts.js
> +        link: "/build-your-software-catalog/custom-integration/webhook/examples/orca-security"
Okay

2024-10-10 11:34 UTC, hadar-co approved these changes

2024-10-10 11:34 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        tags: ["Webhook"],
```suggestion
        tags: ["AppSec", "Webhook"],
```

2024-10-10 11:43 UTC, merged