PORT 10426 New Relic Add Cloud Resources
port-labs/port-docs pull request #1629
Opened 2024-10-02 13:56 UTC by kodjomiles

# Description

Added new guide for new relic's additon of cloud resources
## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Guide (`/guides/all/ingest-cloud-resources-using-newrelic`)

2024-10-03 16:13 UTC, PeyGis requested changes
looks good overall. left some suggestions

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +## Ingesting Cloud Resources into Port
```suggestion
## Ingesting cloud resources into Port
```

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +
```suggestion
We will utilize the `entity` kind in Port's New Relic integration, which provides information on entities monitored in New Relic. Entities are ingested based on their respective infrastructure integration type.
```

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +<summary><b>Some cloud resources infrastructure integration types</b></summary>
```suggestion
<summary><b>Examples of cloud resources infrastructure integration types</b></summary>

```

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +## Data Model Setup
```suggestion
## Data model setup
```

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +1. Creating the Blueprint Configuration
```suggestion
1. Creating the blueprint configuration
```

2024-10-03 16:13 UTC, PeyGis commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +2. Configuring the Integration Mapping
```suggestion
2. Configuring the integration mapping
```

2024-10-07 07:58 UTC, PeyGis approved these changes

2024-10-07 11:08 UTC, hadar-co requested changes

2024-10-07 11:08 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        logos: ["NewRelic"],
```suggestion
        logos: ["New Relic"],
```

2024-10-07 11:08 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        description: "Ingest any cloud resources from your New Relic environment into Port",
```suggestion
        description: "Ingest cloud resources from your New Relic environment into Port",
```

2024-10-07 11:08 UTC, hadar-co commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +<img src="/img/guides/newRelicIngestedData.png" />
```suggestion
<img src="/img/guides/newRelicIngestedData.png" border='1px' />
```

2024-10-07 11:08 UTC, hadar-co commented on docs/guides/all/ingest-cloud-resources-using-newrelic.md
> +:::note Follow up to date
```suggestion
:::note Latest information
```

2024-10-07 11:49 UTC, hadar-co approved these changes

2024-10-07 11:52 UTC, merged