PORT-10735 Datadog Integration Docs
port-labs/port-docs pull request #1633
Opened 2024-10-03 14:26 UTC by kodjomiles

# Description

Restructure the Datadog integration guide to follow new integration docs structure. 

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Datadog Integration Docs Page(`/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog`)

2024-10-08 15:22 UTC, PeyGis approved these changes
LGTM

2024-10-09 06:51 UTC, hadar-co requested changes

2024-10-09 06:51 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
> +Port's Datadog integration allows you to import `monitors` (also known as alerts), `services`, `slos`, `sloHistory`, and `serviceMetrics` from your Datadog account into Port, according to your mappin
```suggestion
Port's Datadog integration allows you to model Datadog resources in Port and ingest data into them.
```

2024-10-09 06:51 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
> +<TabItem value="one-time-ci" label="One-time (CI)">
```suggestion
<TabItem value="one-time-ci" label="Scheduled (CI)">
```

2024-10-09 06:51 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
> +- For relevant guides and examples, see the [guides section](https://docs.getport.io/guides?tags=Datadog).
```suggestion
For relevant guides and examples, see the [guides section](https://docs.getport.io/guides?tags=Datadog).
```

2024-10-09 10:43 UTC, hadar-co approved these changes

2024-10-09 11:20 UTC, merged