PORT-10679 Extend deployments docs with Gitlab & Azure DevOps
port-labs/port-docs pull request #1640
Opened 2024-10-08 02:10 UTC by kodjomiles

# Description
Extending the deployment strategies to cover other git providers (Azure and Gitlab)

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Dora Metrics Guide (`/guides/all/setup-dora-metrics`)

2024-10-08 08:51 UTC, Matanga1-2 approved these changes
Looks good, make sure to add @hadar-co as reviewer

2024-10-08 08:55 UTC, kodjomiles commented
@Matanga1-2 I will but I want to update the gitlab docs and the azure devops docs with the leadTime for pr first before this is merged.. else we will find some misleading information about the leadTime ... it's still a calculation property on the gitlab docs and is not mentioned anywhere on azure. I will open a task for it shortly and implement them ASAP then the review can continue

2024-10-10 14:16 UTC, hadar-co requested changes

2024-10-10 14:16 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
>  ## Tracking Deployment
```suggestion
## Tracking deployments
```

2024-10-10 14:17 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
> +  Below is how the deployment tracking can be done in GitHub using the PR merge strategy:
@kodjomiles please change this phrasing in all instances, there quite a few

2024-10-10 15:30 UTC, PeyGis approved these changes

2024-10-10 20:19 UTC, hadar-co approved these changes

2024-10-10 20:20 UTC, merged