Port 10412 automating self service actions approvals guides
port-labs/port-docs pull request #1658
Opened 2024-10-15 08:52 UTC by shariff-6

# Description

This pull request introduces new documentation for automating the approval of Self-Service Actions (SSAs), specifically focusing on how to automatically approve permission requests under certain conditions. Additionally, updates have been made to the guide section to reflect this new documentation.

## Added docs pages

- Automating Self Service Action Approval (`/guides/all/automatically-approve-action-using-automation`)

## Updated docs pages

- src/components/guides-section/consts.js: Added a new guide link for "Automatically Approving Actions Using Automation."

## Summary of Changes

- Created a new guide explaining how to set up automation for automatically approving actions.
- Updated the available guides section to include the new guide with relevant details and tags.

2024-10-15 09:17 UTC, PeyGis requested changes
Looks great overall. Please go over my comments and apply the fixes

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +In this guide, we'll walk you through the process of setting up an automated approval system for Self-Service Actions (SSAs). We'll use a specific example of a permissions request system that you can
```suggestion
In this guide, we will walk you through the process of setting up an automated approval system for Self-Service Actions (SSAs). We will use a specific example of a developer requesting a cloud resource, such as a database, with a certain level of permissions.
```

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +- Permissions to create and edit Self-Service Actions and Automations
replace all instances of Self-Service Actions to self service actions and Automations to automations

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +  "title": "Self Service - Request Permissions",
change title to Request Database Access

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +    "userInputs": {
add another string input for `reason` we want to understand the reason for requesting the permission

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +    "url": "https://hooks.slack.com/services/xyz",
add a comment that they need to change the url of the slack hook to their own

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +      "text": "\nHello from Port :slightly_smiling_face:\n\n:white_circle:   Read more about Slack wehooks <https://api.slack.com/messaging/webhooks%7Chere.>\n\n:white_circle:   Read more about forma
Change the text of the body to someone more tailored to the guide: hello from Port, a {user} from your organization has requested for access to a database. the reason is {reason}

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +Now that we have our SSA, let's create an automation to automatically approve certain requests:
use the full self service action instead of SSA

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +  "title": "Auto Approve",
Auto Approve Cloud Resource Access

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +
Guides are meant to be short so let's delete this section

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +:::
delete

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +By leveraging Port's automation capabilities, we've created an efficient, secure workflow that reduces manual overhead for permission requests. This system streamlines the approval process for **Read
```suggestion
By leveraging Port's automation capabilities, we have created an efficient, secure workflow that reduces manual overhead for permission requests. This system streamlines the approval process for **ReadOnly** permissions while ensuring that **ReadWrite** requests still go through manual review.
```

2024-10-15 09:17 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +We're excited to see how you'll use this feature to improve your team's productivity and streamline your permission management processes!
the conclusion above is okay so let's remove this

2024-10-15 13:04 UTC, shariff-6 commented on docs/guides/all/automatically-approve-action-using-automation.md
> +      "text": "hello from Port :slightly_smiling_face:, a {user} from your organization has requested for access to a database. the reason{reason}"
Should have seen this, thanks 😅 . Updating

2024-10-15 17:29 UTC, PeyGis requested changes
a few more comments

2024-10-15 17:29 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +    "operation": "CREATE",
Just realized that the action json is quite lengthy. Let's wrap in inside a clickable button tag like

```
 <details>
 <summary> Request Database Access (click to expand) </summary>
 json content
 </details>
```

<img width="1113" alt="Screenshot 2024-10-15 at 5 28 03 PM" src="https://github.com/user-attachments/assets/6915baf5-f599-49a2-a1a4-7f88d28d1814">

2024-10-15 17:29 UTC, PeyGis commented on docs/guides/all/automatically-approve-action-using-automation.md
> +  "invocationMethod": {
Just realized that the action json is quite lengthy. Let's wrap in inside a clickable button tag like

```
 <details>
 <summary> Automation definition auto approve cloud resource (click to expand) </summary>
 json content
 </details>
```

2024-10-15 17:54 UTC, PeyGis approved these changes
LGTM

2024-10-16 07:01 UTC, hadar-co requested changes

2024-10-16 07:01 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        logos: ["Actions", "Automations"],
```suggestion
        logos: ["Slack"],
```

2024-10-16 10:05 UTC, hadar-co approved these changes

2024-10-16 10:05 UTC, hadar-co commented on docs/guides/all/automatically-approve-action-using-automation.md
> +1. In the [Automations page](https://app.getport.io/settings/automations), click on **+ Automation**.
```suggestion
1. In the [Automations page](https://app.getport.io/settings/automations), click on `+ Automation`.
```

2024-10-16 10:05 UTC, hadar-co commented on docs/guides/all/automatically-approve-action-using-automation.md
> +1. Navigate to the [Self-service](https://app.getport.io/self-serve) section in your Port dashboard.
```suggestion
1. Navigate to the [Self-service](https://app.getport.io/self-serve) page in your portal.
```

2024-10-16 10:05 UTC, hadar-co commented on docs/guides/all/automatically-approve-action-using-automation.md
> +2. Click on "+ Action" to create a new self service action.
```suggestion
2. Click on `+ Action` to create a new self service action.
```

2024-10-16 10:48 UTC, merged