PORT-10848 Guide - Working Agreements (TF)
port-labs/port-docs pull request #1659
Opened 2024-10-15 09:11 UTC by kodjomiles

# Description

A new guide that covers creating **working agreements** that helps teams establish shared understandings of processes and standards, enhancing collaboration, promoting accountability,  Measuring PR standards for assessing code quality,
review processes, and team efficiency. leading to overall workflow improvement

## Added docs pages
- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- PR Metrics Guide (`/guides/all/working_agreements_and_measuring_pr_standards`)

2024-10-20 19:06 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +**working agreements** help teams establish shared understandings of processes and standards, enhancing collaboration, promoting accountability,
```suggestion
**working agreements** help teams establish shared understandings of processes and standards while enhancing collaboration.
```

2024-10-20 19:06 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +**working agreements** help teams establish shared understandings of processes and standards, enhancing collaboration, promoting accountability,
I think we can make it more concise

2024-10-20 19:07 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +facilitating onboarding, and improving efficiency.**pull requests (PRs)** are a critical part of the workflow. Measuring PR standards is essential for assessing code quality,
```suggestion
**Pull requests (PRs)** are a critical part of the workflow. Measuring PR standards is essential for assessing code quality,
```

I think measuring PR standards is essential to improve efficiency metrics and make sure teams are working within defined standards.

2024-10-20 19:08 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +teams can monitor adherence to best practices and continuously improve their workflows.
We can make this entire paragraph more concise

2024-10-20 19:08 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and pr checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
PR? (not pr)

2024-10-20 19:10 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +To measure PR standards effectively, add aggregation properties on the **service** and **organization** blueprints.
```suggestion
To measure PR standards effectively, add aggregation properties on the **service**  blueprint.
```

You mention organization later, and it's not clear the user even has organization blueprint so I think we can remove it from this sentence

2024-10-20 19:16 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +## Implementation
Do you think it might make more sense to add all the metrics in one snipper?
One snipper for scorecard, one for mapping, and one for the properties.

The guide feels complicated where it can easily be a copy-paste one. WDYT?

2024-10-20 19:17 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +  defaultValue="totalAverageCommitsPerPr"
What does "Total average" means? isn't it "average"?

2024-10-20 19:18 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +By leveraging Port's Dashboards, you can create custom dashboards to track the pr metrics and monitor your team's performance over time.
You can also add a simple visualization that group the scorecards by team/service and show the scored (without special aggregation, just a type of widget)

2024-10-20 19:19 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src="/img/guides/prMetricsDashboardComp.png" />
This image is nice, but ideally, you can add 1-2 more images showing how it looks like. specifically the widget that shows group by service/team (my comment above), and maybe something like average lines of codes

2024-10-21 12:08 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +teams can monitor adherence to best practices and continuously improve their workflows.
okay

2024-10-21 23:32 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +## Implementation
I think doing that would not leave much of a choice for the user, but to use all these metrics weather they like it or not, it it also doesn't explicitly explain what each json or mapping config is doing. I think is best if each agreement gets a spot light

2024-10-21 23:36 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +  defaultValue="totalAverageCommitsPerPr"
Yeah I think total being there should be removed

2024-10-21 23:39 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +By leveraging Port's Dashboards, you can create custom dashboards to track the pr metrics and monitor your team's performance over time.
I don't understand this, if you could elaborate on this a bit more

2024-10-21 23:43 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src="/img/guides/prMetricsDashboardComp.png" />
like this ? 
<img width="1565" alt="image" src="https://github.com/user-attachments/assets/893115ae-a5cc-45b8-965f-a8bd53fed457">

2024-10-22 05:11 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src="/img/guides/prMetricsDashboardComp.png" />
Perfect

2024-10-22 05:13 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +By leveraging Port's Dashboards, you can create custom dashboards to track the pr metrics and monitor your team's performance over time.
Assuming you have a scorecard score for each service, and each service has on owning team, you can create a table view of all services groups by team and showing average of the teams services scorecard. It's a simple widget but powerful

2024-10-30 08:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +## Implementation
OK

2024-10-30 08:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +By leveraging Port's Dashboards, you can create custom dashboards to track the pr metrics and monitor your team's performance over time.
@kodjomiles ?

2024-10-30 09:00 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +By leveraging Port's Dashboards, you can create custom dashboards to track the pr metrics and monitor your team's performance over time.
okay I will add this so we can merge

2024-10-31 07:54 UTC, Matanga1-2 requested changes

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
maybe the link can lead to a more meaningful page? like the "socrecards overview" page"? or a specific pull request scorecards?

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<h4> Scorecard Definition </h4>
@kodjomiles you explain here each scorecard, but its' unclear what to do with it.
MAybe you should add a section explaining that you can go to your pull request blueprint, click on add scorecard, and paste each JSON.
Also share screenshot

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to the **service** blueprint:
@kodjomiles maybe simila to the DORA metric guide explain how to add aggregation prop?

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to the **service** and **organization** blueprint:
why mentioning "organization" here? we didn't instruct to have or add such blueprint

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +First, ensure you have a calculation property `totalLocChanged` on the **pull request** blueprint:
@kodjomiles why not moving this step above to where you define the scorecard? less context switching

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to calculate the total average commits per PR:
@kodjomiles are these any difference from the service ones?

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +    "title": "Total Average Commits Per PR",
Total average?

2024-10-31 07:54 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +# Implement working agreements and measure pull request standards
I'm missing meaningful screenshots showing both how a PR scorecard looks like, and how an example dashboard looks like (you can take the "scorecard overview" from the demo for example)

2024-11-01 01:16 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
I don't see any scorecard overview page can you point me to the right page

2024-11-01 01:51 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to the **service** and **organization** blueprint:
it was in the notion documentation to aggregate on service and organization

2024-11-01 01:51 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +First, ensure you have a calculation property `totalLocChanged` on the **pull request** blueprint:
okay sounds good

2024-11-01 02:12 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to calculate the total average commits per PR:
not very significant. should I remove them ?

2024-11-01 05:17 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
You're right it disappeared. 
Look at https://demo.getport.io/engineering_overview all the way down to the bottom for a similar example.

2024-11-01 05:18 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to the **service** and **organization** blueprint:
Yes but earlier you mentioned that the aggregations are on service and can be added to higehr hierarchies as well (which is great)

Here it's out of context, the user don't know what is this blueprint

2024-11-01 05:20 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to calculate the total average commits per PR:
I would avoid duplication and right above when adding to service under a tip panel that
1. If you want to see it on a team level, you need to make sure services are related to teams and add the same aggregations to team

2024-11-01 09:37 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to calculate the total average commits per PR:
okay got it

2024-11-01 10:17 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
@Matanga1-2 so we write `The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/engineering_overview) all the way down for similar examples:` ??

2024-11-01 10:18 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Add the following aggregation property to the **service** and **organization** blueprint:
removed

2024-11-01 17:32 UTC, Matanga1-2 requested changes
Great version!! we are 90% there, added small comments

2024-11-01 17:32 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/scorecardOverview.png' border='1px' />
this was broken to me

2024-11-01 17:32 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +# Implement working agreements and measure pull request standards
I wonder if we should name it just "Measure Pull Requests Standards"

2024-11-01 17:32 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   - Add the properties and mapping configurations as described below.
Here I felt like I'm supposed to add properties based on the image. Maybe the image can be at the end of this section (after "Save the changes") with explanation of "after implementing all the checks in the next section ,it will look something like this"

2024-11-01 17:32 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   <img src='/img/guides/scorecardOnPRAdd.png' />
this was broken for me

2024-11-01 17:32 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<summary><b>Service Scorecard Performance by Team</b></summary>
This should be the most powerful example. If we can build a screenshot of it (will be in the demo next week) and even add at the beginning of this guide and explaining something like "by the end of this guide you'll be able to track teams performance based on pull requests metrics as shown in this screenshot"

2024-11-04 11:13 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +# Implement working agreements and measure pull request standards
makes sense

2024-11-04 11:36 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   - Add the properties and mapping configurations as described below.
okay

2024-11-04 12:12 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
@Matanga1-2  will this be okay then `https://demo.getport.io/my_teams_scorecards`

2024-11-04 12:14 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/settings/data-model) on the `pull request` blueprint:
https://demo.getport.io/scorecard_overview is active now

2024-11-05 06:55 UTC, Matanga1-2 requested changes

2024-11-05 06:55 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/teamPRMetricTable.png' border='1px' />
This is still borken for me.Can you check?

2024-11-05 06:55 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/scorecard_overview) all the way down for similar examples:
all the way down for similar examples


Not sure I understand the context

2024-11-05 06:55 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/scorecardsOverview.png' border='1px' />
This visualization shows properties, not scorecards. These properties are interesting in widgets context but here I thought we will create scorecard for the service blueprint and show the nice aggregation with colors as in the Demo (if it's not like that we will update the demo)

2024-11-05 06:55 UTC, Matanga1-2 commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
This image is broken for me. I'm checking in the guide link in the PR

2024-11-05 06:56 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +The following working agreements and PR checks have been implemented in our [demo environment](https://demo.getport.io/scorecard_overview) all the way down for similar examples:
yeah yeah let me change that. it was in relation to the old picture.

2024-11-05 06:57 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
I made sure everything was pushed. let me check again

2024-11-05 07:27 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/scorecardsOverview.png' border='1px' />
@Matanga1-2 can you check it now

2024-11-05 07:27 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
it's not like that in the preview link.

2024-11-05 07:30 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/teamPRMetricTable.png' border='1px' />
It's not broken in the preview too

2024-11-05 07:30 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/teamPRMetricTable.png' border='1px' />
https://pr-1659.d2ngvl90zqbob8.amplifyapp.com/guides/all/working_agreements_and_measuring_pr_standards

2024-11-05 07:31 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +<img src='/img/guides/scorecardsOverview.png' border='1px' />
@Matanga1-2 Can you check it now ? please

2024-11-05 08:05 UTC, Matanga1-2 approved these changes

2024-11-05 08:05 UTC, Matanga1-2 commented on static/img/guides/teamPRMetricTable.png
@kodjomiles my only comment is that we should create this exact image only have some variation in the socrecards score (similar to the image above). IT will look more impressive.
That's it

2024-11-05 08:08 UTC, kodjomiles commented on static/img/guides/teamPRMetricTable.png
okay got it.

2024-11-05 17:47 UTC, hadar-co requested changes

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +For detailed insights into key metrics like `deployment frequency`, `lead time for changes`, and `change failure rate`,
Same here, the sentence "For detailed...." should be in a new line.
To add a new line, add 2 spaces after the last word. For example:

this is the first line  
This is the second line, note the 2 spaces at the end of the first one

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +These checks are implemented using Port's [scorecards](/#scorecards).
fix the link to the correct scorecards page

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +Follow the steps below to  implement this :
```suggestion
Follow the steps below:
```

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   -  Click on the `{...}` button in the top right corner, and choose "Edit JSON".
```suggestion
   -  Click on the `...` button in the top right corner, and choose "Edit JSON".
```

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   - Save the changes.
note that there is no space between the list and the admonition. This looks bad, use `<br />` where needed to add a gap between them.
Fix this for other places in the guide as well.

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   :::tip Aftermath
Aftermath is not a good name for this, please change it.
Also, "implementing all the checks" is not clear. Make it clearer that this is the expected JSON definition.

2024-11-05 17:47 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +  <summary>Click to view the scorecard definition</summary>
change all of these to be in our regular format:
- should be bold, using <b></b>
- should say "Scorecard definition (click to expand)"

2024-11-06 00:28 UTC, kodjomiles commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +These checks are implemented using Port's [scorecards](/#scorecards).
okay

2024-11-07 13:29 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +If you haven't added the `prDescription` property, and it's relative mapping config
```suggestion
If you haven't added the `prDescription` property and its relative mapping config,
```

2024-11-07 13:29 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +   <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
```suggestion
     <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
```

2024-11-07 13:44 UTC, hadar-co commented on docs/guides/all/working_agreements_and_measuring_pr_standards.md
> +     <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
```suggestion
   <img src='/img/guides/scorecardOnPRAdd.png' border="1px" />
```

2024-11-07 14:39 UTC, hadar-co approved these changes

2024-11-07 14:40 UTC, merged