improvements to github exporter docs
port-labs/port-docs pull request #166
Opened 2023-01-15 16:32 UTC by danielsinai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-01-16 13:40 UTC, MPTG94 approved these changes
LGTM

2023-01-16 13:40 UTC, MPTG94 commented on docs/exporters/github-exporter/exporting-all-repositories.md
> +sidebar_position: 3
Again, verify sidebar position numbering

2023-01-17 15:56 UTC, EllaFurman requested changes

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/bitbucket-exporter/exporting-all-repositories.md
> +To export your Bitbucket `repositories` to Port, you can use the following Port Blueprints definitions, and `port-app-config.yml`:
```suggestion
In this tutorial you will learn how to create a `microservice` Blueprint that contains the properties `repository URL`, `Workspace` and `Project`, which are automatically synced from Bitbucket to Port Entity.

1. Create a `microservice` Blueprint and `port-app-config.yml` configuration file.

To export your Bitbucket `repositories` to Port, you can use the following Port Blueprints definitions, and `port-app-config.yml`:
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/bitbucket-exporter/exporting-all-repositories.md
> +You have to place the `port-app-config.yml` in the repository's root folder.
```suggestion
Place the `port-app-config.yml` in the repository's root folder.
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/bitbucket-exporter/exporting-files.md
> +By the end of this tutorial, we will have a `microservice` Blueprint that contains an auto-synced README.md file into a Port property.
```suggestion
In this tutorial you will learn how to create a `microservice` Blueprint that contains an auto-synced README.md file into a Port property.
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/github-exporter/exporting-all-repositories.md
> +By the end of this tutorial, we will have a `microservice` Blueprint that contains the properties `repository URL` and `Description` which are automatically synced from GitHub to Port entity.
```suggestion
IN this tutorial you will learn how to create a `microservice` Blueprint that contains the properties `repository URL` and `Description`, which are automatically synced from GitHub to Port Entity.
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/github-exporter/exporting-all-repositories.md
> +In order to apply the `port-app-config.yml` in the whole organization, place it in the `.github` folder or in the `.github-private` repository in the root directory.
```suggestion
To apply the `port-app-config.yml` in the whole organization, place it in the `.github` folder or in the `.github-private` repository in the root directory.
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/github-exporter/exporting-files.md
> +By the end of this tutorial, we will have a `microservice` Blueprint that contains an auto-synced `README.md` file into a Port property.
```suggestion
In this tutorial you will learn how to create a `microservice` Blueprint that contains an auto-synced `README.md` file into a Port property.
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/exporters/github-exporter/self-hosted-installation.md
> +- Repository Events (Needed to receive webhooks of changes from GitHub):
```suggestion
- Repository Events (required to receive webhook changes from GitHub):
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/software-catalog/dashboards/dashboards.md
> +| `Filters`               | `Array`  | Filters to include or exclue specific data based on Port's [Search Rules](../../software-catalog/search-in-port.md#search-rules) | []      | `false`  |
```suggestion
| `Title`                 | `String` | Visualization title                                                                                                   | `null`  | `true`   |
| `Icon`                  | `String` | Visualization Icon                                                                                                     | `null`  | `false`  |
| `Description`           | `String` | Visualization description                                                                             | `null`  | `false`  |
| `Blueprint`             | `String` | The chosen Blueprint from which related Entities data is visualized from                                                                    | `null`  | `true`   |
| `Breakdown by property` | `String` | Group your chart by a specific property                                                                                          | `null`  | `true`   |
| `Filters`               | `Array`  | Filters to include or exclude specific data based on Port's [Search Rules](../../software-catalog/search-in-port.md#search-rules) | []      | `false`  |
```

2023-01-17 15:56 UTC, EllaFurman commented on docs/software-catalog/dashboards/dashboards.md
> +To achieve this desired state, we can go into one of the `Service`'s specific page and create a new visualization and after selecting the `Deployment` Blueprint in the dropdown we can add the followi
```suggestion
#### Example: filter only `Deployment` Entities from last week

Let's assume we have a [Blueprint](../../software-catalog/blueprint/blueprint.md) that is called `Service` which is related to another Blueprint called `Deployment`, and we want to create visualizations on top of the last week's deployments of this service.

To achieve this desired state, we can go into one of the `Service`'s profile pages and create a new visualization. After selecting the `Deployment` Blueprint in the dropdown, we can add the following filter to the `Filters` array:
```

2023-01-18 08:24 UTC, merged