PORT-10982- Ingest security issues from sarif files to services
port-labs/port-docs pull request #1675
Opened 2024-10-22 17:52 UTC by kodjomiles

# Description

Added a guide to ingest security issues from sarif files and relate them with service
## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Guide (`/guides/all/ingest-security-issues-from-sarif-files-to-services#how-to-relate-the-security-issues-to-the-service`)

2024-10-23 04:10 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +title: Ingest security issues from `.sarif` files to services
Maybe "too services" is redundant?

2024-10-23 04:19 UTC, Matanga1-2 requested changes

2024-10-23 04:19 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +- Ensure you have [GitHub installed and configured](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/git/github/installation.md) in your environment.
Also supported in Gitlab, no?

2024-10-23 04:19 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +Once the security issues have been ingested, the next step is to establish relationships between these `security_issue` entities and the corresponding `service` entities.
Maybe I'm missing something but at this point you only created BP, you didn't ingest anything

2024-10-23 04:19 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +2. **Add this JSON to establish the relationship**:
Can't we provide the full json in 1 steo instead of 2?

2024-10-23 04:19 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +3. Head back to the [data sources page](https://app.getport.io/settings/data-sources) and ensure that the `relations` section in your mapping includes the relationship to the service:
Again, when did we even added the mapping to begin with?

2024-10-23 04:19 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +By following these steps, you can effectively ingest security issues from `.sarif` files and relate them to the corresponding service entities in Port 🎉.
It's unclear what is the value from this guide. I suggest -
1. Reference the example sarif repo and explain we rely on this standard format, but additional fields can be extracted and modified (for example, location is an array and could be treated as relations to components)
2. Add a screenshot showing the extracted issues from an example file

2024-10-23 10:31 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +- Ensure you have [GitHub installed and configured](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/git/github/installation.md) in your environment.
yeah

2024-10-23 10:36 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +Once the security issues have been ingested, the next step is to establish relationships between these `security_issue` entities and the corresponding `service` entities.
it got flipped

2024-10-23 10:38 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +2. **Add this JSON to establish the relationship**:
if it's just the service relationship we are establishing I don't think we need to show the entire service blueprint since by the time the person get's here, we have assumed they already have github or gitlab setup, so adding this throught the UI or JSON should suffice

2024-10-23 10:40 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +By following these steps, you can effectively ingest security issues from `.sarif` files and relate them to the corresponding service entities in Port 🎉.
Yeah I will add the screenshots

2024-10-31 03:33 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +2. **Add this JSON to establish the relationship**:
@Matanga1-2 ??

2024-10-31 07:45 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +2. **Add this JSON to establish the relationship**:
@jadenmyles the way I saw it, security issue has a relation to service (not the other way around).
And my question was if we can just provide the relation JSON as part of the security_issue blueprint

2024-10-31 07:47 UTC, Matanga1-2 requested changes

2024-10-31 07:47 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +  "relations": {}
@kodjomiles here I assumed you'll have a relation to service

2024-10-31 07:47 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +          issue_service: .repo.name
@kodjomiles here you establish the relation without adding it the blueprint yet

2024-10-31 07:47 UTC, Matanga1-2 commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> + "security_issues": {
This should be part of the security issue blueprint. 
Also here you call it "security_issues" while in the mapping you call it issue_service

2024-11-01 05:14 UTC, Matanga1-2 approved these changes

2024-11-02 13:27 UTC, hadar-co requested changes

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +:::info Prerequisites
change the prerequisites to be a regular header and not an admonition

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +:::info Configuration Details
this too should be a sub-header and not an admonition

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +<img src='/img/guides/exampleExtractedIssues.png' width='100%' />
add border of 1px

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +<img src='/img/guides/exampleSingleExtractedIssues.png' width='100%' />
add border

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +<img src='/img/guides/exampleSingleExtractedIssues.png' width='100%' />
```suggestion
<img src='/img/guides/exampleSingleExtractedIssues.png' width='100%' />
<br/><br/>
```

2024-11-02 13:27 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +## Relevant Guides
No need for a "Guides" section inside a guide like this.
Consider adding a "Conclusion" instead that sums up the value of the guide, like we have other guides, see example here:
https://pr-1675.d2ngvl90zqbob8.amplifyapp.com/guides/all/automatically-approve-action-using-automation#conclusion

2024-11-02 13:30 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +:::info Prerequisites
okay

2024-11-02 13:32 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +:::info Configuration Details
okay. What are the notes on when to make it an admonition or a sub header

2024-11-02 14:43 UTC, hadar-co commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +## Conclusion
reading the conclusion now, it feels a bit repetitive and doesnt add much. Let's remove it

2024-11-02 15:18 UTC, kodjomiles commented on docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
> +## Conclusion
Right

2024-11-03 07:50 UTC, hadar-co approved these changes

2024-11-03 07:50 UTC, merged