PORT-11047 Create SSA for ADO pipeline copy and creation
port-labs/port-docs pull request #1684
Opened 2024-10-28 03:01 UTC by kodjomiles

# Description

-Created SSA to copy template from one repo to another using a pipeline in ADO

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- /guides/all/copy-pipeline-template-to-target-repo

2024-10-28 17:59 UTC, PeyGis requested changes
looks great overall. Left some comments

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
are these enough to run the whole script?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +- The `Azure DevOps Repository` blueprint should be created during the [azure devops installation](/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/#installation) process
Can they somehow have an alternative instead of them using the ADO ocean integration?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +## Implementation - copy pipeline.yaml template from one repository to another
title is long, let's make it short

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
can they use an existing repository for this guide?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +```
if they don't use the ADO ocean integration then this will not work

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
a lot of empty spaces

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +Make sure to replace the placeholder for AZURE_DEVOPS_ORGANIZATION_NAME to where your `pipeline_copier`  repository resides.
in case they use an existing repository then we need to reword this `pipeline_copier`

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +  "title": "Copy Pipeline Template to Target Repo",
Create Azure Pipeline YAML from a Template?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +    "operation": "DAY-2",
why is it a DAY-2 instead of CREATE?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::
I saw you have mentioned this already above. so duplication?

2024-10-28 17:59 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
Also users are having issue with passing the base64 encoded token. Can we ask them to pass the RAW token while we do the base64 ourselves in the script?

2024-10-28 17:59 UTC, PeyGis commented on src/components/guides-section/consts.js
> +        // category: "Getting started",
remove comment if not needed

2024-10-28 18:00 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
I take the raw value and encode it in the pipeline, for the permission we need full access to code and some GitHub. I will add it

2024-10-28 18:01 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +## Implementation - copy pipeline.yaml template from one repository to another
oaky

2024-10-28 18:02 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +
yeah they just have to create the azure-pipeline.yaml in that repo and configure service connection that's all

2024-10-28 18:04 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +```
well in the SSA we are taking inputs from the repo blueprint. if they are not using the ocean integration, they have to  use API to ingest the data into port, use that blueprint for the frontend and select the target and base repo.

2024-10-28 18:06 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +Make sure to replace the placeholder for AZURE_DEVOPS_ORGANIZATION_NAME to where your `pipeline_copier`  repository resides.
In the case of using an existing repository they don't need to create a new repo. so that admonition doesn't affect them. we can state that if you are using an existing repository just copy the azure-pipeline.yaml and put that in your existing repository. and do the necessary service connection configuration

2024-10-28 18:08 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +  "title": "Copy Pipeline Template to Target Repo",
We take a pipeline template from a source repo, copy its content and recreate it in a target repository. Unless I didn't get the requirements right, that would be the way

2024-10-28 18:13 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +    "operation": "DAY-2",
Well the target repo is an already existing repository.  so DAY-2 is modifying it to add a pipeline template. 
Unless they want the target repo to be created for them with the pipeline.yaml then the operation should be a DAY-2

2024-10-28 18:14 UTC, kodjomiles commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::
it's an oversight then

2024-10-28 18:14 UTC, kodjomiles commented on src/components/guides-section/consts.js
> +        // category: "Getting started",
okay

2024-10-29 07:29 UTC, PeyGis commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +```
let's add a note specifying this alternative

2024-10-30 09:33 UTC, hadar-co requested changes

2024-10-30 09:33 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        title: "Copy Pipeline Template to Target Repository",
```suggestion
        title: "Copy ADO Pipeline Template to Target Repo",
```

2024-10-30 09:33 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        description: "Create a self-service action that copies a pipeline template from a source repository to a target repository",
```suggestion
        description: "Create a self-service action that copies an AzureDevops pipeline template to a target repository",
```

2024-10-30 09:33 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +# Copy Pipeline Template to Target Repository
```suggestion
# Copy ADO Pipeline Template to Target Repo
```

2024-10-30 09:33 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +- The `Azure DevOps Repository` blueprint should be created during the [azure devops installation](/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/#installation) process
please make this clearer in the prerequisite. Write that the integration can be installed, or alternatively only the blueprint&mapping from there are enough.

2024-10-30 09:33 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::note
refrain from using :::note pretty much everywhere, it doesnt stand out and its easy to miss. 
Also, make sure all admonitions have titles (there another note below, same comments for that one).

2024-10-30 09:33 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +5. To configure the Pipeline in your project go to Pipelines -> Create Pipeline -> Azure Repos Git and choose `pipeline_copier` and click Save(in "Run" dropdown menu).
```suggestion
5. To configure the Pipeline in your project go to Pipelines -> Create Pipeline -> Azure Repos Git and choose `pipeline_copier` and click Save (in "Run" dropdown menu).
```

2024-10-30 09:33 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +7. Trigger the action from the [Self-service](https://app.getport.io/self-serve) tab of your Port application.
```suggestion
7. Trigger the action from the [Self-service](https://app.getport.io/self-serve) page of your Port application.
```

2025-01-28 15:36 UTC, PeyGis approved these changes
LGTM

2025-02-28 11:11 UTC, hadar-co requested changes

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +- Teams maintain consistent CI/CD configurations across projects
```suggestion
This guide demonstrates how to copy pipeline templates between Azure DevOps repositories using a self-service action in Port. 

Once implemented:
- Platform teams can define standard pipeline templates in a base repository.
- Developers can easily copy these templates to their repositories using a self-service action in their portal.
- Teams can maintain consistent CI/CD configurations across projects.
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +## Common use cases
like the last guide we talked about, leave only one section for use-cases

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +### Create pipeline copier repository
```suggestion
### Create a pipeline copier repository
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::note Port trigger
this should not be in a callout

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::info Option to use an existing repository
indent this callout

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +<br/>
```suggestion
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::info Option to use an existing repository
```suggestion
:::info Use an existing repository
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::
```suggestion
2. Update the `azureDevopsRepository` blueprint and mapping configuration with the `defaultBranch` property, depending on how your setup was created:

    - If you installed the **Azure DevOps integration**, update the `defaultBranch` property in the mapping config file.
    - If you created the blueprint **manually** (without the integration), add the JSON blueprint below and use Port's API to ingest the repository data.

:::info Using Port's API 
If you’re not using the Azure DevOps integration, you will need to use Port's API to ingest repository data based on the blueprint you created.
:::
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::info Using Port's API
include a link to the relevant API docs page

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +Here’s the blueprint JSON configuration to use for manual creation:
```suggestion
To create the necessary data model manually, use the following blueprint JSON and mapping configuration:
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +```yaml showLineNumbers
indentation is wrong

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +3. Create Port action using the following JSON definition:
```suggestion
3. Create a self-service action in Port using the following JSON definition:
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +:::tip Organization and repository placeholders
this callout is not clear, rewrite it in more accurate and clear language

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +<br/>
```suggestion
```

2025-02-28 11:11 UTC, hadar-co commented on docs/guides/all/copy-pipeline-template-to-target-repo.md
> +    1. `PERSONAL_ACCESS_TOKEN` - a [Personal Access Token](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Wind
refrain from using numbered lists inside other numbered lists

2025-02-28 13:41 UTC, merged