PORT-11289 Bug | Change how MTTR is calculated
port-labs/port-docs pull request #1728
Opened 2024-11-13 09:30 UTC by kodjomiles

# Description

Changed `mttr` calculation to use `total average` and added admonition to filter records based on desired month for `lead time for change` and `mttr`

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Dora Metrics (`/guides/all/setup-dora-metrics#aggregation`)

2024-11-14 06:24 UTC, Matanga1-2 requested changes
In lead time, "measureTimeBy": "$createdAt", shouldn't it be "mergedAt"?
As you want to count based on when PRs were merged, not created.

2024-11-14 10:16 UTC, kodjomiles commented
There is no mergedAt property when we use the ```total average```. we are not provided the option to select measureTimeBy. we are given that option when we select average of month,week,days or hours

2024-11-14 10:24 UTC, Matanga1-2 approved these changes

2024-11-14 16:14 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics.md
>  Ensure that the target property is set to the correct Git provider (e.g., `githubPullRequest` for GitHub, `gitlabMergeRequest` for GitLab and `azureDevOpsPullRequest` for Azure DevOps).
too many admonitions here.. The information under "Correct target property" should not be in an admonition

2024-11-14 16:25 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
>  Ensure that the target property is set to the correct Git provider (e.g., `githubPullRequest` for GitHub, `gitlabMergeRequest` for GitLab and `azureDevOpsPullRequest` for Azure DevOps).
Okay

2024-11-15 13:23 UTC, hadar-co approved these changes

2024-11-15 13:38 UTC, merged