PORT-10984 Add “synced webhook + secrets” implementation method to relevant guides
port-labs/port-docs pull request #1741
Opened 2024-11-18 00:07 UTC by kodjomiles

# Description

- Modified trigger datadog incident to include an alternate incident trigger via ports sync webhook and secrets

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Trigger Datadog Incident (`/guides/all/trigger-datadog-incident#alternative-trigger-via-webhook`)

2025-03-05 10:17 UTC, hadar-co requested changes

2025-03-05 10:17 UTC, hadar-co commented on docs/guides/all/change-status-and-assignee-of-jira-ticket.md
> +Ensure the status names are mapped to Jira transition IDs as done in our example:
```suggestion
Replace `<JIRA_ORGANIZATION_URL>` in the webhook URL with your Jira organization URL (e.g., `example.atlassian.net`).

Ensure the status names are mapped to Jira transition IDs as done in the action definitions above:
```

2025-03-05 15:54 UTC, hadar-co commented on docs/guides/all/acknowledge-incident.md
> +1. Head to the [Self Service hub](https://app.getport.io/self-serve)
```suggestion
1. Head to the [self-service page](https://app.getport.io/self-serve) of your portal
```

2025-03-05 15:54 UTC, hadar-co commented on docs/guides/all/change-status-and-assignee-of-jira-ticket.md
>  1. Head to the [Self Service hub](https://app.getport.io/self-serve)
see comment in the same place in the acknowledge incident guide

2025-03-05 15:58 UTC, kodjomiles commented
Okay I will make the corrections along the way

2025-03-05 16:08 UTC, hadar-co commented on docs/guides/all/open-jira-issue-with-automatic-label.md
> +### Add automation to update issue labels
```suggestion
### Create an automation to update issue labels
```

2025-03-05 16:08 UTC, hadar-co commented on docs/guides/all/open-jira-issue-with-automatic-label.md
> +Since the webhook implementation creates the issue first, we'll use an automation to add the service-specific label to the created issue. This keeps our implementation clean and modular.
no need for the "clean and modular" sentence. Instead, add a sentence about what this automation will do

2025-03-06 07:42 UTC, hadar-co requested changes

2025-03-06 07:42 UTC, hadar-co commented on docs/guides/all/resolve-incident.md
> +1. Navigate to Port's [self-hosted agent installation](https://app.getport.io/self-hosted-agents) page.
what is this link? 😅 
Take the wording used in the "acknowledge incident" guide for this part and use it in all guides

2025-03-06 07:42 UTC, hadar-co commented on docs/guides/all/toggle-launchdarkly-feature-flag.md
> +Now you should see both the `Toggle LaunchDarkly Feature Flag` and `Toggle Feature Flag (Webhook)` actions in the self-service page. 🎉
why should the user see both? what if they implemented only the webhook part?

2025-03-06 07:42 UTC, hadar-co commented on docs/guides/all/create-pagerduty-service.md
> +1. Head to the [Builder](https://app.getport.io/settings/data-model) icon.
note that this says to go to the builder icon, which doesnt make sense.

Also, when directing users to the automations page, you can send them directly there with this link:
https://app.getport.io/settings/automations

So step 1 and 2 can become one step.
Also, the button to create a new automation is `+ Automation` and not `+ New Automation`.

Please fix this in all guides

2025-03-08 09:40 UTC, hadar-co approved these changes

2025-03-08 10:22 UTC, merged