PORT-11204 | DORA metrics benchmark guide
port-labs/port-docs pull request #1747
Opened 2024-11-18 20:09 UTC by kodjomiles

# Description

Added the guide to benchmark and visualize DORA metrics
## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- Benchmark DORA Metrics (`/guides/all/setup-dora-metrics-benchmark#track-dora-metrics`)

2024-11-18 20:35 UTC, Matanga1-2 requested changes

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +
@kodjomiles I would consider adding here a screenshot of how the widget should look like when you are finished (we have it in the demo)

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +In this guide, we will extend the work from the [DORA Metrics guide](/guides/all/setup-dora-metrics) by implementing scorecards to benchmark your services against the industry-standard DORA metrics.
@kodjomiles consider linking to the official DORA report (2024) - https://dora.dev/research/2024/

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +You can adjust the thresholds based on your organization's specific needs.
@kodjomiles worth mentioning that these benchmarks consists with the DORA report for 2024, BUT you can always adjust them based on...

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +        "description": "Failure rate is 6-15%.",
@kodjomiles here I actually made a mistake which I'm not sure how to apply.

Medium has CFR of below 10%
High has CFR of below 20% 

It's the other way around in a sense

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +        "description": "Failure rate is 0-5%.",
@kodjomiles worth saying "Less then 5%"?

2024-11-18 20:35 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Elite: 0-5%
Elite - less than 5%
High - less then 20%
Medium - less then 10%
Low - more than 20%

2024-11-18 21:11 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Medium: Between one day and one week.
Less than one day for ??

2024-11-18 21:21 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +        "description": "Failure rate is 6-15%.",
According to the [**official DORA report (2024)**](https://dora.dev/research/2024/), the **Change Failure Rate** benchmarks are:

- **Elite**: Less than **5%**
- **High**: Between **5%** and **10%**
- **Medium**: Between **10%** and **20%**
- **Low**: More than **20%**

2024-11-18 21:24 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Medium: Between one day and one week.
Medim :) medium is like high

2024-11-18 21:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +        "description": "Failure rate is 6-15%.",
@kodjomiles please share screenshot. I sent to you over Slack that Medium is up to 10, and high is up to 20.
also I think it's better to phrase it as "Up to 20" rather than "10 to 20" . But your call on this

2024-11-19 06:23 UTC, Matanga1-2 requested changes

2024-11-19 06:23 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +In this guide, we will extend the work from the [DORA Metrics guide](/guides/all/setup-dora-metrics) by implementing scorecards to benchmark your services against the industry-standard DORA metrics.
@kodjomiles did you decide not to add it?

2024-11-19 06:23 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- High: Between 5% and 10%
@kodjomiles high is less than 20%, medium is less than 10%

2024-11-19 06:23 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Medium: Less than one week.
@kodjomiles medium is less than one day

2024-11-19 08:54 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- High: Between 5% and 10%
@Matanga1-2 are we not using the picture chart anymore ?
![image](https://github.com/user-attachments/assets/8ac69546-4b77-499c-a075-b634821310ff)

2024-11-19 08:57 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- High: Between 5% and 10%
So from what you sent about high being less than 20 and medium less than 10 for cfr. 
that leads to :

- Elite: Less than 5%
- High: Less than 20%
- Medium: Less than 10%
- Low: More than 20%

2024-11-19 08:58 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- High: Between 5% and 10%
is this what you mean ?

2024-11-19 08:58 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- High: Between 5% and 10%
I am successfully confused

2024-11-19 09:03 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Medium: Less than one week.
- Elite: ?
- High: ?
- Medium: Less than one day.
- Low: More than one week.

what would be high and Elite

2024-11-20 12:08 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +                  "property": "changeFailureRate",
@kodjomiles why is this specific condition necessary?
If I have 3% failure rate, that I won't match the "High" scorecard value.

2024-11-20 19:51 UTC, Matanga1-2 approved these changes

2024-11-21 08:26 UTC, hadar-co requested changes

2024-11-21 08:26 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +- Complete the [DORA Metrics guide](/guides/all/setup-dora-metrics): Ensure you have set up the necessary blueprints, properties, and data ingestion.
```suggestion
- Complete the [DORA Metrics guide](/guides/all/setup-dora-metrics), ensuring you have set up the necessary blueprints, properties, and data ingestion.
```

2024-11-21 08:26 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +<details>
this should not be under a details dropdown, it should be directly in the page.

2024-11-21 08:26 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +<img src="/img/guides/doraMetricsTeamScorecard.png" border="1px" />
add a line break after the image

2024-11-21 08:26 UTC, hadar-co commented on src/components/guides-section/consts.js
> +        description: "Setup DORA metrics benchmark within your organization in PORT",
this description repeats the title and doesnt add any information, change it to something more descriptive of the content

2024-11-21 09:53 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +<details>
is it because it's just one

2024-11-21 10:57 UTC, hadar-co approved these changes

2024-11-21 10:57 UTC, hadar-co commented on docs/guides/all/setup-dora-metrics-benchmark.md
> +<br></br>
```suggestion
<br/><br/>  
```

2024-11-21 11:05 UTC, merged