PORT-10837 AgroCD Integration guide refactoring
port-labs/port-docs pull request #1780
Opened 2024-11-25 07:10 UTC by kodjomiles

# Description

Restructure the documentation structure and made some refactoring

## Added docs pages
- Examples page (`/build-your-software-catalog/sync-data-to-catalog/argocd/example`)

## Updated docs pages

Please also include the path for the updated docs

- ArgoCD (`/build-your-software-catalog/sync-data-to-catalog/argocd`)

2024-11-27 11:50 UTC, hadar-co requested changes

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +- Watch for X object changes (create/update/delete) in real-time, and automatically apply the changes to your software catalog.
```suggestion
- Watch for ArgoCD object changes (create/update/delete) in real-time, and automatically apply the changes to your software catalog.
```

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +## Prerequisite
```suggestion
## Prerequisites
```

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +### Generating ArgoCD token
```suggestion
### Generate an ArgoCD token
```

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +1. Navigate to `<serverURL>/settings/accounts/<user>`. For example, if you access your ArgoCD at `https://localhost:8080`, you should navigate to `https://localhost:8080/settings/accounts/<user>`
this section is crowded, put an empty line between each item in the list

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +3. Newly created users may have limited scope to resources by default. For that reason, You will need to configure RBAC policy for the new user by following [this guide](https://argo-cd.readthedocs.i
```suggestion
3. Newly created users may have limited scope to resources by default. For that reason, You will need to configure the RBAC policy for the new user by following [this guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/)
```

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +:::tip Creating ArgoCD user with readonly permissions
this section is not clear.
1. As a reader, I don't know by reading this if I need to create a readonly user or not, there is no context.
2. Why is this in an admonition?

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +<h2> Prerequisites </h2>
missing this line above the prerequisites:
"Using this installation method means that the integration will be able to update Port in real time using webhooks."

You can see that we have it here:
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/other/backstage

Please add this line to the template if it is not already there.

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
>  ```bash showLineNumbers
for code snippets that have only one line, do not add "showLineNumbers"

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/example.md
> +# Examples
please change the name of this file to "examples.md" (and not example.md). 
Make sure to fix the link in the "argocd.md" page accordingly

2024-11-27 11:50 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +### Configuring real-time updates
```suggestion
### Configure real-time updates
```

2024-11-27 17:12 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +:::tip Creating ArgoCD user with readonly permissions
I just did the rearrangement. So I took the entire content and dumped it in there and reading as a user I understood it as if that was the main step

2024-11-27 17:56 UTC, kodjomiles commented on docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
> +<h2> Prerequisites </h2>
it was  not in the template. and I didn't add it to the pagerduty too. is something we missed or its intentional

2024-11-30 14:43 UTC, hadar-co approved these changes

2024-11-30 14:43 UTC, merged