PORT-11428 Added mapping extra resources page to octopus deploy guide
port-labs/port-docs pull request #1824
Opened 2024-12-04 09:24 UTC by oiadebayo

# Description

This PR adds support for mapping additional resources from Octopus Deploy to Port. It includes examples of new resources such as tasks, teams, worker pools, workers, environments, proxies, accounts, packages, and subscriptions, with detailed YAML configurations and blueprint examples.

## Added docs pages

- Mapping extra resources for octopus deploy (`/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/`)

2024-12-04 12:46 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_account.mdx
> +      },
let's remove this property since it's redundant. in the config mapping, I see we are mapping the entity **title** with the **.name**. so let remove the name prop from the mapping

2024-12-04 12:46 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_environment.mdx
> +      },
let's delete this too

2024-12-04 12:47 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_package.mdx
> +      },
let's delete this since we are mapping the entity title already to the .title so this makes it redundant.

title: .Title

2024-12-04 12:48 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_package.mdx
> +      },
let's delete this since we already map the entity identifier to the .Id so mapping it again to the packageId makes it redundant

        mappings:
          identifier: .Id

2024-12-04 12:48 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_proxy.mdx
> +      },
based on the same comments above, let's delete this

2024-12-04 12:49 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_subscription.mdx
> +      },
let's delete this prop

2024-12-04 12:49 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_task.mdx
> +      },
let's delete this

2024-12-04 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_task.mdx
> +      }
shouldn't this be a relation to the space blueprint?

2024-12-04 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_task.mdx
> +      },
shouldn't this be related to the project blueprint?

2024-12-04 12:51 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_team.mdx
> +      },
let's delete this

2024-12-04 12:52 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_worker.mdx
> +      },
let's delete this

2024-12-04 12:52 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/blueprints/_workerpool.mdx
> +      },
delete this

2024-12-04 12:54 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +As you've probably looked at some examples on [Octopus Deploy](../octopus-deploy.md) page, you've noticed that the Octopus Deploy Integration supports several resources, but there are many more resou
```suggestion
As you've probably looked at some examples on [Octopus Deploy](../octopus-deploy.md) page, you've noticed that the Octopus Deploy integration supports several resources, but there are more resources that are not documented on the page.
```

2024-12-04 12:55 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_account.mdx
> +            name: .Name
delete this

2024-12-04 12:55 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_environment.mdx
> +            name: .Name
delete this

2024-12-04 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_package.mdx
> +            title: .Title
delete this

2024-12-04 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_proxy.mdx
> +            name: .Name
delete this

2024-12-04 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_subscription.mdx
> +            name: .Name
delete this

2024-12-04 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_task.mdx
> +            name: .Name
delete this

2024-12-04 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_task.mdx
> +            spaceId: .SpaceId
make it a relation to project and space blueprint

2024-12-04 12:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_team.mdx
> +            name: .Name
delete this

2024-12-04 12:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_worker.mdx
> +            name: .Name
delete this

2024-12-04 12:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mappings/_workerpool.mdx
> +            name: .Name
delete this

2024-12-08 09:43 UTC, hadar-co requested changes

2024-12-08 09:43 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/_category_.json
> +  "label": "Mapping Extra Resources",
```suggestion
  "label": "Ingest additional resources",
```

2024-12-08 09:43 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +As you've probably looked at some examples on [Octopus Deploy](../octopus-deploy.md) page, you've noticed that the Octopus Deploy integration supports several resources, but there are more resources
```suggestion
In addition to the supported resources listed in the [integration page](../octopus-deploy.md), other resources can be ingested, as described on this page.
```

2024-12-08 09:43 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +As you've probably looked at some examples on [Octopus Deploy](../octopus-deploy.md) page, you've noticed that the Octopus Deploy integration supports several resources, but there are more resources
in addition to the suggestion I left, please change the link to be full path and not relative

2024-12-08 09:43 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +---
in addition to all other comments, add a link to this page in the main "octopus deploy" page, with something like:
"The integration supports additional resources, see the `[ingest additional resources]()` page for more information:".

2024-12-10 12:13 UTC, hadar-co requested changes

2024-12-10 12:13 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +## Is the Resource Supported by the Octopus Deploy Integration?
```suggestion
## Check if a resource is supported
```

2024-12-10 12:13 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/mapping-extra-resources/mapping-extra-resources.md
> +## Example Configuration for Additional Resources
```suggestion
## Example configurations
```

2024-12-11 14:16 UTC, hadar-co approved these changes

2024-12-11 14:27 UTC, merged