PORT-11788 DORA Metrics - additional tracking ways
port-labs/port-docs pull request #1851
Opened 2024-12-11 12:49 UTC by kodjomiles

# Description

Added some additional ways to track deployment, calculate lead time for change and measure change failure rate for in the dora metrics guide leveraging on Jira. 

## Updated docs pages

Please also include the path for the updated docs

- Dora Metrics guide (`/guides/all/setup-dora-metrics`)

2024-12-18 08:56 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +              (.fields.created as $created | .fields.resolutiondate as $resolved |
This is actually from "created" to "Resolved". Not from "in progress" to "done". I don't believe you can get from Jira the "date ticket moved to in progress" unless the user created it in a custom way.
To achieve that you could add an automation that upon change to "in progress" updates the date in Port, and a calculation property from that to the resolved.
I would keep both options since organizations sometimes utilize both

2024-12-18 08:58 UTC, Matanga1-2 requested changes

2024-12-18 08:58 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
>  ## Tracking incidents
Do you think we can simplify this part somehow? maybe using tabs like above

2024-12-18 08:58 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
>  ###  Aggregation
Maybe I missed it, but here you didn't change anything, right? If I choose to track with Jira, should I change any of those?

@hadar-co, I do believe this guide is reaching a point of complexity where we should consider splitting it into multiple guides, or separate the "basic" from "advanced."

2024-12-18 09:14 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
> +              (.fields.created as $created | .fields.resolutiondate as $resolved |
Sounds good

2024-12-18 09:15 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
>  ## Tracking incidents
Okay I will use the tabs

2024-12-18 09:16 UTC, kodjomiles commented on docs/guides/all/setup-dora-metrics.md
>  ###  Aggregation
Yeah nothing changed in the aggregation. It stays the same.

2025-01-08 06:26 UTC, Matanga1-2 commented
@kodjomiles @hadar-co I highly recommend to start split this guide into files for readability. it's way too long.
For example
- CI/CD deployments
- PR merged 
- Incident management tools

Its really hard to understand the guide (technically) in its current structure (the UI shouldnt' change, just files structure)

2025-01-08 06:26 UTC, Matanga1-2 requested changes

2025-01-08 06:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Tracking lead time with Jira tickets
This feels out of place. We discuss on tracking deployments and instead we're talking about lead tim

2025-01-08 06:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +### Tracking deployment via Jira tickets (Alternative)
Why don't we put it with the other tracking strategis?

2025-01-08 06:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
> +<TabItem value="recommended" label="Recommended">
Why not have tab items like "Incident management tools" ,"Jira", "Hotfix deployment"

2025-01-08 06:26 UTC, Matanga1-2 commented on docs/guides/all/setup-dora-metrics.md
>  ## Metrics
Maybe I'm missing but no where we explain how the aggregation correlate with the alternative methods. e.g., if I use Jira to track lead time

2025-03-25 10:58 UTC, closed without merging