Add note on preserving API response case style for kinds from non-asset APIs
port-labs/port-docs pull request #1853
Opened 2024-12-11 15:36 UTC by phalbert

# Description

- Introduced a new section in the examples documentation to explain the use of `preserveApiResponseCaseStyle` in the selector configuration.
- Provided examples for `pubsub.googleapis.com/Subscription` and `pubsub.googleapis.com/Topic`.
- Clarified the purpose of this configuration to maintain camelCase format from the GCP API response.

## Updated docs pages

Please also include the path for the updated docs

- GCP Installation - Mapping Extra Resources (`/docs\build-your-software-catalog\sync-data-to-catalog\cloud-providers\gcp\examples\mapping_extra_resources.md`)

2024-12-12 09:03 UTC, mk-armah requested changes
Left some comments and recommendations

2024-12-12 09:03 UTC, mk-armah commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +This ensures that properties maintain their original camelCase format from the GCP API response.
List the APIs affected and their endpoints, Example

- Projects: `cloudresourcemanager.googleapis.com/Project`

2024-12-12 11:52 UTC, mk-armah commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +When `preserveApiResponseCaseStyle` is not set or set to `false` (default behavior), all property names will be converted to camelCase format regardless of their original case style in the API respon
That's the default behavior ? we are not keeping backward compatibility  ?

2024-12-12 11:54 UTC, mk-armah commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +
It converts by default ?

2024-12-12 11:55 UTC, mk-armah reviewed
need some clarifications

2024-12-13 17:07 UTC, mk-armah approved these changes
LGTM

2024-12-14 09:31 UTC, hadar-co approved these changes

2024-12-14 09:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +For resources listed below, the GCP Integration provides flexibility to either transform the properties to snake_case or preserve the original case style (e.g., camelCase) returned by the API for con
```suggestion
For the resources listed below, this integration provides flexibility to either transform the properties to `snake_case` or preserve the original case style (e.g., `camelCase`) returned by the API for consistency with other resources.
```

2024-12-14 09:31 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md
> +This feature applies to the following kinds:
```suggestion
This applies to the following kinds:
```

2024-12-14 09:42 UTC, merged