Add AWS Exporter to the docs
port-labs/port-docs pull request #211
Opened 2023-02-23 09:08 UTC by talsabagport

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- AWS Exporter (`docs/build-your-software-catalog/sync-data-to-catalog/aws/*`)

2023-02-28 16:29 UTC, MPTG94 approved these changes
LGTM, apply fixes for comments please

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +- The `EventPattern` property defines which events to consume, including which event sources, and other filters based on the event structure.
```suggestion
- The `EventPattern` property defines which events to consume, including which event sources, which filters to apply based on the event structure.
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +  In that case, we want to configure the AWS Exporter events queue as the target:
```suggestion
 For the AWS exporter, we want to configure it's own event queue as the target:
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +  In that case, we want to configure the AWS Exporter events queue as the target:
```suggestion
 For the AWS exporter, we want to configure it's own event queue as the target:
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +- The `InputTransformer` key in `Targets` property, defines the transformation applied to the event, before sending it to the target queue;
```suggestion
- The `InputTransformer` key in the `Targets` property defines the transformation that will be applied to the event, before sending it to the target queue;
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +- `InputPathsMap` key in `InputTransformer`, defines which fields to extract from the event. It makes use of [`JSONPath`](https://goessner.net/articles/JsonPath/index.html) syntax to configure the ex
```suggestion
- The `InputPathsMap` key in `InputTransformer` defines which fields to extract from the event. It makes use of [`JSONPath`](https://goessner.net/articles/JsonPath/index.html) syntax to configure the extraction:
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +- `InputTemplate` key in `InputTransformer`, defines a template of the final input to the target queue, as the exporter's Lambda [expects](#input-structure-for-a-single-event) it. The template is ren
```suggestion
- The `InputTemplate` key in `InputTransformer` defines a template of the final input that will be sent to the target queue, in the format the exporter's Lambda [expects](#input-structure-for-a-single-event). The template is rendered using the values from the `InputPathsMap`:
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +Here, the `InputTemplate` takes the information extracted in the `InputPathsMap`, and constructs a message that will be sent to the SQS queue, and will be consumed by the Exporter’s Lambda.
```suggestion
Here, the `InputTemplate` takes the information extracted in the `InputPathsMap`, and constructs a message that will be sent to the SQS queue and consumed by the Exporter’s Lambda.
```

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +The message includes the hardcoded resource type (`AWS::Lambda::Function`); the `awsRegion` from the event;
Update this section so that it is a proper list of resources sent, and not a very long sentence with semi-colons in between

2023-02-28 16:29 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +1. You should prepare an [event rule](#event-rule-definition), based on any specific events;
```suggestion
1. You should prepare an [event rule](#event-rule-definition), based on specific events matching resources you want the AWS exporter to update in real time;
```

2023-02-28 16:30 UTC, MPTG94 approved these changes
LGTM, apply fixes for comments please

2023-03-01 11:55 UTC, Avivlavie requested changes

2023-03-01 11:55 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
> +The `config.json` file is how you specify the exact resources you want to export from your AWS account, and also which entities and which properties in Port, you want to fill in with data.
```suggestion
The `config.json` file is how you specify the exact resources you want to export from your AWS account, and also which Entities and which properties in Port, you want to fill in with data.
```

2023-03-01 11:55 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
> +- The `port`, `entity` and the `mappings` keys open the section used to map the AWS resource fields to Port entities, the `mappings` key is an array where each object matches the structure of an [ent
```suggestion
- The `port`, `entity` and the `mappings` keys open the section used to map the AWS resource fields to Port Entities, the `mappings` key is an array where each object matches the structure of an [entity](../sync-data-to-catalog.md#entity-json-structure).
```

2023-03-01 11:55 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
> +  Pay attention that not all of the resource types listed in the reference are available for use with the Cloud Control API. A method to determine if a resource type is available discussed [here](#st
```suggestion
  Note that not all of the resource types listed in the reference are available for use with the Cloud Control API. A method to determine if a resource type is available discussed [here](#structure).
```

2023-03-01 11:55 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
> +In order to manage entities in Port, the exporter needs access to your Port credentials, these are provided to the exporter via an [`AWS Secrets Manager`](https://docs.aws.amazon.com/secretsmanager/l
```suggestion
In order to manage Entities in Port, the exporter needs access to your Port credentials, these are provided to the exporter via an [`AWS Secrets Manager`](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html) secret.
```

2023-03-01 11:55 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
> +- `region` - A JQ query to get the region from the event, usually the value will be `"\"<awsRegion>\""`
```suggestion
- `region` - A JQ query to get the region from the event, usually the value will be `"\"<awsRegion>\""`;
```

2023-03-01 13:00 UTC, merged