Add pulumi docs
port-labs/port-docs pull request #268
Opened 2023-04-10 14:32 UTC by danielsinai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-04-16 15:07 UTC, MatanHeledPort requested changes
Make all the python examples multi-line like the rest (:

2023-04-17 11:49 UTC, MPTG94 requested changes
Please properly format the different pulumi examples and also add docusaurus code block highlights in the relevant sections, like we do in the API and terraform examples

2023-04-17 11:49 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/_pulumi_provider_base.mdx
> +Please make sure to configure the clientId and secret to Port using the commands
Please add here the general "how to find Port credentials" section that is usually referenced in most docs that require creds (for example look at K8s or AWS docs)

2023-04-17 11:49 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/pulumi.md
> +<Tabs groupId="properties" queryString="property" defaultValue="string" values={[
In this section, please make the code examples multi line so the user doesn't need to scroll horizontally to view the specific property definition.

Also, please add # highlight-start and # highlight-end to highlight the specific lines that show the property definition

2023-04-18 11:01 UTC, MatanHeledPort approved these changes
LGTM

2023-04-20 08:53 UTC, MPTG94 approved these changes
LGTM

Please also add a __category__.json file in the Pulumi directory to make sure its sidebar position is 2

2023-04-20 08:53 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/examples/pulumi-managed-blueprint.md
> +<Tabs groupId="pulumi-definition" defaultValue="python" values={[
```suggestion
<Tabs groupId="pulumi-definition" queryString defaultValue="python" values={[
```

2023-04-20 08:53 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/examples/pulumi-managed-blueprint.md
> +Here is the example definition in all the different languages supported:
```suggestion
Here is the example definition in all the supported languages:
```

2023-04-20 08:53 UTC, MPTG94 commented on docs/build-your-software-catalog/define-your-data-model/setup-blueprint/setup-blueprint.md
> +<Tabs groupId="pulumi-definition" defaultValue="python" values={[
```suggestion
<Tabs groupId="pulumi-definition" queryString defaultValue="python" values={[
```

2023-04-20 09:02 UTC, merged