Docs Sentry Issues and Comments Relations
port-labs/port-docs pull request #269
Opened 2023-04-10 14:52 UTC by PeyGis

# Description

The Sentry webhook integration currently streams individual issues and comments entities to Port. This PR changes the sentry docs to create a relationship between the issues and comments event types.

## Added docs pages
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comment_webhook_configuration.mdx

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comments_blueprint.mdx

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_issue_event_blueprint.mdx

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry.md

## Updated docs pages

{API_URL}/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry

2023-04-16 11:52 UTC, danielsinai requested changes
Great work @PeyGis! 🦢

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_issue_event_blueprint.mdx
> +  "identifier": "sentryIssuesEvent",
Can it be renamed to `sentryIssue`

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry.md
> +## Relation example
I think it's better to change the title to `Relate comments to Issues` wdyt?

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry.md
> +The following example adds a `comment` blueprint, in addition to the `issues` blueprint shown in the previous example. In addition, it also adds a `sentryIssuesEvent` relation. The webhook will creat
```suggestion
The following example adds a `sentryComment` blueprint, in addition to the `sentryIssue` blueprint shown in the previous example. In addition, it also adds a `sentryIssue` relation. The webhook will create or update the relation between the 2 existing entities, allowing you to map which issue a comment is made on:
```

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comment_webhook_configuration.mdx
> +          "sentryIssuesEvent": ".body.data.issue_id | tostring"
`sentryIssue`

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comments_blueprint.mdx
> +    "sentryIssuesEvent": {
sentryIssue

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comments_blueprint.mdx
> +      "target": "sentryIssuesEvent",
sentryIssue

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_issue_event_blueprint.mdx
> +  "identifier": "sentryIssuesEvent",
I added comments when it should be changed as well, but make sure the example still works please :)

2023-04-16 11:52 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_issue_event_blueprint.mdx
> +      "issueStatus": {
Maybe `status` instead, also would love if you can change the `issueUrl` to `url`

2023-04-17 05:05 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry.md
> +## Relation example
That sounds great.

2023-04-17 05:12 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comment_webhook_configuration.mdx
> +          "sentryIssuesEvent": ".body.data.issue_id | tostring"
I have a comment on this. I see that you have sentryIssue as the blueprint's name, and the relation's name is also sentryIssue. Is this correct?

2023-04-17 06:28 UTC, PeyGis commented
Hello @danielsinai I've made changes to the sentry webhook. I've also tested it and ensured all changes work as expected. See the screenshots below.

Issues:
![image](https://user-images.githubusercontent.com/15999660/232402055-8fa7bdbd-57d9-4d07-8423-3327b6bf7400.png)

Related Comments:
![image](https://user-images.githubusercontent.com/15999660/232402206-600229c0-1ec0-4175-af35-598a3971ecd3.png)

2023-04-17 06:30 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_issue_event_blueprint.mdx
> +      "issueStatus": {
You can see in the code that I've deleted the URL. This is because that field returns null, and it is not included in the request payload. See the example below.

```
{
	'action': 'created',
	'installation': {
		'uuid': '54a3e698-f389-4d86-b9f8-50093a228449'
	},
	'data': {
		'issue': {
			'id': '4098021079',
			'shareId': None,
			'shortId': 'PYTHON-6',
			'title': "AttributeError: module 'sentry_sdk' has no attribute 'newp'",
			'culprit': '__main__ in <module>',
			'permalink': None,
			'logger': None,
			'level': 'error',
			'status': 'unresolved',
			'statusDetails': {},
			'isPublic': False,
			'platform': 'python',
			'project': {
				'id': '4504989602480128',
				'name': 'python',
				'slug': 'python',
				'platform': 'python'
			},
			'type': 'error',
			'metadata': {
				'value': "module 'sentry_sdk' has no attribute 'newp'",
				'type': 'AttributeError',
				'filename': 'app.py',
				'function': '<module>',
				'display_title_with_tree_label': False
			},
			'numComments': 0,
			'assignedTo': None,
			'isBookmarked': False,
			'isSubscribed': False,
			'subscriptionDetails': None,
			'hasSeen': False,
			'annotations': [],
			'issueType': 'error',
			'issueCategory': 'error',
			'isUnhandled': True,
			'count': '1',
			'userCount': 0,
			'firstSeen': '2023-04-17T05:48:14.511057Z',
			'lastSeen': '2023-04-17T05:48:14.511057Z'
		}
	},
	'actor': {
		'type': 'application',
		'id': 'sentry',
		'name': 'Sentry'
	}
}
```

2023-04-17 10:47 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comment_webhook_configuration.mdx
> +          "sentryIssuesEvent": ".body.data.issue_id | tostring"
Yea :)

2023-04-17 10:50 UTC, danielsinai requested changes
Nice :) 
Last change! 🦢

2023-04-17 10:50 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sentry.md
> +<summary>Sentry comments blueprint (including the sentryIssuesEvent relation)</summary>
```suggestion
<summary>Sentry comments blueprint (including the sentryIssue relation)</summary>
```

2023-04-17 12:23 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/sentry/_example_sentry_comment_webhook_configuration.mdx
> +          "sentryIssuesEvent": ".body.data.issue_id | tostring"
noted

2023-04-17 16:58 UTC, danielsinai approved these changes
🦢 WP

2023-04-18 11:36 UTC, merged