Docs  - Jenkins Webhook
port-labs/port-docs pull request #271
Opened 2023-04-12 12:16 UTC by PeyGis

# Description

Adding a webhook integration between Port and Jenkins. The purpose is to stream all Jenkins job statuses and events to Port.

## Added docs pages

 docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
 docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_blueprint.mdx
 docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx

2023-04-13 10:06 UTC, PeyGis commented
Job Entities
![image](https://user-images.githubusercontent.com/15999660/231726262-463226f3-3c7d-4a02-b1ba-5380434b080b.png)

Build Entities
![image](https://user-images.githubusercontent.com/15999660/231726491-dd4f0777-c386-44de-993f-5f25adbba49b.png)

Job Build Relationship
![image](https://user-images.githubusercontent.com/15999660/231726668-a389801f-388e-4388-bff2-f925dcbdc235.png)

2023-04-13 10:20 UTC, MPTG94 requested changes
Please go over my notes and verify the things around the JSON payload

2023-04-13 10:20 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +3. Navigate to the **Available Plugins** tab and search for **Notifications** in the search bar. Install the [Extreme Notification Plugin](https://plugins.jenkins.io/notification/) or a suitable plug
```suggestion
3. Navigate to the **Available Plugins** tab and search for **Notifications** in the search bar. Install the [Notification Plugin](https://plugins.jenkins.io/notification/) or a suitable plugin that can notify some endpoints about events that occur in Jenkins;
```

2023-04-13 10:39 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +   4. `URL` - Choose **Plain Text** and enter the value of the `url` key you received after creating the webhook configuration;
That makes sense. I will stick with your suggestion here. `body.name + \"-\" + .body.build.number`. I had it initially but Yonatan suggested in one of my previous docs that I shouldn't repeat the payload fields. That's why I chose the `notes` Knowing this, I'll stick with your suggestion then

2023-04-13 10:44 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +          "timestamp": ".body.build.timestamp"
This looks interesting because below is an example of the payload I worked with yesterday. 

```
{
	'name': 'First Project',
	'display_name': 'First Project',
	'url': 'job/First%20Project/',
	'build': {
		'full_url': 'http://localhost:8081/job/First%20Project/33/',
		'number': 33,
		'queue_id': 33,
		'timestamp': 1681282860312,
		'duration': 2735,
		'phase': 'COMPLETED',
		'status': 'SUCCESS',
		'url': 'job/First%20Project/33/',
		'scm': {
			'changes': [],
			'culprits': []
		},
		'log': '',
		'notes': 'Webhook integration for job status',
		'artifacts': {}
	}
}
```

2023-04-13 10:46 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +          "timestamp": ".body.build.timestamp"
And I can see from my Port Jenkins job entity that the timestamp (in UNIX) in included in the payload

![image](https://user-images.githubusercontent.com/15999660/231735704-c668bccf-6d3b-4384-9065-d0082fdd159a.png)

2023-04-13 12:15 UTC, PeyGis commented
@MPTG94 I've made changes to the code based on the feedback you gave.

2023-04-17 11:02 UTC, MPTG94 requested changes
Please look at my various comments @PeyGis

2023-04-17 11:02 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +In this example you are going to create a webhook integration between [Jenkins](https://www.jenkins.io/) and Port, which will ingest job and build entities.
General question - the notification we are using is for build events, where do you explain in this guide how to send job events?

2023-04-18 05:30 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +        "type": "string",
Looking at the sample of the request payload, the format is not a URL. It is more like a path. It is the buildURL that follows the regular URL pattern.

```
{
	'name': 'First Project',
	'display_name': 'First Project',
	**'url': 'job/First%20Project/**',
	'build': {
		'full_url': 'http://localhost:8081/job/First%20Project/33/',
		'number': 33,
		'queue_id': 33,
		'timestamp': 1681282860312,
		'duration': 2735,
		'phase': 'COMPLETED',
		'status': 'SUCCESS',
		'url': 'job/First%20Project/33/',
		'scm': {
			'changes': [],
			'culprits': []
		},
		'log': '',
		'notes': 'Webhook integration for job status',
		'artifacts': {}
	}
}
```

2023-04-18 05:37 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "timestamp": {
Changing the format to date-time shows this extraordinary date value (336 years ago) in Port.
![image](https://user-images.githubusercontent.com/15999660/232680374-aab0b8e9-4578-47d1-b39d-32636f68a345.png)

However, when I used an online converter to valid it, I got the correct timestamp (6 days ago)
![image](https://user-images.githubusercontent.com/15999660/232680870-eb72abdd-05aa-4920-a28d-9e95c9f2aa61.png)

Do you happen to know why this is so?

2023-04-18 05:43 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +## Relation example
I need clarification on this. Can you help me understand what is expected to be done here?

2023-04-18 05:45 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "title": ".body.name + \"-\" + .body.build.number",
I explained in the main section that they should add the **Notes** section, so this section uses the value from the `notes` field. I've updated it

2023-04-18 06:11 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_blueprint.mdx
> +        "type": "string",
Hello, there is an issue with parsing the URL from Jenkins in Port. When I change the format from regular string to URL, it throws this error. As a result, the entities are not created. Here is an example of the URL from the request payload, and not sure why it can't be parsed.

http://localhost:8081/job/Git%20Project%20Demo/55/

![image](https://user-images.githubusercontent.com/15999660/232686443-e931d9ad-3f45-4730-9735-190f9d3acde2.png)

2023-04-18 06:43 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "title": ".body.name + \"-\" + .body.build.number",
I finally managed to get this format to work using `.body.name + \" - \" + (.body.build.number | tostring)`
![image](https://user-images.githubusercontent.com/15999660/232693188-b1ee1b2a-66e0-4f1f-8c3b-e2132d030000.png)

2023-04-18 07:04 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +In this example you are going to create a webhook integration between [Jenkins](https://www.jenkins.io/) and Port, which will ingest job and build entities.
The **Notification** plugin sends both pieces of information. So the same payload contains all the details about the current phase of the job (Queued, Started, Completed, Finished) as well as the status of the build (Success, Failure, Unstable)

Here's a description from the [plugin's page](https://plugins.jenkins.io/notification/)

> The payload submitted includes the following information:
> 
> Job's name and URL.
> Build's number, full URL, phase, and status.
> SCM URL, branch and commit (only for Git repositories).

2023-04-18 07:07 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "timestamp": {
Ignore this. Looks like the app was having a challenge parsing old timestamps for the old entities. New entities added are now processed well. The old entity records still show the 336 years old, though

![image](https://user-images.githubusercontent.com/15999660/232698244-64649cc0-75a3-4c36-950f-877f890a7981.png)

2023-04-18 12:15 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "title": ".body.name + \"-\" + .body.build.number",
@PeyGis Nice, looks good 👍

2023-04-18 12:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "timestamp": {
That's fine, users will only ingest new entities that use the correct format so if it works that's fine

2023-04-18 12:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +        "type": "string",
Ok, so let's leave it as type `string` without the `format`

2023-04-18 12:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +In this example you are going to create a webhook integration between [Jenkins](https://www.jenkins.io/) and Port, which will ingest job and build entities.
Ok so my comment [here](https://github.com/port-labs/port-docs/pull/271#discussion_r1169943765) will work with the plugin well (the same webhook for both mappings)

2023-04-18 13:57 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
> +## Relation example
![image](https://user-images.githubusercontent.com/15999660/232800328-4202e78f-981e-410d-8c4d-5e7a8c87355f.png)

I've got it to work with the multiple blueprints

2023-04-18 17:08 UTC, MPTG94 approved these changes
LGTM

2023-04-18 17:08 UTC, merged