Docs  - Dynatrace webhook
port-labs/port-docs pull request #276
Opened 2023-04-18 13:02 UTC by PeyGis

# Description

A webhook integration between Port and Dynatrace. This doc guides users to ingest problem notifications from Dynatrace entities to Port.

## Added docs pages

Please also include the path for the added docs.

{{BASE_URL}}/build-your-software-catalog/sync-data-to-catalog/webhook/examples/dynatrace

2023-04-18 13:55 UTC, PeyGis commented
![image](https://user-images.githubusercontent.com/15999660/232799651-592a7319-bcbb-480f-8936-98c049272aa8.png)

![image](https://user-images.githubusercontent.com/15999660/232799755-456e3e18-2eb2-4066-9d4f-336a4d44280b.png)

2023-04-20 14:13 UTC, MPTG94 requested changes
Please fix the comments and suggestions I added

2023-04-20 14:13 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/dynatrace/_example_dynatrace_problem_webhook_configuration.mdx
> +          "severity": ".body.ProblemSeverity"
Please check if you can also map the problem tags to an array of tags (you will also need to update the dynatrace problem blueprint with this new property)

2023-04-20 14:13 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/dynatrace.md
> +
Add here an [admonition](https://docusaurus.io/docs/markdown-features/admonitions) block of type note that says that the relation mapping in the webhook configuration will only work if the identifiers of Port microservice entities matches the names of entities in your dynatrace

2023-04-20 16:02 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/dynatrace/_example_dynatrace_problem_webhook_configuration.mdx
> +          "microservice": ".body.ImpactedEntities[].entity"
Thanks for this. I had asked about it in the channel

2023-04-20 16:42 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/dynatrace/_example_dynatrace_problem_webhook_configuration.mdx
> +          "severity": ".body.ProblemSeverity"
I have used arrays for the `tags` property. Let me know if I should convert it to string, as that's the default type from the webhook
```{
  "Tags": "testtag1, testtag2"
}
```

2023-04-21 07:52 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/dynatrace.md
> +The relation mapping in the webhook configuration will only work if the identifiers of Port microservice entities matches the names of entities in your dynatrace.
```suggestion
The relation mapping in the webhook configuration will only work if the identifiers of Port microservice entities matches the names of entities in your Dynatrace.
```

2023-04-21 08:01 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/dynatrace.md
> +   "ProblemID":"{PID}",
noted

2023-04-21 08:15 UTC, merged