Docs jenkins webhook
port-labs/port-docs pull request #277
Opened 2023-04-19 09:57 UTC by PeyGis

# Description

Changing the Jenkins build relation title to "Jenkins Job"

2023-04-22 11:09 UTC, MPTG94 requested changes
Can you please go over my comment, and also can you post in the PR screenshots of the resulting entities form this example after replacing the plugin?

2023-04-22 11:09 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "calculation": "'https://your_jenkins_url/' + .identifier",
I don't think adding the identifier to the jenkins URL will construct a correct URL, did you test this? what is the URL that is generated?

2023-04-22 13:30 UTC, PeyGis commented
Jenkins Job Entity
![image](https://user-images.githubusercontent.com/15999660/233787904-3234144c-0b30-4743-9b89-80df48d89dc0.png)


Jenkins Build Entity col 1
![image](https://user-images.githubusercontent.com/15999660/233787991-f62f8da1-a228-4cfe-bf41-5d6d0dcfb410.png)

Jenkins Build Entity col 2
![image](https://user-images.githubusercontent.com/15999660/233788019-19000975-ce10-4129-9881-b0ddfc8b026d.png)

2023-04-22 13:32 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "calculation": "'https://your_jenkins_url/' + .identifier",
This is an example URL from one of the jobs.

[https://your_jenkins_url/Git Project Demo](https://your_jenkins_url/job/Test%20Project%202/)

2023-04-22 13:35 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "calculation": "'https://your_jenkins_url/' + .identifier",
Below is an example of the create/update/delete job event. You can see that the URL property is properly formatted 
```
{
	'data': {
		'_class': 'hudson.model.FreeStyleProject',
		'actions': [{}, {}, {
			'_class': 'org.jenkinsci.plugins.displayurlapi.actions.JobDisplayAction'
		}, {
			'_class': 'com.cloudbees.plugins.credentials.ViewCredentialsAction'
		}],
		'description': None,
		'displayName': 'New Item Example',
		'displayNameOrNull': None,
		'fullDisplayName': 'New Item Example',
		'fullName': 'New Item Example',
		'name': 'New Item Example',
		'buildable': True,
		'builds': [],
		'color': 'notbuilt',
		'firstBuild': None,
		'healthReport': [],
		'inQueue': False,
		'keepDependencies': False,
		'lastBuild': None,
		'lastCompletedBuild': None,
		'lastFailedBuild': None,
		'lastStableBuild': None,
		'lastSuccessfulBuild': None,
		'lastUnstableBuild': None,
		'lastUnsuccessfulBuild': None,
		'nextBuildNumber': 1,
		'property': [],
		'queueItem': None,
		'concurrentBuild': False,
		'disabled': False,
		'downstreamProjects': [],
		'labelExpression': None,
		'scm': {
			'_class': 'hudson.scm.NullSCM'
		},
		'upstreamProjects': []
	},
	'dataType': 'hudson.model.FreeStyleProject',
	'id': '62bf0f1b-4666-4c33-b817-e1967c3d2324',
	'source': '',
	'time': '2023-04-19T11:13:23.677+0000',
	'type': 'item.created',
	'url': 'job/New%20Item%20Example/'
}
```

2023-04-22 18:35 UTC, MPTG94 requested changes
Please look at my comments

2023-04-22 18:35 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "calculation": "'https://your_jenkins_url/' + .identifier",
If you browse to the URL, does it properly open in your browser?

2023-04-22 18:35 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "identifier": ".body.url",
Isn't there some other unique id that can be used as the identifier? The URL as an identifier is not very pretty, I prefer to just save it as an additional property, and have a more meaningful and aesthetic value as the identifier

2023-04-23 09:26 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_job_blueprint.mdx
> +      "calculation": "'https://your_jenkins_url/' + .identifier",
Yes, I'm running my Jenkins on my localhost and when I click on the link in Port, it takes me directly to my Jenkins job page

http://localhost:8081/job/Test%20Freestyle%20Project/

2023-04-23 09:30 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "identifier": ".body.url",
There is the `id` field on the job event payload, and that would have been the best property to use. However, when we look at the build/run event payload, the only property that references the parent job is the `source` property. And the value of the `source` property references the `url` property of the job event

2023-04-23 09:31 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "identifier": ".body.url",
Here's a sample payload from the run/build event

```
{
	'data': {
		'_class': 'hudson.model.FreeStyleBuild',
		'actions': [{
			'_class': 'hudson.model.CauseAction',
			'causes': [{
				'_class': 'hudson.triggers.TimerTrigger$TimerTriggerCause',
				'shortDescription': 'Started by timer'
			}]
		}, {}, {
			'_class': 'org.jenkinsci.plugins.displayurlapi.actions.RunDisplayAction'
		}],
		'artifacts': [],
		'building': False,
		'description': None,
		'displayName': '#253',
		'duration': 1378,
		'estimatedDuration': 2263,
		'executor': {},
		'fullDisplayName': 'Multiple Blueprint Project #253',
		'id': '253',
		'inProgress': False,
		'keepLog': False,
		'number': 253,
		'queueId': 582,
		'result': 'SUCCESS',
		'timestamp': 1681901640686,
		'builtOn': '',
		'changeSet': {
			'_class': 'hudson.scm.EmptyChangeLogSet',
			'items': [],
			'kind': None
		},
		'culprits': []
	},
	'dataType': 'hudson.model.FreeStyleBuild',
	'id': '1d7a6a30-d4ca-4b33-b317-2c7ca75d41d0',
	'source': 'job/Multiple%20Blueprint%20Project/',
	'time': '2023-04-19T10:54:03.056+0000',
	'type': 'run.finalized',
	'url': 'job/Multiple%20Blueprint%20Project/253/'
}

```

2023-04-23 09:44 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
> +        "identifier": ".body.url",
Ok, let's keep it as URL, but please update the JQ pattern so that it replaces the `%20` with hypens (`-`) to make the URL seem nicer. You will also need to make that update when creating the relation.

In addition, add a new separate property for the build URL so that users can still make use of the calculation property you created (because the identifier will now not be correct for the URL, so the additional property will be a replacement)

2023-04-23 17:05 UTC, PeyGis commented
Build
![image](https://user-images.githubusercontent.com/15999660/233853940-fe7f3f25-e91a-4e19-9ab3-75043214ebbf.png)

Job and related builds
![image](https://user-images.githubusercontent.com/15999660/233853983-36d6a558-1e42-4ab2-8285-8b4550bf37f6.png)

2023-04-23 17:45 UTC, MPTG94 approved these changes
LGTM

2023-04-23 17:48 UTC, merged