Update OpsGenie to include who is on call
port-labs/port-docs pull request #280
Opened 2023-04-23 18:58 UTC by PeyGis

# Description

This PR adds a section that points users on how to ingest OpsGenie's on-call data into Port

## Updated docs pages

https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie

2023-04-24 14:40 UTC, danielsinai requested changes
Great work buddy 🦢

2023-04-24 14:40 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
> +[Github Action](https://github.com/PeyGis/OpsGenie)
Please change it to GitHub Workflow

2023-04-24 14:40 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
> +[Github Action](https://github.com/PeyGis/OpsGenie)
Please move those repos to port-labs both in github and gitlab

2023-04-24 14:40 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
> +[Github Action](https://github.com/PeyGis/OpsGenie)
Ill send you invites right away

2023-04-27 09:36 UTC, Avivlavie approved these changes

2023-04-27 09:36 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
> +In this example we will create a blueprint for `service` entities with a `on-call` property that will be ingested directly from OpsGenie.
```suggestion
In this example we will create a blueprint for `service` entities with an `on-call` property that will be ingested directly from OpsGenie. 
```

2023-04-27 09:36 UTC, Avivlavie commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
> +The exmaples below are pulling data from the OpsGenie REST Api, in a defined scheduled period using GitLab Pipelines or GitHub Workflows, and reports the data to Port as a property to the `service` b
```suggestion
The examples below pull data from the OpsGenie REST Api, in a defined scheduled period using GitLab Pipelines or GitHub Workflows, and report the data to Port as a property to the `service` blueprint.
```

2023-04-27 11:07 UTC, merged