Docs - Snyk Webhook
port-labs/port-docs pull request #290
Opened 2023-04-25 12:14 UTC by PeyGis

# Description

A webhook integration between Port and Snyk to ingest vulnerability entities to Port.

## Added docs pages

/build-your-software-catalog/sync-data-to-catalog/webhook/examples/snyk

2023-04-25 12:21 UTC, PeyGis commented
![image](https://user-images.githubusercontent.com/15999660/234274316-97ecd24b-eeb8-46ea-a1e0-9104a6cda15e.png)

![image](https://user-images.githubusercontent.com/15999660/234274369-111485b6-acdd-4e8f-9abc-6718a7787736.png)

2023-04-27 13:55 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/snyk.md
> +4. Open any REST API client such as POSTMAN and make the following API call to create your webhook:
Provide here a `curl` script in addition

2023-04-27 13:55 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/snyk/_example_snyk_vulnerability_webhook_configuration.mdx
> +          "issueType": ".body.newIssues[0].issueType",
There could be more than 1 issue in a single webhook?

2023-04-28 06:48 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/snyk/_example_snyk_vulnerability_webhook_configuration.mdx
> +          "issueType": ".body.newIssues[0].issueType",
Yes, there could be more than 1 issue

2023-04-30 12:57 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/snyk.md
> +4. Open any REST API client such as POSTMAN and make the following API call to create your webhook:
```
curl -X POST \
     -H "Authorization: token YOUR_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"url": "https://ingest.getport.io/YOUR_PORT_WEBHOOK_KEY", "secret": "WEBHOOK_SECRET"}' \
     https://api.snyk.io/v1/org/YOUR_ORG_ID/webhooks
```

2023-04-30 12:57 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/snyk/_example_snyk_vulnerability_webhook_configuration.mdx
> +          "issueType": ".body.newIssues[0].issueType",
I see thanks! we will wait for the feature in port side then :)

2023-05-28 15:38 UTC, danielsinai requested changes
🦢 Great job man, small comment :)

2023-05-28 15:38 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/snyk.md
> +```curl showLineNumbers
Can you input it in a :::note

2023-05-29 11:47 UTC, danielsinai approved these changes
🦢 Great job!

2023-05-29 11:54 UTC, merged