BitBucket Repository Push
port-labs/port-docs pull request #311
Opened 2023-05-08 19:17 UTC by PeyGis

# Description

Added documentation on streaming the latest BitBucket commit hash to Port using webhooks.

## Added docs pages

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md

2023-05-16 11:29 UTC, danielsinai requested changes
🦢 Great work, some comments

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +import CommitBlueprint from './resources/bitbucket/\_example_bitbucket_push_blueprint.mdx'
Let's rename to `MicroserviceBlueprint`

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +<summary>Commit blueprint</summary>
Here as well

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +<summary>Commit webhook configuration</summary>
Maybe Push webhook configuration instead

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +   2. `URL` - enter the value of the `url` key you received after creating the webhook configuration;
Maybe rephrase it in a way it will make sense that it comes from Port (the URL)

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +In order to view the different payloads and events available in BitBucket webhooks, [look here](https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Push)
Specify here that the structure of the data can be found here, and it is used by the configuration in the webhook configuration

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +          "author": ".body.push.changes[0].new.target.author.user.display_name",
Does it works on squash & merge, and also rebase?
Can you validate that please

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +          "author": ".body.push.changes[0].new.target.author.user.display_name",
Let's name it `commitHash` and `commitAuthor`, as the identifier of the blueprint is camelcased.
And please remember to update the blueprint as well accrodingly

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +In this example you are going to create a webhook integration between [BitBucket](https://bitbucket.org) and Port, which will ingest commit entities.
This isn't phrase well, please rephrase it in a way that will explain we will add to an existing microservices in port a data about the latest commit pushes to the default branch

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +In this example you are going to create a webhook integration between [BitBucket](https://bitbucket.org) and Port, which will ingest commit entities.
In this example, we will be integrating BitBucket and Port to enhance an existing microservice in Port with data regarding the latest commit pushes to the default branch. This integration will involve setting up a webhook to receive notifications from BitBucket whenever a new commit is made to the default branch, allowing Port to ingest and process the commit entities accordingly.

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +In this example you are going to create a webhook integration between [BitBucket](https://bitbucket.org) and Port, which will ingest commit entities.
something like that maybe

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +Create the following blueprint definition and webhook configuration:
```suggestion
Create the following blueprint definition and webhook configuration in Port:
```

2023-05-16 11:29 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +Done! any change you make to the repository will trigger a webhook event that BitBucket will send to the webhook URL provided by Port. Port will parse the events according to the mapping and update t
```suggestion
Done! any push to the repository's main branch will trigger a webhook event that will be sent to the webhook URL provided by Port. Port will parse the events according to the mapping and update the catalog entities accordingly.
```

2023-05-16 17:16 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +          "author": ".body.push.changes[0].new.target.author.user.display_name",
Reading from the docs, it looks like the[ push event](https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Push) contains a rebased commit.

> Commits that have been force pushed–When you perform a rebase followed by a force push, the commits of the old reference are replaced with all the commits in the new reference. As a result, the array includes the commits part of the new reference.  The array does not include commits that are deleted during a rebase or a force push.

2023-05-16 17:18 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +          "author": ".body.push.changes[0].new.target.author.user.display_name",
Also, merge requests are part of a different event [pullrequest:fulfilled](https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Pull-request)

2023-05-16 17:19 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +In this example you are going to create a webhook integration between [BitBucket](https://bitbucket.org) and Port, which will ingest commit entities.
thanks for this

2023-06-07 07:29 UTC, danielsinai approved these changes
👍

2023-06-07 08:02 UTC, danielsinai requested changes
Went over it again, seems like some things are yet to be finished

2023-06-07 08:02 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +        "identifier": "latest_commit",
Should be the repo name

2023-06-07 08:02 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +        "title": "Latest Commit",
Should be the repo name

2023-06-07 08:02 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/bitbucket/_example_bitbucket_push_webhook_configuration.mdx
> +      "filter": ".headers.\"X-Event-Key\" == \"repo:push\"",
Where the filter is looking for the main branch?

2023-06-07 08:02 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/bitbucket.md
> +<summary>Microservice blueprint</summary>
Add a note that explaining that the blueprint microservice can be extended, and that's just an example

2023-08-02 10:24 UTC, closed without merging