Docs Cloudbuild Webhook Trigger
port-labs/port-docs pull request #317
Opened 2023-05-10 11:56 UTC by PeyGis

# Description

This doc guides users to trigger webhook actions to Google CloudBuild

## Added docs pages

docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/

2023-05-16 11:24 UTC, MPTG94 requested changes
Please fix the various comments

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +[
Put this through a proper JSON formatter, you can see that the root square bracket and curly bracket are in the same indent and it doesn't look good enough

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +  "identifier": "myIdentifier",
```suggestion
  "identifier": "runPipeline",
```

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +  "title": "GCP Cloud Build",
```suggestion
  "title": "Run GCP Cloud Build Pipeline",
```

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +      "image_name": {
```suggestion
      "imageName": {
```

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +  _IMAGE_NAME: $(body.payload.properties.image_name)
```suggestion
  _IMAGE_NAME: $(body.payload.properties.imageName)
```

2023-05-16 11:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +```yaml
Please verify all codeblocks in this doc have `showLineNumbers`

2023-05-16 11:25 UTC, MPTG94 reviewed
Added another comment

2023-05-16 11:25 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/_category_.json
> +  "position": 6
Azure pipelines already uses position `6`, if you want to add it after Azure, you need to change Kafka to `8` and cloud build will use `7`.

2023-05-17 09:35 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/_category_.json
> +  "position": 6
Noted

2023-05-17 09:49 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +[
Thanks for pointing this out. I've fixed it

2023-05-18 09:15 UTC, MPTG94 requested changes
Requested some more minor changes

2023-05-18 09:15 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +**Port Action** - The full port action definition can be found [here](#setting-up-the-port-action).
```suggestion
**Port Action** - The full Port action definition can be found [here](#setting-up-the-port-action).
```

2023-05-18 09:15 UTC, MPTG94 commented on static/img/self-service-actions/setup-backend/cloudbuild-pipeline/cloud-build-illustration.png:Zone.Identifier
@PeyGis remove this file

2023-05-18 11:00 UTC, MPTG94 approved these changes
LGTM

2023-05-18 11:00 UTC, merged