Datadog Webhook
port-labs/port-docs pull request #318
Opened 2023-05-12 14:15 UTC by PeyGis

# Description

Added integration docs for Datadog and Port using webhook

## Added docs pages

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/datadog.md

2023-05-16 13:25 UTC, MPTG94 requested changes
please make changes according to comments

2023-05-16 13:25 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +          "event_type": ".body.event_type",
```suggestion
          "eventType": ".body.event_type",
```

2023-05-16 13:25 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +          "alert_metric": ".body.alert_metric",
```suggestion
          "alertMetric": ".body.alert_metric",
```

2023-05-16 13:25 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +          "microservice": ".body.service"
is the `service` key in the datadog request an array? you marked the relation as `many: true`

2023-05-16 13:25 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +          "microservice": ".body.service"
After reviewing the documentation of variables in datadog, it looks that a single value will be sent, and not an array. So I think the relation should be `many: false`. Can you please verify?

2023-05-16 15:39 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +          "microservice": ".body.service"
Yes that's correct

2023-05-16 16:04 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +  "security": {}
Unlike the other platforms that provide a mechanism to verify the webhook payload, there isn't much information on how to achieve the same on Datadog's documentation. A substitute will be to leverage their **Custom Header** section when creating the webhook.
![image](https://github.com/port-labs/port-docs/assets/15999660/e839df9e-8f0b-4bb1-9b06-f962f8fbf763)

From the image above, the user can hash a webhook secret using a hashing algorithm such as the sha256. This value is then passed to the custom header as a property in Datadog. The user can then provide the security configuration in Port as follows:

  ```
  "security": {
    "secret": "WEBHOOK_SECRET_IN_PLAIN_TEXT",
    "signatureHeaderName": "X-Port-Signature",
    "signatureAlgorithm": "sha256"
  }
```

2023-05-17 07:24 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +  "security": {}
Then let's just skip the security section for this doc

2023-05-17 08:15 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/datadog/_example_datadog_webhook_configuration.mdx
> +  "security": {}
sure, I've removed it then

2023-05-17 09:33 UTC, MPTG94 approved these changes
LGTM

2023-05-17 10:03 UTC, merged