CloudBuild Trigger - Report Build Status
port-labs/port-docs pull request #341
Opened 2023-05-23 16:08 UTC by PeyGis

# Description

This update reports CloudBuild pipeline run status to Port.
## Added docs pages

docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md

2023-05-24 12:32 UTC, matarpeles requested changes

2023-05-24 12:32 UTC, matarpeles commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +Once you have triggered your CloudBuild pipeline successfully, it is essential to update the status of the run action in Port. This update allows Port to monitor the status of your CloudBuild pipelin
new line between the "This" line and "To report" line

2023-05-24 12:32 UTC, matarpeles commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
>  You can also follow the sample project on how to integration Cloud Build with Port.
Like my comment above, 

maybe change this to something like: 

"For more information, visit:"
* Cloudbuild example repository
* [updating an action run](../../reflect-action-progress/reflect-action-progress.md#updating-an-action-run)

2023-05-24 12:35 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +Once you have triggered your CloudBuild pipeline successfully, it is essential to update the status of the run action in Port. This update allows Port to monitor the status of your CloudBuild pipelin
You mean I should add a new line between these sentences?

2023-05-24 12:38 UTC, matarpeles commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +Once you have triggered your CloudBuild pipeline successfully, it is essential to update the status of the run action in Port. This update allows Port to monitor the status of your CloudBuild pipelin
yes, so it will begin a new sentence, not critical just think it looks better :)

2023-05-24 12:39 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md
> +Once you have triggered your CloudBuild pipeline successfully, it is essential to update the status of the run action in Port. This update allows Port to monitor the status of your CloudBuild pipelin
gotcha

2023-05-25 08:15 UTC, matarpeles commented
Looks good to me :)

2023-05-29 11:17 UTC, merged