GO connection to  Port Documentation
port-labs/port-docs pull request #354
Opened 2023-06-01 03:59 UTC by Samuelseggs

# Description

This documentation shows how to ingest GO dependencies into Port

## Added docs pages

Please also include the path for the added docs

  - Quickstart (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md`)
- Blueprint (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/go/_example_go_blueprint.mdx`)
- Webhook (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/go/_example_go_webhook_configuration.mdx`)
- Bash(`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/go/_example_go_bash.mdx`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-06-07 07:27 UTC, danielsinai requested changes
Good work, please fix the comments

2023-06-07 07:27 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +<summary>GO Bash configuration</summary>
Go Bash Script*

2023-06-07 07:27 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +    ```json showLineNumbers
why json here?

2023-06-07 07:27 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +    ```json showLineNumbers
also here

2023-06-07 07:27 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +Done! After the script has run, you should see a new file in your project root named output.json containing the parsed go.mod data. The script also prints the HTTP response code after attempting to s
Don't explain about the output json, maybe explain it in a tip

Here just write that it autootically ingests it to Port via HTTP request

2023-06-07 09:56 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +<summary>GO Bash configuration</summary>
This is corrected in my next commit

2023-06-07 09:57 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +    ```json showLineNumbers
This is corrected

2023-06-07 09:57 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +Done! After the script has run, you should see a new file in your project root named output.json containing the parsed go.mod data. The script also prints the HTTP response code after attempting to s
This change is completed

2023-06-14 08:47 UTC, MPTG94 requested changes
Please fix comments

2023-06-14 08:47 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +2. Make the script executable. For instance, if you named the script parse_and_send.sh, you would use the following command;
```suggestion
2. Make the script executable. For instance, if you named the script `parse_and_send.sh`, use the following command:
```

2023-06-14 08:47 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +Done! After the script has run, it will automatically injest Go packages into Port via HTTP Request
```suggestion
Done! After the script completes, You will see Go dependency entities in Port.
```

2023-06-14 08:47 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +Create the following blueprint definitions and webhook configuration:
Add a :::note block specifying the different unique commands the script will use (I noticed jq and mapfile)

2023-06-14 10:46 UTC, MPTG94 requested changes
Some more small fixes

2023-06-14 10:46 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +- `mapfile -t` reads lines into an array from the `go.mod` file, creating a collection for iteration.
It is not necessary to explain what the commands do, just to mention commands that might not be available in the user's shell by default and will require installation (sed, tail, head etc. are always available, but `jq` might not be on some shells so it is worth mentioning is. I noticed that `mapfile` is also unavailable for me so it is also worth mentioning)

2023-06-14 10:46 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +description: Ingest Go Modules and dependencies into your catalog
```suggestion
description: Ingest Go modules and dependencies into your catalog
```

2023-06-14 10:46 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md
> +<summary>Go Bash Script</summary>
```suggestion
<summary>Go bash script</summary>
```

2023-06-18 08:42 UTC, merged