This documentation shows how to import historical data from PagerDuty…
port-labs/port-docs pull request #358
Opened 2023-06-02 09:52 UTC by Samuelseggs

… to Port

# Description

This documentation guides you on how to use the provided Bash script to fetch data from the PagerDuty API and push it to the Port platform. The script extracts services and incidents from PagerDuty, and sends them to Port as Microservice and Incident entities respectively.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Webhooks (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/pagerduty/_example_pagerduty_webhook_history_config.mdx`)
- Bash (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/pagerduty/_example_pagerduty_shell_history_config.mdx`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- `docs (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md`)
- ...

2023-06-07 07:14 UTC, danielsinai requested changes
Good work please fix the comments

2023-06-07 07:14 UTC, danielsinai commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +<PagerDutyWebhookShellConfig/>
Call it PagerDutyScript, any way is needed (Title, filename, here etc)

2023-06-07 07:14 UTC, danielsinai requested changes
Good work please fix the comments

2023-06-08 15:51 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +This documentation guides you on how to use the provided Bash script to fetch data from the PagerDuty API and push it to the Port platform. The script extracts services and incidents from PagerDuty,
Done

2023-06-08 15:53 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +There are slight changes to the webhook, and since is probably a one time run, you may want to start off running this to import all your incidents and services into Port
I used an existing data from port, and it does not have the properties listed in the old webhook configuration. For example 

`{
    "services": [
        {
            "id": "PWJAGSD",
            "name": "Port Internal Service",
            "description": "Description for test service",
            "created_at": "2023-05-15T16:55:46+03:00",
            "updated_at": "2023-05-15T21:38:20+03:00",
            "status": "warning",
            "teams": [],
            "alert_creation": "create_alerts_and_incidents",
            "addons": [],
            "scheduled_actions": [],
            "support_hours": null,
            "last_incident_timestamp": "2023-05-15T17:57:11Z",
            "escalation_policy": {
                "id": "P7LVMYP",
                "type": "escalation_policy_reference",
                "summary": "Test Escalation Policy",
                "self": "https://api.pagerduty.com/escalation_policies/P7LVMYP",
                "html_url": "https://getport-io.pagerduty.com/escalation_policies/P7LVMYP"
            },
            "incident_urgency_rule": {
                "type": "constant",
                "urgency": "high"
            },
            "acknowledgement_timeout": null,
            "auto_resolve_timeout": null,
            "integrations": [],
            "type": "service",
            "summary": "Port Internal Service",
            "self": "https://api.pagerduty.com/services/PWJAGSD",
            "html_url": "https://getport-io.pagerduty.com/service-directory/PWJAGSD"
        },
        {
            "id": "P69HX03",
            "name": "Port Outbound Service",
            "description": "Writing test integration with Port",
            "created_at": "2023-05-15T21:10:56+03:00",
            "updated_at": "2023-05-15T21:38:56+03:00",
            "status": "warning",
            "teams": [],
            "alert_creation": "create_alerts_and_incidents",
            "addons": [],
            "scheduled_actions": [],
            "support_hours": null,
            "last_incident_timestamp": "2023-05-15T18:36:51Z",
            "escalation_policy": {
                "id": "P7LVMYP",
                "type": "escalation_policy_reference",
                "summary": "Test Escalation Policy",
                "self": "https://api.pagerduty.com/escalation_policies/P7LVMYP",
                "html_url": "https://getport-io.pagerduty.com/escalation_policies/P7LVMYP"
            },
            "incident_urgency_rule": {
                "type": "constant",
                "urgency": "high"
            },
            "acknowledgement_timeout": null,
            "auto_resolve_timeout": null,
            "integrations": [],
            "type": "service",
            "summary": "Port Outbound Service",
            "self": "https://api.pagerduty.com/services/P69HX03",
            "html_url": "https://getport-io.pagerduty.com/service-directory/P69HX03"
        }
    ],
    "limit": 25,
    "offset": 0,
    "total": null,
    "more": false
}`

2023-06-08 15:53 UTC, Samuelseggs commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +This script fetches services and incidents from PagerDuty and sends them to Port.
Done

2023-06-14 11:17 UTC, MPTG94 requested changes
Please fix comments

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +We will continue utilizing the same blueprint mentioned earlier to create the following webhook configuration.
```suggestion
This example will use the same blueprint provided in the [Prerequisites](ADD DEEPLINK TO THE PREVIOUS PREREQUISITES SECTION HERE) section of the previous example. In addition, the example will use the following webhook configuration:
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +1. PD_TOKEN: Your PagerDuty API token.
```suggestion
1. `PD_TOKEN`: your PagerDuty API token;
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +2. PORT_URL: Your Port webhook URL.
```suggestion
2. `PORT_URL`: your Port webhook URL.
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/pagerduty/_example_pagerduty_shell_history_config.mdx
> +```json showLineNumbers
```suggestion
```bash showLineNumbers
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +Then run this
```suggestion
Then trigger the script by running:
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +```json showLineNumbers
```suggestion
```bash showLineNumbers
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +The script writes the JSON payload for each service and incident to a file named output.json. This can be useful for debugging if you encounter any issues.
```suggestion
The script writes the JSON payload for each service and incident to a file named `output.json`. This can be useful for debugging if you encounter any issues.
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +Done! you can now pull out your historical data into Port. Port will parse the events according to the mapping and update the catalog entities accordingly.
```suggestion
Done! you can now import historical data from PagerDuty into Port. Port will parse the events according to the mapping and update the catalog entities accordingly.
```

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/pagerduty/_example_pagerduty_webhook_history_config.mdx
> +  "identifier": "pagerdutyMapper",
I think it is better for this mapper to use a different identifier to avoid a case where a customer overwrites his existing mapping.

2023-06-14 11:17 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/pagerduty/_example_pagerduty_webhook_history_config.mdx
> +```json showLineNumbers
Need to include a block here mentioning the need to update the `WEBHOOK_SECRET` value after creating the webhook in pagerduty, take a look at the configuration that already appears in this doc page and copy the text from there

2023-06-14 14:06 UTC, MPTG94 requested changes
Added another comment

2023-06-14 14:06 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md
> +:::note
Remove this note

2023-06-18 14:57 UTC, merged