Software Packages
port-labs/port-docs pull request #369
Opened 2023-06-08 15:00 UTC by PeyGis

# Description

Added a new section (Packages) under the webhook section to catalog how developers can ingest third-party dependencies and packages to Port

## Added docs pages

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages.md

2023-06-19 11:16 UTC, MPTG94 requested changes
Please fix comments before asking for another review

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/javascript.md
> +## Working with Port's API
```suggestion
## Working with Port's API and Bash script
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/python.md
> +In this example you are going to create `package` blueprint that ingests all third party dependencies and libraries in your requirements.txt file using a combination of REST API and Webhook. You will
```suggestion
In this example you are going to create a `package` blueprint that ingests all third party dependencies and libraries in your `requirements.txt` file using a combination of Port's API and webhook functionality. You will then relate this blueprint to a `service` blueprint, allowing you to map all the packages used by a service.

To ingest the packages to Port, a script that sends information about packages according to the webhook configuration is used.
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/python.md
> +## Working with Port's API
```suggestion
## Working with Port's API and Bash script
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/python.md
> +For more information on how to adapt this tutorial with your existing Gitlab CI pipelines, visit:
```suggestion
For an example showing how to integrate the above scripts with your existing Gitlab CI pipelines, visit:
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/golang/_example_package_blueprint.mdx
> +      "packageamNe": {
```suggestion
      "packageName": {
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/python/_example_package_webhook_config.mdx
> +  "description": "A webhook configuration to map software package file",
```suggestion
  "description": "A webhook configuration to map packages and dependencies from a file",
```

2023-06-19 11:16 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/golang/_example_package_webhook_config.mdx
> +  "description": "A webhook configuration to map Go dependencies to Port",
```suggestion
  "description": "A webhook configuration to map packages and dependencies from a file,
```

2023-06-19 15:21 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/_category_.json
> +  "position": 0
Since this one has a list of packages, I thought bringing it up would be relatively easier for the user (navigation-wise) than taking it to the bottom

2023-06-21 10:06 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/go.md
> +## Working with Port's API and Bash Script
@Samuelseggs in your Go packages, can you write a sample Python script just like you did for the shell script?

2023-06-23 14:51 UTC, MPTG94 requested changes
Fix the comment about the relative links and then I'll merge

2023-06-23 14:51 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/go.md
> +In this example you are going to create a `package` blueprint that ingests Go modules, versions and dependencies using a combination of Port's [API](https://docs.getport.io/build-your-software-catalo
Use relative link to page, and not hardcoded full URL (for example use ../../api/api.md - that might not be the real path, I am just providing it as an example)

2023-06-23 14:51 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/javascript.md
> +In this example you are going to create a `package` blueprint that ingests all third party dependencies and libraries in your `package.json` file using a combination of Port's [API](https://docs.getp
Use relative link to page, and not hardcoded full URL (for example use ../../api/api.md - that might not be the real path, I am just providing it as an example)

2023-06-23 14:51 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/python.md
> +In this example you are going to create a `package` blueprint that ingests all third party dependencies and libraries in your `requirements.txt` file using a combination of Port's [API](https://docs.
Use relative link to page, and not hardcoded full URL (for example use ../../api/api.md - that might not be the real path, I am just providing it as an example)

2023-06-23 18:58 UTC, MPTG94 approved these changes
LGTM

2023-06-23 18:58 UTC, merged