Add Checkmarx scan results to Port
port-labs/port-docs pull request #439
Opened 2023-07-17 16:27 UTC by PeyGis

# Description

Add checkmarx scan reports to Port

## Added docs pages

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/checkmarx.md
        docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/checkmarx/

2023-07-20 12:43 UTC, EllaFurman requested changes

2023-07-20 12:43 UTC, EllaFurman commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/checkmarx.md
> +In this example you are going to create a `checkmarxScan` blueprint that ingests all scan results in your Checkmarx KICS file using a combination of Port's [API](../../../api/api.md) and [webhook fun
```suggestion
In this example, you will create a `checkmarxScan` blueprint that ingests all scan results in your Checkmarx KICS file using a combination of Port's [API](../../../api/api.md) and [webhook functionality](../../webhook.md).
```

2023-07-20 12:43 UTC, EllaFurman commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/checkmarx.md
> +To ingest the scan results to Port, a script that sends information about the scans according to the webhook configuration is used.
```suggestion
To ingest the scan results to Port, use a script that sends information about the scans according to the webhook configuration.
```

2023-07-23 08:37 UTC, danielsinai approved these changes

2023-07-23 08:38 UTC, merged