Update Terraform guide for GCP to work with current version of provider
port-labs/port-docs pull request #734
Opened 2023-12-14 19:20 UTC by tcaddy

# Description

Update Terraform guide for GCP to work with current version of provider.

The docs are out of date and do not work with the current TF provider for Port.

I'm not sure exactly how correct I got everything, as I'm brand new to Port.  But at least we can TF plan/apply without error.

## Updated docs pages
- `docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md`

2023-12-17 11:09 UTC, Tankilevitch requested changes
Thx for contributing @tcaddy, 
Minor thing I found while while I was looking at the terraform docs is that the properties keys should be [x_props](https://registry.terraform.io/providers/port-labs/port-labs/latest/docs/resources/port_blueprint#nestedatt--properties)  ( e.g instead of string_items => string_props ).

Note that the `x_items` is when specifying [array_props](https://registry.terraform.io/providers/port-labs/port-labs/latest/docs/resources/port_blueprint#nested-schema-for-propertiesarray_props)

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    }
same

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      link = {
```suggestion
    string_props = {
      link = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    string_items = {
```suggestion
    string_props = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      link = {
```suggestion
  properties = {
    string_props = {
      link = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    object_items = {
```suggestion
    }
    object_props = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      labels = each.value.labels
```suggestion
    object_props = {
      labels = each.value.labels
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    }
```suggestion
  properties = {
    string_props = {
      name = {
        title = "name"
      }
      assetType = {
        title = "Asset Type"
      }
      description = {
        title = "Description"
      }
      location = {
        title = "Location"
      }
    }
    object_props = {
      labels = {}
      additionalAttributes = {
        title = "Additional Attributes"
      }
      networkTags = {
        title = "NetworkTags"
      }
    }
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      labels               = each.value.labels
```suggestion
    }
    object_props = {
      labels               = each.value.labels
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    string_items = {
```suggestion
  properties = {
    string_props = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      link = {
```suggestion
  properties = {
    string_props = {
      link = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +    }
```suggestion
  properties = {
    string_props = {
      link = {
        title  = "Link"
        format = "url"
      }
      number = {
        title = "Number"
      }
      "createTime" = {
        title  = "Create Time"
        format = "date-time"
      }
    }
    object_props = {
      labels = {}
    }
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      labels = each.value.labels
```suggestion
    object_props = {
      labels = each.value.labels
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      networkTags = {
```suggestion
    string_props = {
      name = {
        title = "name"
      }
      assetType = {
        title = "Asset Type"
      }
      description = {
        title = "Description"
      }
      location = {
        title = "Location"
      }
    }
    object_props = {
      labels = {}
      additionalAttributes = {
        title = "Additional Attributes"
      }
      networkTags = {
```

2023-12-17 11:09 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
> +      networkTags          = each.value.network_tags
```suggestion
    string_props = {
      name        = each.value.name
      assetType   = each.value.asset_type
      description = each.value.description
      location    = each.value.location
    }
    object_props = {
      labels               = each.value.labels
      additionalAttributes = each.value.additional_attributes
      networkTags          = each.value.network_tags
```

2023-12-26 18:19 UTC, hadar-co commented
@tcaddy Hi:)
Did you get a chance to look at @Tankilevitch 's comments?

2024-01-03 14:58 UTC, closed without merging