added gitlab tabs for gitops enrichment
port-labs/port-docs pull request #749
Opened 2023-12-20 14:40 UTC by OmriGez

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-12-21 14:19 UTC, hadar-co requested changes

2023-12-21 14:19 UTC, hadar-co commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +1. Under your root group, access Settings, Access Tokens, and create a `Maintainer` role token with the following scopes:
```suggestion
1. Under your root group, access [Settings](ADD LINK HERE)->Access Tokens, and create a `Maintainer` role token with the `api`, `read-repository`, and `write-repository` scopes. Copy the token's value.
```

2023-12-21 14:19 UTC, hadar-co commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +- PORT_CLIENT_ID - Taken from Port
Instead of "Taken from Port", we need to tell the user how to get the credentials. See other guides, you can copy from there

2023-12-24 09:58 UTC, OmriGez reviewed
@hadar-co 
About this one. GitLab's settings URL is tied to the group name.
For example, this is ours
https://gitlab.com/groups/getport-labs/-/settings/ci_cd
I believe adding a link will cause confusion, as people are supposed to know where this stuff is.

2023-12-24 10:08 UTC, OmriGez commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +- PORT_CLIENT_ID - Taken from Port
I have added a small TIP section inside the tab.
 see latest commit

2023-12-24 10:09 UTC, OmriGez commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +1. Under your root group, access Settings, Access Tokens, and create a `Maintainer` role token with the following scopes:
fixed in the latest commit to match how it looks in gitlab

2023-12-24 10:09 UTC, OmriGez commented on docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
> +   - Endpoint URL: https://gitlab.com/api/v4/projects/(PROJECT_ID)/ref/main/trigger/pipeline?token=(INSERT_TRIGGER_TOKEN)
I have seen you added a section about it to the INFO window, so this should be fine now

2024-01-03 13:46 UTC, closed without merging