PORT-5608 Python Script for Ingesting JFrog Container Images in Port with and keep them updated using Webhook Integration
port-labs/port-docs pull request #757
Opened 2023-12-21 21:53 UTC by lordsarcastic

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- JFrog (Self-Hosted and Cloud) (`/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog`)

2023-12-24 08:17 UTC, hadar-co requested changes

2023-12-24 08:17 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog.md
> +Create the following webhook configuration [using Port UI](../../?operation=ui#configuring-webhook-endpoints)
@lordsarcastic 
1. I'm not sure where this link is supposed to send the reader?
2. From now on please use full path links and not relative ones.

2023-12-24 08:17 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog.md
> +# JFrog (Self-Hosted and Cloud)
@lordsarcastic 
The title should be "JFrog", without the (Self-Hosted and Cloud).
If there is a difference between them, please address that in the page where it's relevant

2023-12-26 18:21 UTC, hadar-co commented
@lordsarcastic Hi, have you had a chance to look at the comments?

2023-12-28 08:59 UTC, lordsarcastic commented
> @lordsarcastic Hi, have you had a chance to look at the comments?

Yes I'll attend to it once I'm done with a pending task

2023-12-28 23:45 UTC, lordsarcastic commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog.md
> +Create the following webhook configuration [using Port UI](../../?operation=ui#configuring-webhook-endpoints)
I followed the convention from other documentations as regards creating webhook configurations. Still want me to change it?

2024-01-02 08:06 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog.md
> +Create the following webhook configuration [using Port UI](../../?operation=ui#configuring-webhook-endpoints)
@lordsarcastic just change the links to be full path and not relative:)

2024-01-02 08:07 UTC, hadar-co commented
@lordsarcastic just change the links to be full path and not relative:)

2024-01-04 07:13 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jfrog.md
> +Create the following webhook configuration [using Port UI](build-your-software-catalog/sync-data-to-catalog/webhook/?operation=ui#configuring-webhook-endpoints)
```suggestion
Create the following webhook configuration [using Port UI](/build-your-software-catalog/sync-data-to-catalog/webhook/?operation=ui#configuring-webhook-endpoints)
```

2024-01-04 07:16 UTC, merged