Create create-azure-resource.md
port-labs/port-docs pull request #758
Opened 2023-12-22 16:19 UTC by phalbert

# Description

This guide has an example resource in Azure using Terraform. This is executed with a Jenkins pipeline.

## Added docs pages

Please also include the path for the added docs

- Create resource in Azure Cloud with Terraform (`./create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource`)

2023-12-22 16:47 UTC, phalbert commented
Need to use port terraform provider

2023-12-24 12:30 UTC, MPTG94 requested changes
Please make changes according to the comments

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        3. `ARM_SUBSCRIPTION_ID` - Azure Subscription ID.
Does Azure have some documentation guide showing where to get this information? If there, let's add a link here, same for `ARM_TENANT_ID`

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +2. Create a Port blueprint with the following properties:
Add a tooltip on the word blueprint, similar to how it's done in the quickstart: https://docs.getport.io/quickstart#4-set-standards-using-scorecards

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +3. Create Port Action from [here](https://app.getport.io/self-serve) using the following JSON definition:
```suggestion
3. Create a Port Action in the [self-service hub](https://app.getport.io/self-serve) using the following JSON definition:
```

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +Please make sure to modify JENKINS_HOST and TOKEN placeholders to match your environment.
```suggestion
Make sure to replace the placeholders for `JENKINS_URL` and `JOB_TOKEN`.
```

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +    "icon": "S3",
```suggestion
    "icon": "Azure",
```

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        stage('Terraform Azure') {
Are both this and the `Terraform Port` steps needed? it seems like they are doing pretty much the same thing, only one doesn't echo in the middle.

Can we remove one of them?

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +4. Create a Terraform templates in your GitHub repository:
```suggestion
4. Create a Terraform template in your GitHub repository:
```

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
This section requires a bit more of an explanation - outline ahead of the time what files are we going to create, why are we creating each one, and where in the repository are they expected to be

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
Add as a prerequisite a GitHub repository to contain the Terraform template files

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
You are also using the webhook plugin for Jenkins, so it also needs to be mentioned somewhere in the doc, see the example from here:
![image](https://github.com/port-labs/port-docs/assets/9868797/23eedafa-060a-41e9-bfe6-fffea24d8a4d)

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
This is taken from the Scaffold bitbucket repositories using cookiecutter doc

2023-12-24 12:30 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +:::tip
This tip block is unnecessary, please remove

2023-12-24 15:13 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +   1. Azure Credentials - This plugin provides the `Azure Service Principal` kind in Jenkins Credentials.
added

2023-12-24 15:25 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        3. `ARM_SUBSCRIPTION_ID` - Azure Subscription ID.
added

2023-12-24 15:25 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +2. Create a Port blueprint with the following properties:
added

2023-12-24 15:26 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +3. Create Port Action from [here](https://app.getport.io/self-serve) using the following JSON definition:
modified

2023-12-24 15:27 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +Please make sure to modify JENKINS_HOST and TOKEN placeholders to match your environment.
Oh, naming it `JOB_TOKEN` is better. modified this too

2023-12-24 15:31 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        stage('Terraform Azure') {
I have revised this now

2023-12-24 16:44 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +4. Create a Terraform templates in your GitHub repository:
revised this

2023-12-24 16:44 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
That's correct. It helps to outline what the files are for. I will add this.

2023-12-24 16:45 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +
Alright, I have done this.

2023-12-24 16:45 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +:::tip
I have removed it now.

2023-12-25 08:24 UTC, MPTG94 requested changes
Please see my additional comments

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        1. `PORT_CLIENT_ID` - Port Client ID [learn more](../../../../build-your-software-catalog/sync-data-to-catalog/api/#get-api-token).
These URLs do not work, please use absolute paths (start from `/build-your-software-catalog`) and make sure the URLs work

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +   2. [Terraform Plugin](https://plugins.jenkins.io/terraform/)
Please add a short description for these two plugins as well

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        :::info NOTE
```suggestion
        :::tip
```

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +3. Create a Port Action in the [self-service hub](https://app.getport.io/self-serve) using the following JSON definition:
```suggestion
3. Create a Port action in the [self-service hub](https://app.getport.io/self-serve) using the following JSON definition:
```

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +    "icon": "S3",
@phalbert please apply the fix to the icon

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +    2. `variables.tf` – This file will contain the variable declarations that will be used in the resource blocks e.g. the port credentials and port run id.
```suggestion
    2. `variables.tf` – This file will contain the variable declarations that will be used in the resource blocks e.g. the Port credentials and Port run id.
```

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +    3. `output.tf` – This file will contain the url of the Storage Account that needs to be generated on successful completion of “apply” operation. This url will be used in the `endpoint` property w
```suggestion
    3. `output.tf` – This file will contain the URL of the Storage Account that needs to be generated on successful completion of an “apply” operation. This URL will be used in the `endpoint` property when creating the Port entity.
```

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +  ```yaml
Please make sure **all** codeblocks have `showLineNumbers` in them

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +  :::note
Move the `:::note` block underneath the `<summary>` tag, it doesn't change to how the markdown renders but it makes it easier to edit the file in the future

2023-12-25 08:24 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +6. Trigger the action from the [Self-service](https://app.getport.io/self-serve) tab of your Port application.
```suggestion
6. Trigger the action from the [self-service](https://app.getport.io/self-serve) tab of your Port application.
```

2023-12-25 08:53 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        1. `PORT_CLIENT_ID` - Port Client ID [learn more](../../../../build-your-software-catalog/sync-data-to-catalog/api/#get-api-token).
Let me make certain all URLs work.

2023-12-25 08:58 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +   2. [Terraform Plugin](https://plugins.jenkins.io/terraform/)
I have added these descriptions.

2023-12-25 09:02 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +  ```yaml
Alright then.

2023-12-25 09:30 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +  :::note
I have moved it.

2023-12-25 10:48 UTC, MPTG94 requested changes
One last comment

2023-12-25 10:48 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        1. `PORT_CLIENT_ID` - Port Client ID [learn more](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/api/#get-api-token).
While the links work now, you should utilize the internal linking of the docs system.

Please change the link value to: `/build-your-software-catalog/sync-data-to-catalog/api/#get-api-token`

After that, verify that it works. Try to make the same use of absolute paths to other files in the docs project in the future.

The internal paths allow the linking to provide a better experience for people reading the docs, and using absolute paths (starting with `/` ) in the links makes it easier to move pages around

2023-12-25 11:02 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-azure-resource.md
> +        1. `PORT_CLIENT_ID` - Port Client ID [learn more](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/api/#get-api-token).
Thank you for this explanation. It make clear the reason for internal linking.

2023-12-25 12:10 UTC, MPTG94 approved these changes
LGTM

2023-12-25 12:15 UTC, merged