re-organzied port-agent and added argocd installation method
port-labs/port-docs pull request #762
Opened 2023-12-24 13:41 UTC by stavbernazport

# Description

re-organzied port-agent and added argocd installation method

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2023-12-24 15:37 UTC, hadar-co requested changes

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md
> +- [Usage](/create-self-service-experiences/self-service-actions-deep-dive/self-service-actions-deep-dive.md) guide Set up a webhook.
This is unclear - what is the step? The link just takes me to the deep dive page. Also, the sentence is incorrect - "Usage guide set up a webhook". Please revise:)

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md
> +Let's dive in to a walkthrough on how to install the Port execution agent in your Kubernetes cluster.
You used the same sentence here and in the Helm page. Perhaps let's change it to something like:
This page will walk you through the installation of the Port execution agent in your Kubernetes cluster using ArgoCD.

And let's use the same format in the Helm page.

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +Let's dive in to a walkthrough on how to install the Port execution agent in your Kubernetes cluster.
See comment in argocd.md line 7

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md
> +  ArgoCD's [documentation](https://argo-cd.readthedocs.io/en/stable/) for further details on the installation;
```suggestion
- [ArgoCD](https://argoproj.github.io/cd/) must be installed in your Kubernetes cluster. Please refer to the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/) for further details about the installation.
```

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +- The [Helm](https://helm.sh) must be installed to use the chart. Please refer to
```suggestion
- [Helm](https://helm.sh) must be installed to use the chart. Please refer to
```

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +  the Helm's [documentation](https://helm.sh/docs) for further details on the installation;
```suggestion
  the [Helm documentation](https://helm.sh/docs) for further details about the installation.
```

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +## Installation
Move the "Installation" title up, it should be directly below the prerequisites like you did in argocd.md

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +- [Usage](/create-self-service-experiences/self-service-actions-deep-dive/self-service-actions-deep-dive.md) guide Set up a webhook.
See comment at the end of argocd.md

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/installation-methods.md
> +# Installation Methods
You can delete this page entirely, it isnt needed, the "Installation methods" can just be a category in the sidebar but without a page. If you're not sure how to do this talk to me:)

2023-12-24 15:37 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/port-execution-agent.md
> +- [Explore How to install and use the agent](/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/installation-methods.md)
If we remove the "Installation methods" page like i suggested in my previous comment, this link will not work. So we can replace it with 2 links - one for Helm and one for ArgoCD.

2023-12-24 16:42 UTC, MPTG94 requested changes
Please go over both my comments and Hadar's

2023-12-24 16:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +You can observe the helm chart with the full installation [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```suggestion
You can observe the helm chart and the available parameters [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
```

2023-12-24 16:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +helm repo add port-labs https://port-labs.github.io/helm-charts
Let's add both the `add` and the `repo update` commands in the same code block. I don't want to rely on the user to remember that he installed in the past

2023-12-24 16:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
> +If you already added this repo earlier, run `helm repo update` to retrieve
We can remove this part completely after adding the `helm repo update` command to the above code block

2023-12-24 16:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md
> +You can observe the helm chart with the full installation [here](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent).
I altered the sentence slightly in the comment on the helm page, let's apply it here too

2023-12-25 14:16 UTC, hadar-co approved these changes

2023-12-25 14:16 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md
> +- Refer to the [Usage](/create-self-service-experiences/setup-backend/webhook/port-execution-agent/usage.md) guide Set up a webhook.
```suggestion
- Refer to the [usage guide](/create-self-service-experiences/setup-backend/webhook/port-execution-agent/usage.md) to set up a webhook.
```

2023-12-25 14:29 UTC, merged