Add a guide for creating PRs with jenkins pipeline
port-labs/port-docs pull request #779
Opened 2023-12-27 10:41 UTC by phalbert

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Create pull request (`/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md`)

## Updated docs pages

Please also include the path for the updated docs

- Deploy resource in Azure Cloud with Terraform (`/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/deploy-azure-resource.md`)

2023-12-27 20:43 UTC, MPTG94 requested changes
Please fix my comments and I'll review again

2023-12-27 20:43 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +After creating an action, it will appear under the `Self-service` tab of your Port application:
This image shows the action after selecting it from the hub, it might be worth showing its box in the hub itself

2023-12-27 20:43 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +- You will need to have [Port's Github app](https://github.com/apps/getport-io) installed in your Github organization (the one that contains the repository you'll work with).
Reading the guide, the github app doesn't seem like it is required

2023-12-28 09:29 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +   - Click `Next`:
alright then

2023-12-28 09:30 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +    - Go to your [Port application](https://app.getport.io/), hover over the `...` in the top right corner, then click `Credentials`. Copy your `Client ID` and `Client secret`. [Learn more](/build-yo
thank you for this tip. let me reuse that instead

2023-12-28 09:36 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +- In your Github repository, create a file named `create-azure-storage.tf` under `/templates/` (it's path should be `/templates/create-azure-storage.tf`).
Its the little things! I will be more aware of these going forward. Thanks.

2023-12-28 09:40 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +# create-azure-storage.tf
Alright then. I have standardised how I add file names now.

2023-12-28 09:51 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +- You will need to have [Port's Github app](https://github.com/apps/getport-io) installed in your Github organization (the one that contains the repository you'll work with).
I believe that I can omit the prerequisite information from this section. Once the user has followed the instructions in the quickstart guide to set up a `Service` blueprint, they will have already fulfilled those prerequisites.

2023-12-28 12:05 UTC, MPTG94 requested changes
Reviewed again with some comments

2023-12-28 12:05 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +- You will need to have [Port's Github app](https://github.com/apps/getport-io) installed in your Github organization (the one that contains the repository you'll work with).
I think having a prerequisite section is good, it should just be precise and not ask for things that the user does not really need to set up

2023-12-28 17:21 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +   :::tip
alright, let me do that

2023-12-28 17:24 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/create-pull-request.md
> +- You will need to have [Port's Github app](https://github.com/apps/getport-io) installed in your Github organization (the one that contains the repository you'll work with).
Are we good then with how it looks now?

2023-12-28 17:48 UTC, MPTG94 approved these changes
Nice work!

2023-12-28 17:51 UTC, merged