PORT-5882 Add Wiz integration guide
port-labs/port-docs pull request #802
Opened 2024-01-05 14:24 UTC by phalbert

# Description

This is the documentation of the [Wiz integration](https://github.com/port-labs/ocean/pull/306)

## Added docs pages

Please also include the path for the added docs

- Wiz Integration (`/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md`)

2024-01-05 17:34 UTC, PeyGis requested changes

2024-01-05 17:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +| `port.clientSecret`                 | Your port client secret                                                                                            | ✅       |
We typically add a link to where they can get their Port client it and secret, just like you've done it at the Jenkinsfile section below

Your port client id ([How to get the credentials](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/api/#find-your-port-credentials))

2024-01-05 17:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +- Create/delete Wiz objects using self-service actions.
Not sure but does the wiz ocean integration have the capacity to trigger self-service actions?

2024-01-05 17:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +        --set integration.config.wizWebhookToken="WIZ_WEBHOOK_TOKEN"
As part of the helm installation command, we typically show only the required config params. This means you'll have to remove webhookToken from it since you've specified it as not required above

2024-01-05 17:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +                        string(credentialsId: 'OCEAN__INTEGRATION__CONFIG__WIZ_WEBHOOK_TOKEN', variable: 'OCEAN__INTEGRATION__CONFIG__WIZ_WEBHOOK_TOKEN'),
same comment on the inclusion of the webhook token since it's optional

2024-01-05 17:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +            # https://integrate.wiz.io/reference/issues-query#:~:text=Direct%20a%20user%20to%20an%20Issue%20in%20Wiz
remove this commented line

2024-01-07 20:17 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +| `port.clientSecret`                 | Your port client secret                                                                                            | ✅       |
noted

2024-01-07 20:18 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +- Create/delete Wiz objects using self-service actions.
Oh, let me remove that.

2024-01-07 20:20 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +        --set integration.config.wizWebhookToken="WIZ_WEBHOOK_TOKEN"
alright

2024-01-07 20:21 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +                        string(credentialsId: 'OCEAN__INTEGRATION__CONFIG__WIZ_WEBHOOK_TOKEN', variable: 'OCEAN__INTEGRATION__CONFIG__WIZ_WEBHOOK_TOKEN'),
okay then

2024-01-07 20:21 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
> +            # https://integrate.wiz.io/reference/issues-query#:~:text=Direct%20a%20user%20to%20an%20Issue%20in%20Wiz
alright

2024-01-10 08:55 UTC, hadar-co approved these changes

2024-01-10 08:59 UTC, merged