PORT-5801 Add guide for Azure devops terraform pipeline
port-labs/port-docs pull request #816
Opened 2024-01-10 11:11 UTC by phalbert

# Description

Added a guide for a self-service action that triggers an Azure Devops pipeline to deploy a storage account using `terraform apply`

## Added docs pages

Please also include the path for the added docs

- Create Azure Resource (`/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md`)

2024-01-11 07:54 UTC, hadar-co requested changes

2024-01-11 07:54 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +In the following guide, you are going to build a self-service action in Port that [executes](/create-self-service-experiences/setup-backend/azure-pipeline/azure-pipeline.md) an Azure pipeline to depl
the link here should be "Azure pipeline" instead of "executes"

2024-01-11 07:54 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +2. Create a Port <PortTooltip id="blueprint">blueprint</PortTooltip> with the following properties:
```suggestion
2. Create a Port <PortTooltip id="blueprint">blueprint</PortTooltip> with the following JSON definition:
```

2024-01-11 07:54 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +3. Create a Port action in the [self-service hub](https://app.getport.io/self-serve) or with the following JSON definition:
```suggestion
3. Create a Port action in the [self-service page](https://app.getport.io/self-serve) with the following JSON definition:
```

2024-01-11 07:54 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/deploy-azure-resource.md
> +Please make sure to modify `YOUR_USERNAME` and `YOUR_REPO` placeholder in the URL of the git repository in the `Checkout` stage. Alternatively you can use our [example repository](https://github.com/
```suggestion
Please make sure to modify the `YOUR_USERNAME` and `YOUR_REPO` placeholders in the URL of the git repository in the `Checkout` stage. Alternatively you can use our [example repository](https://github.com/port-labs/pipelines-terraform-azure).
```

2024-01-12 01:12 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +2. Create a Port <PortTooltip id="blueprint">blueprint</PortTooltip> with the following properties:
done this. thank you.

2024-01-12 01:12 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +3. Create a Port action in the [self-service hub](https://app.getport.io/self-serve) or with the following JSON definition:
added this.

2024-01-12 01:15 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md
> +In the following guide, you are going to build a self-service action in Port that [executes](/create-self-service-experiences/setup-backend/azure-pipeline/azure-pipeline.md) an Azure pipeline to depl
alright then

2024-01-12 01:19 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/deploy-azure-resource.md
> +Please make sure to modify `YOUR_USERNAME` and `YOUR_REPO` placeholder in the URL of the git repository in the `Checkout` stage. Alternatively you can use our [example repository](https://github.com/
this was an old piece I removed.

2024-01-14 09:30 UTC, merged