Snyk Organization Support
port-labs/port-docs pull request #838
Opened 2024-01-16 16:20 UTC by PeyGis

# Description

We have improved on the way in which users export the Snyk ocean integration. With this updates, users can fetch multiple organization's data into Port with one installation.

## Updated docs pages

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md

2024-01-16 16:57 UTC, Tankilevitch requested changes
Nice job

Still some changes required.
Also the integration guide misses any information about what will be the default behavior of the installations and how to manage it, I think it require a section of its own.

2024-01-16 16:57 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md
> +    groups: SNYK_GROUPS  ## Required when you want to fetch data for all organizations within the specified group(s)
I think the default should be without those options, and rather have in the note / guide on where to add it if they want to manage the scope which the integration will have access to

2024-01-16 16:57 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md
> +| `OCEAN__INTEGRATION__CONFIG__ORGANIZATION_ID` | The Snyk organization ID
It is unclear why and when to use it. You want to emphasis that it should be passed if wanting to restrict the access to specific organizationId, do the same for the groups config.

2024-01-17 08:12 UTC, Tankilevitch requested changes

2024-01-17 08:12 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md
> +
I think this should be before the installation

2024-01-17 11:51 UTC, Tankilevitch requested changes

2024-01-17 11:51 UTC, Tankilevitch commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md
> +
This should be inside the installation section.

Please make sure that it aligned for each kind of the installations with the right params and where to set them.

2024-01-17 14:48 UTC, Tankilevitch approved these changes

2024-01-17 14:54 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md
>  :::note
Please add a title for the admonition (and for all future admonitions), it makes it more inviting to actually read it and not skip it.

:::note title-here
content
:::

2024-01-17 15:26 UTC, hadar-co approved these changes

2024-01-17 15:43 UTC, merged