Add guide for github workflow to terraform azure resources
port-labs/port-docs pull request #846
Opened 2024-01-18 14:23 UTC by phalbert

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Deploy Azure Resource using Terraform (`/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md`)

2024-01-19 15:49 UTC, PeyGis requested changes

2024-01-19 15:49 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +1. Create the following GitHub action secrets:
GitHub **Action**

2024-01-19 15:49 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +    "identifier": "github_terraform",
You can make the identifier descriptive such as create_azure_storage
Same applies to the title of the Action blueprint

2024-01-19 16:10 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +    "identifier": "github_terraform",
Alright

2024-01-22 16:29 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +    1. Create the Port credentials.
```suggestion
    1. Create the following Port credentials:
```

2024-01-22 16:29 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +    2. Create the Azure Cloud credentials.
```suggestion
    2. Create the following Azure Cloud credentials:
```

2024-01-22 16:29 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +
The whole text is very crowded, please add a line of space between each article(1-6)

2024-01-22 16:41 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +
@hadar-co , do you mean `<br />`?

2024-01-22 16:43 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-azure-resource.md
> +
yes exactly

2024-01-22 17:08 UTC, hadar-co approved these changes

2024-01-23 06:46 UTC, merged