Documentation for Dynatrace Ocean integration
port-labs/port-docs pull request #874
Opened 2024-01-31 15:31 UTC by lordsarcastic

# Description

Added documentation for Dynatrace integration. This is to complement the newly added Dynatrace ocean integration

## Added docs pages

- Dynatrace (`docs/build-your-software-catalog/sync-data-to-catalog/incident-management/dynatrace.md`)

2024-01-31 18:06 UTC, PeyGis requested changes
LGTM. One thing that is missing is information on how to configure the Dynatrace problem webhook. See how we have done it for [Opsgenie - configure real time updates](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie#configuring-real-time-updates)

2024-02-01 18:35 UTC, PeyGis requested changes

2024-02-01 18:35 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/dynatrace.md
> +Prepare a webhook `URL` using this format: `{app_host}/integration/events`. The `app_host` parameter should match the ingress or external load balancer where the integration will be deployed. For exa
Change the format to`{app_host}/integration/webhook` - consistent with the one you have in the Dynatrace main.py

Change this as well to https://myservice.domain.com/integration/webhook`

2024-02-01 18:35 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/dynatrace.md
> +   5. `Custom payload` - You can leave the default as is or customize to your taste, the only important thing is the `ProblemID` key. The webhook integration will not work without it.
Instead of leaving it blank, as them to copy and paste this configuration

{
   "ProblemID":"{PID}",
   "ProblemTitle":"{ProblemTitle}",
   "ImpactedEntities": {ImpactedEntities}
}

2024-02-02 17:42 UTC, PeyGis requested changes

2024-02-02 17:42 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/incident-management/dynatrace.md
> +4. Select Dynatrace under the Kubernetes Stack providers category.
Dynatrace should be under Incident Management category instead of Kubernetes Stack

2024-02-04 09:40 UTC, hadar-co approved these changes

2024-02-04 09:41 UTC, merged