Adding IAM permissions management use-case
port-labs/port-docs pull request #912
Opened 2024-02-18 15:24 UTC by MatanHeledPort

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Added docs pages

Please also include the path for the added docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

## Updated docs pages

Please also include the path for the updated docs

- Quickstart (`/`)
- Blueprint (`/platform-overview/port-components/blueprint`)
- ...

2024-02-18 16:02 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +# AWS IAM permission management
```suggestion
# AWS IAM Permission Management
```

2024-02-18 16:06 UTC, stavbernazport commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +- In your AWS console, [create an IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html) called `port-iam-management-user` with the following IAM permission policy:
```suggestion
- In your AWS console, [create an IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html) called `port-iam-management-user` with the following IAM permissions policy:
```

2024-02-18 16:08 UTC, stavbernazport requested changes
The structure looks good IMO.
Maybe save it as a template somewhere?

2024-02-20 15:00 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +- Prepare your Port organization's `Client ID` and `Client Secret`. To find you Port credentials, click [here](/docs/build-your-software-catalog/sync-data-to-catalog/api/api.md#find-your-port-credent
```suggestion
- Prepare your Port organization's `Client ID` and `Client Secret`. To find you Port credentials, click [here](/docs/build-your-software-catalog/sync-data-to-catalog/api/api.md#find-your-port-credentials).
```

2024-02-20 15:05 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +:::note
plz add a title to the admonition.
Consider using a type other than `note`, it is quite easy to miss.

2024-02-20 15:07 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +We want to be able to provision and revoke permissions for AWS resources from Port. To do so, we will need to create some [Port actions](/docs/create-self-service-experiences/create-self-service-expe
```suggestion
We want to be able to provision and revoke permissions for AWS resources from Port. To do so, we will need to create some [actions](/docs/create-self-service-experiences/create-self-service-experiences.md) in our Port organization, and set up some action backends.
```

2024-02-20 15:10 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +:::note
Title

2024-02-20 15:14 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +- ***Coming soon*⏱️: Temporary permissions using [Automations](https://roadmap.getport.io/ideas/p/automation) and the `Timer` property** - With the automations feature, you will be able to automatica
This is cool, but it's very easy to forget to change it, plz make sure you remember to come back here when the feature is ready

2024-02-20 20:45 UTC, MPTG94 reviewed
Please look at my comments

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +Click on the `...` at the top right of the entity screen -> click `Request permissions` -> choose the `s3:PutObject` -> click `Execute`.
```suggestion
Click on the `...` at the top right of the entity screen -> click `Request permissions` -> choose the `s3:PutObject` permission -> click `Execute`.
```

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +<img src='/img/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-provision-permissions-action.png' width='75%' border='1px' />
Can we add an image where the email address is something that maybe ends with getport.io?

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +When the Port action run will end, you will get actions logs showing you info regarding:
```suggestion
When the Port action run will end, you will get action logs which will show you info regarding:
```

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +Copy the sign-in URL and paste it tou your browser URL bar. Click the `Switch Role` button.
```suggestion
Copy the sign-in URL and paste it to your browser's URL bar. Click the `Switch Role` button. 
```

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +You are now signed in to your new role, which has permissions as defined the the Port action! 🥳
```suggestion
You are now signed in to your new role, which has permissions as defined in the Port action! 🥳
```

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +:::note
change to tip and add title - "about provisioned permissions"

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +When the Port action run will end, you will get actions logs showing you info regarding:
```suggestion
When the Port action run will end, you will get action logs which will show you info regarding:
```

2024-02-20 20:45 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +- ***Coming soon*⏱️: Temporary permissions using [Automations](https://roadmap.getport.io/ideas/p/automation) and the `Timer` property** - With the automations feature, you will be able to automatica
```suggestion
- ***Coming soon* ⏱️: Temporary permissions using [Automations](https://roadmap.getport.io/ideas/p/automation) and the `Timer` property** - With the automations feature, you will be able to automatically trigger actions using events from the catalog. You can use the `Timer Expired` event to trigger the `Revoke permissions` action and create a temporary permissions experience.
```

2024-02-21 06:42 UTC, MatanHeledPort commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +:::note
I think this is a note, if this gets missed it shouldn't affect the use-case. 
I the `Summary` section, I reference this again.

This isn't supposed to catch too much attention

2024-02-21 07:13 UTC, MatanHeledPort commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/iam-permissions-guide.md
> +                with:
Since this is Github actions, it will end automatically thanks to the integration. It's another block of code that is not really needed

2024-02-21 11:23 UTC, MPTG94 approved these changes
LGTM

2024-02-21 11:23 UTC, merged