LaunchDarkly Documentation
port-labs/port-docs pull request #931
Opened 2024-02-22 11:57 UTC by mk-armah

# Description

Added documentation for launchdarkly integration

- Launchdarkly Docs (`/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly`)
- ...

2024-02-22 12:50 UTC, PeyGis requested changes

2024-02-22 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +A `Project` in LaunchDarkly is analogous to a workspace in Terraform Cloud but tailored for feature flag management. Each project in LaunchDarkly is a collection of feature flags, targeting rules, an
Can you use a different analogy besides Terraform Cloud? or remove that sentence and go straight to the point? This may be confusing for user's who don't know anything about TF Cloud

2024-02-22 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +A `Flag` in LaunchDarkly represents a feature flag or toggle, which is a central concept in LaunchDarkly. Flags are used to control the visibility and operational state of features in your software w
Let's keep the explanations short. so the first 2 sentences should suffice. Let's remove the last sentence

2024-02-22 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +An `Audit Log` in LaunchDarkly records changes and events that occur within the platform, providing a comprehensive history of activities for compliance, troubleshooting, and analysis. The audit log
Let's keep the first sentence and delete everything afterwards.

2024-02-22 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +
Let's keep the first sentence and delete everything afterwards

2024-02-22 12:50 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +- Feature Rollout and Targeting: Use LaunchDarkly flags to safely roll out new features to users. Gradually increase the visibility of a feature to specific user segments or environments, minimizing
Remove `Gradually increase the visibility of a feature to specific user segments or environments, minimizing risk and allowing for A/B testing and canary releases. `

2024-02-22 12:56 UTC, PeyGis requested changes

2024-02-22 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +- Performance and Impact Analysis: Monitor and analyze the impact of feature releases on application performance and user behavior.
Looks like these are generic use cases of Launchdarkly. This section should be about what users can do with our Launchdarkly integration. 

1. see all their projects and their associated environments and flash
2. Get real time updates about the monitored resources: projects, flags, environments and audit

2024-02-22 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +| `integration.config.launchdarklyHost` | Your Launchdarkly host. For example https://app.terraform.io  token                                                                           | ✅       |
Please remove the reference to the terraform link and use launchdarkly instead

2024-02-22 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +helm upgrade --install terraform port-labs/port-ocean \
remove the mention of terraform and update it accordingly

2024-02-22 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/_launchdarkly_one_time_docker_parameters.mdx
> +| `OCEAN__INTEGRATION__CONFIG__LAUNCHDARKLY_HOST`  | Your Launchdarkly host. For example https://app.terraform.io                                                          | ✅       |
remove the terraform link

2024-02-22 12:56 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +name: Terraform Exporter Workflow
remove terraform

2024-02-22 13:09 UTC, mk-armah commented on docs/build-your-software-catalog/sync-data-to-catalog/project-management/launchdarkly.md
> +name: Terraform Exporter Workflow
realized i made the wrong commit.

2024-02-23 13:28 UTC, PeyGis approved these changes
LGTM

2024-03-08 11:10 UTC, closed without merging