PORT-6651 | Mini guide on connecting Jira issue to a service
port-labs/port-docs pull request #932
Opened 2024-02-22 21:05 UTC by lordsarcastic

# Description
Added Mini guide on connecting Jira issue to a service

## Updated docs pages

Please also include the path for the updated docs

- Jira (`docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md`)

2024-02-23 10:34 UTC, PeyGis requested changes
Looks great. Just some minor comments

2024-02-23 10:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +Since our Jira `issue` may already have several tags, we will need a mechanism to control how these tags will be related to our `Service` blueprint. A way to achieve this relation is to prefix the ta
Replace all mention of tags to labels

2024-02-23 10:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +1. Head back to the [Builder](https://app.getport.io/dev-portal/data-model), choose the `Jira issue` <PortTooltip id="blueprint">blueprint</PortTooltip>, and click on `New relation`:
... chose the Jira Issue (note the capitalisation of issue)

2024-02-23 10:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +The JQ below selects all labels that start with the keyword `port`. It then removes "port-" from each tag, leaving only the part that comes after it. It then selects the first match, which is equival
replace the mention of tag to label

2024-02-23 10:34 UTC, PeyGis commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +<img src='/img/guides/jiraIssueAfterServiceMapping.png' width='60%' border='1px' />
This image is not rendering well. Please replace it

2024-02-23 14:57 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +            service: .fields.labels | map(select(startswith("port"))) | map(sub("port-"; ""; "g")) | .[0]
You could also highlight the modified line. It means a user can easily see the affected line. I eventually saw the tip below which would then explain why the change happened.

```javascript
// highlight-start
service: .fields.labels | map(select(startswith("port"))) | map(sub("port-"; ""; "g")) | .[0]
// highlight-end
```

2024-03-03 12:30 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
> +First, we will need to create a [relation](/build-your-software-catalog/define-your-data-model/relate-blueprints/#what-is-a-relation) between our services and the corresponding Jira Issue.
```suggestion
First, we will need to create a [relation](/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/) between our services and the corresponding Jira Issue.
```

2024-03-03 12:37 UTC, hadar-co approved these changes

2024-03-03 12:38 UTC, merged