PORT-6847 | Write a mini guide how to connect between github pr to a jira issue
port-labs/port-docs pull request #935
Opened 2024-02-27 11:41 UTC by lordsarcastic

# Description

A mini guide showing how to connect a Github PR to a Jira Issue.

## Added docs pages

- Connect Github PR with Jira issue (`docs/guides-and-tutorials/connect-github-pr-with-jira-issue.md`)
- Images
  - `static/img/guides/githubIntegration.png`
  - `static/img/guides/githubIntegrationWithBlueprints.png`
  - `static/img/guides/githubPRCreateNewRelation.png`
  - `static/img/guides/githubPREntityAfterJiraIssueMapping.png`
  - `static/img/guides/githubPRNewJiraIssueRelation.png`

## Updated docs pages

- Guides and tutorials (`docs/guides-and-tutorials/guides-and-tutorials.md`)

2024-02-27 13:39 UTC, PeyGis requested changes
LGTM

2024-02-27 13:39 UTC, PeyGis commented on docs/guides-and-tutorials/connect-github-pr-with-jira-issue.md
> +The goal of this section is to bring our Jira issues into Port. [Port's Jira integration](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/jira/) (powered by [Ocean](https://o
Since the boards and sprints are not currently part of the integration, can we not mention them here until the ocean PR is approved?

2024-02-27 13:39 UTC, PeyGis commented on docs/guides-and-tutorials/connect-github-pr-with-jira-issue.md
> +            jiraIssue: jiraIssue: .title | match("^[A-Za-z]+-[0-9]+") .string
you seem to have a duplicate jiraIssue

2024-03-17 12:15 UTC, hadar-co commented
@lordsarcastic The build is failing, looks like there are some broken links. Please run `npm run build` locally to see where they are and fix them

2024-03-19 08:46 UTC, hadar-co approved these changes

2024-03-19 08:46 UTC, hadar-co commented on docs/build-your-software-catalog/sync-data-to-catalog/git/examples/connect-github-pr-with-jira-issue.md
> +<img src='/img/guides/githubPRNewJiraIssueRelation.png' width='60%' />
Please add `border='1px'` to the image and all other images you used

2024-03-20 09:00 UTC, merged