Port 6653 Mini Guide: Connecting Cloud Resources to Services Using Tags and JQ Mapping
port-labs/port-docs pull request #940
Opened 2024-02-29 20:01 UTC by phalbert

# Description

This guide provides step-by-step instructions on how to connect cloud resources to one or multiple services by leveraging the resource's "tags" attribute and JQ mapping techniques.

## Added docs pages

Please also include the path for the added docs

- 📝 Guides & tutorials > Connect Cloud Resources to Services (`/guides-and-tutorials/connect-cloud-resource-to-service`)

### Assets

- `static/img/guides/connectCloudServiceBlueprints.png`
- `static/img/guides/connectCloudServiceFinal.png`
- `static/img/guides/connectCloudServiceRelation.png`
- `static/img/guides/connectCloudServiceTagging.png`

2024-03-17 10:14 UTC, MPTG94 requested changes
Please take a look at my comments

2024-03-17 10:14 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples.md
> +This guide demonstrates how to connect a Cloud Resource to a service or list of services by relying on the tags property and using JQ mapping. We will be using an S3 bucket as the Cloud Resource.
The guide should mention that having the S3 bucket entities already ingested by the AWS exporter is required.

2024-03-17 10:14 UTC, MPTG94 commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples.md
> +2. Go to the `template-assets/aws/s3_bucket` folder from the [ingestion step](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/Installation). We are going
Why use a complete URL to the docs, and not a relative URL?

Also, this link just sends the user to the installation page, without any specific part of the page that indicates where the user should go.

Also you can link to the template-assets repository directly.

Just writing `template-assets/aws/s3_buckets` does not mean anything to a reader of the docs

2024-03-18 13:16 UTC, phalbert commented on docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples.md
> +2. Go to the `template-assets/aws/s3_bucket` folder from the [ingestion step](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/Installation). We are going
Alright. I have revised the section to make it clear on what the folder represents.

2024-03-19 13:18 UTC, merged