PORT-6857 Mini guide to create ECR image with tags
port-labs/port-docs pull request #959
Opened 2024-03-06 21:42 UTC by phalbert

# Description

A mini guide to create a Github workflow to generate an image with tags and push it to an AWS ECR.

## Added docs pages

Please also include the path for the added docs

- Generate ECR image with tags (`/create-self-service-experiences/setup-backend/github-workflow/examples/aws/aws.md`)

2024-03-17 10:42 UTC, MPTG94 requested changes
Please make changes according to my comments

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/aws.md
> +import DocCardList from '@theme/DocCardList';
There is no need for a dedicated page, other integrations we have examples for (Datadog, Jira, etc) do not have a dedicated page with a doc card list, they just have the sidebar category

So you can just remove this file, and keep the folder structure

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +In the following guide, you are going to create a [self-service action](https://docs.getport.io/create-self-service-experiences/) in Port that executes a [GitHub workflow](https://docs.getport.io/cre
```suggestion
In the following guide, we are going to create a [self-service action](https://docs.getport.io/create-self-service-experiences/) in Port that executes a [GitHub workflow](https://docs.getport.io/create-self-service-experiences/setup-backend/github-workflow) to:
```

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +In the following guide, you are going to create a [self-service action](https://docs.getport.io/create-self-service-experiences/) in Port that executes a [GitHub workflow](https://docs.getport.io/cre
Use internal and not full URLs (meaning that when the user clicks on the link, it does not open a new tab for him)

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +- Generate a Docker image with tags and,
```suggestion
- Generate a Docker image with tags
```

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +- Push it to an [AWS Elastic Container Registry (ECR)](https://aws.amazon.com/ecr/).
```suggestion
- Push the image to an [AWS Elastic Container Registry (ECR)](https://aws.amazon.com/ecr/).
```

2024-03-17 10:42 UTC, MPTG94 commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +      uses: actions/checkout@v2
```suggestion
      uses: actions/checkout@v4
```

2024-03-18 12:53 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/aws.md
> +import DocCardList from '@theme/DocCardList';
I actually had another [PR](https://github.com/port-labs/port-docs/pull/981) where I was adding cards for examples that exceeded one e.g. AWS, Azure, PagerDuty. 

Should I go ahead and remove this for all so that we stick to sidebar category?

cc @hadar-co

2024-03-18 13:23 UTC, phalbert commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/aws/push-image-to-ecr.md
> +In the following guide, you are going to create a [self-service action](https://docs.getport.io/create-self-service-experiences/) in Port that executes a [GitHub workflow](https://docs.getport.io/cre
alright

2024-03-20 12:39 UTC, hadar-co approved these changes

2024-03-21 12:48 UTC, closed without merging