Self service/create ec2 instance
port-labs/port-docs pull request #973
Opened 2024-03-12 09:57 UTC by mk-armah

# Description

Moving [Create EC2 Example](https://github.com/port-labs/self-service-actions-examples/blob/main/github-workflows/aws/README.md#create-an-aws-ec2-instance-action) Github action to port docs

2024-03-12 11:18 UTC, hadar-co requested changes

2024-03-12 11:18 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-an-ec2-instance.md
> +1. Create the following GitHub Action secrets:
@mk-armah Please dont use numbered lists inside other numbered lists, it looks confusing. Consider using bullets where needed.

2024-03-12 11:18 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-an-ec2-instance.md
> +2. Create a Port action in the [self-service page](https://app.getport.io/self-serve) or with the following JSON definition for the `EC2 Instance` blueprint:
should be 3?

2024-03-12 11:18 UTC, hadar-co commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-an-ec2-instance.md
> +3. Create a workflow file under .github/workflows/create-an-ec2-instance.yaml with the following content:
4?

2024-03-12 22:56 UTC, hadar-co approved these changes

2024-03-12 22:56 UTC, merged

2024-03-13 00:19 UTC, mk-armah commented
@hadar-co , i'm not seeing the changes on port docs yet. Everything okay ?