PORT-6983 | Write a github actions to put tags on ecr repo
port-labs/port-docs pull request #976
Opened 2024-03-13 06:51 UTC by lordsarcastic

# Description

A Github action that allows users put tags on ECR repositories

## Added docs pages

- Add tags to ECR repository (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md`)

2024-03-13 10:12 UTC, PeyGis requested changes
LGTM

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +[
Remove the square bracket from the action schema

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +1. Create the following GitHub action secrets.
update to `Create the following GitHub action secrets:` note the colon instead of full stop

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +- `PORT_CLIENT_SECRET` - Port Client Secret [learn more](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/api/#get-api-token)
Remove the full stops after each item

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +        },
The identifier of the ecrRepository blueprint entities is the name of the AWS Repo so why are we asking them for this information while we already have it from the repository prop?

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +      "required": ["tags"],
Is there any reason why `tags` is the only required field?

2024-03-13 10:12 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +          # }
If this is not a comment then let's remove it

2024-03-13 14:35 UTC, lordsarcastic commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +        },
All the current self-service actions correspond to an already existing integration in Ocean except for this one. The closest thing we have is the [ECR images and repository script](https://github.com/port-labs/example-ecr-images). When triggering this action, they need to know the name of the repository else it will fail. We can minimize failures by making them pick from repositories already ingested instead of typing the name manually.

So, we're giving the user two options:
- Enter the repository name manually (which the `repository_name` field is for)
- Select one of the repositories (the `repository` field) ingested from using the script.

This also gives a reason to use the ECR script.

Ideally, we'd have some form of validation that allows one of two fields to be compulsorily filled but we don't have that feature yet.

2024-03-13 14:35 UTC, lordsarcastic commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +      "required": ["tags"],
Continuing from my above explanation, it is due to the validation limitations

2024-03-13 14:35 UTC, lordsarcastic commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +          # }
It's a comment

2024-03-20 13:15 UTC, PeyGis commented on docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
> +        },
@lordsarcastic let's go with the assumption that the user already has ECR ingested in their software catalog. Which can be achieved either using the AWS Exporter of the ECR images and repository script. So instead of asking them to enter the name of the repository, it will be a selection entity where they select one of the available repos to add the tag on

2024-03-21 09:36 UTC, merged